### ISSUE TITLE
表自连接属性冲突

### ISSUE THREAD

**Issue by jinspire** [Tencent/APIJSON#125]
**环境信息**
 - 系统: mac os
 - JDK: 1.8.0_17
 - 数据库: MySQL 5.7
 - APIJSON:   3.3.0 

**问题描述**
1.有一张表如下：

`CREATE TABLE `identity_certificate` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `mobile` varchar(32) NOT NULL DEFAULT '' COMMENT '手机号',
  `name` varchar(32) NOT NULL DEFAULT '' COMMENT '姓名',
  `idcard` varchar(32) NOT NULL DEFAULT '' COMMENT '身份证号',
  `idcard_positive_url` varchar(500) NOT NULL DEFAULT '' COMMENT '身份证正面图片',
  `idcard_negative_url` varchar(500) NOT NULL DEFAULT '' COMMENT '身份证反面图片',
  `status` int(4) NOT NULL DEFAULT '0' COMMENT '认证状态(0-待审核;1-审核通过;2-已拒绝;3-二级审核中;)',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实名认证表';`

2.现在需要查询表中的最大值，sql形式如下：
select r1.* from identity_certificate r1,(select max(id) as id from identity_certificate 
group by idcard)  r2 where r1.id=r2.id

3.使用apijson请求
`{
            "[]": {
                'query': 2,
                "page": 0,
                "count": 0,
                "identity_certificate": {
                    "@schema": "auth",
                    "@column": "max(id):abcid",
                    "@group": 'idcard',
                },
                "identity_certificate": {
                    "@schema": "auth",
                    "id@": "/identity_certificate/abcid",
                },
            },
            "total@": "/[]/total"
    }`

**错误信息**
请求变成了，第一个属性被覆盖，导致请求变成了无结果的请求。
`{"[]":{"query":2,"page":0,"count":0,"identity_certificate":{"@schema":"auth","id@":"/identity_certificate/abcid"}},"total@":"/[]/total"}`

结果：
`{code: 200, msg: "success"}`

有类似于sql改名机制解决这个问题么？如何解决？

**Comment by TommyLemon** [comment]
JSON 对象的 key 不允许重复，identity_certificate:max 取别名就行了。
另外你这个需求不是非得一条 SQL 查出来，改成两次效率可能更高，尤其是有缓存的情况下。
可以类似：
```
{
    "Comment": {
        "@column": "count(DISTINCT userId):total"  //替代 query:2 查 total，因为 max(id) 函数导致查总数报错，这是一个刚发现的 bug，待解决
    },
    "[]": {
        "page": 0,
        "count": 0,
        "Comment:max": {
            "@column": "max(id):abcid",
            "@group": "userId"
        },
        "Comment": {
            "id@": "/Comment:max/abcid"
        }
    }
}
```

**Comment by jinspire** [comment]
你说的
`"@column": "count(DISTINCT userId):total" `
 //替代 query:2 查 total，因为 max(id) 函数导致查总数报错，这是一个刚发现的 bug，
这个具体是啥意思？有问题的写法是怎样的？

**Comment by TommyLemon** [comment]
```
{
    "[]": {
        "query": 2, //这样会报错
        "page": 0,
        "count": 0,
        "Comment:max": {
            "@column": "max(id):abcid",
            "@group": "userId"
        },
        "Comment": {
            "id@": "/Comment:max/abcid"
        }
    }
}
```

**Comment by TommyLemon** [comment]
不小心删了我之前的回答：
```
{
    "Comment:total": {
        "@column": "count(DISTINCT userId):total"  //替代 query:2 查 total，因为 max(id) 函数导致查总数报错，这是一个刚发现的 bug
    },
    "[]": {
        "page": 0,
        "count": 0,
        "Comment:max": {
            "@column": "max(id):abcid",
            "@group": "userId"
        },
        "Comment": {
            "id@": "/Comment:max/abcid"
        }
    }
}
```

**Comment by jasoncool520** [comment]
> @jinspire
> 
> ```
> {
>     "[]": {
>         "query": 2, //这样会报错
>         "page": 0,
>         "count": 0,
>         "Comment:max": {
>             "@column": "max(id):abcid",
>             "@group": "userId"
>         },
>         "Comment": {
>             "id@": "/Comment:max/abcid"
>         }
>     }
> }
> ```
> 
> 返回
> 
> ```
> {
>     "[]": {
>         "Comment:max": {
>             "@column": "max(id):abcid",
>             "@group": "userId"
>         },
>         "Comment": {
>             "id@": "/Comment:max/abcid"
>         }
>     },
>     "ok": false,
>     "code": 406,
>     "msg": "HEAD请求: 预编译模式下 @column:value 中 value里面用 , 分割的每一项 column:alias 中 column 必须是1个单词！如果有alias，则alias也必须为1个单词！并且不要有多余的空格！",
>     "sql:generate|cache|execute|maxExecute": "1|0|0|200",
>     "depth:count|max": "3|5",
>     "time:start|duration|end": "1587292937756|2|1587292937758"
> }
> ```
> 
> 需要改写 AbstractSQLConfig.getColumnString 737 行
> 
> ```
> return SQL.count(column != null && column.size() == 1 ? getKey(Pair.parseEntry(column.get(0), true).getKey()) : "*");
> ```
> 
> 当 column.size() == 1 时，可能里面包含一个 SQL 函数，需要改成
> 
> ```
> if (column != null && column.size() == 1) {
>   String key = getKey(Pair.parseEntry(column.get(0), true).getKey());
>   if (key != null && key.indexOf("(") < 0 && key.indexOf(")") < 0) {
>     return SQL.count(key);
>   }
> }
> 
> return SQL.count("*");
> ```
> 
> https://github.com/APIJSON/APIJSON/blob/master/APIJSON-Java-Server/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java
> 
> 我暂时没时间，你可以改完后发个 Pull Request 贡献代码，感谢

这个的修改方式应该就是直接 return SQL.count("*") 吧，然后去掉上边 origin 的 isName验证，既然HEAD是查询总记录数，返回max(id),也没有意义，像其他非聚合函数(比如一些转换函数cast等)的话， 返回原函数也不对，所以这里直接返回SQL.count("*")就ok吧

**Comment by TommyLemon** [comment]
> > @jinspire
> > ```
> > {
> >     "[]": {
> >         "query": 2, //这样会报错
> >         "page": 0,
> >         "count": 0,
> >         "Comment:max": {
> >             "@column": "max(id):abcid",
> >             "@group": "userId"
> >         },
> >         "Comment": {
> >             "id@": "/Comment:max/abcid"
> >         }
> >     }
> > }
> > ```
> > 
> > 
> > 返回
> > ```
> > {
> >     "[]": {
> >         "Comment:max": {
> >             "@column": "max(id):abcid",
> >             "@group": "userId"
> >         },
> >         "Comment": {
> >             "id@": "/Comment:max/abcid"
> >         }
> >     },
> >     "ok": false,
> >     "code": 406,
> >     "msg": "HEAD请求: 预编译模式下 @column:value 中 value里面用 , 分割的每一项 column:alias 中 column 必须是1个单词！如果有alias，则alias也必须为1个单词！并且不要有多余的空格！",
> >     "sql:generate|cache|execute|maxExecute": "1|0|0|200",
> >     "depth:count|max": "3|5",
> >     "time:start|duration|end": "1587292937756|2|1587292937758"
> > }
> > ```
> > 
> > 
> > 需要改写 AbstractSQLConfig.getColumnString 737 行
> > ```
> > return SQL.count(column != null && column.size() == 1 ? getKey(Pair.parseEntry(column.get(0), true).getKey()) : "*");
> > ```
> > 
> > 
> > 当 column.size() == 1 时，可能里面包含一个 SQL 函数，需要改成
> > ```
> > if (column != null && column.size() == 1) {
> >   String key = getKey(Pair.parseEntry(column.get(0), true).getKey());
> >   if (key != null && key.indexOf("(") < 0 && key.indexOf(")") < 0) {
> >     return SQL.count(key);
> >   }
> > }
> > 
> > return SQL.count("*");
> > ```
> > 
> > 
> > https://github.com/APIJSON/APIJSON/blob/master/APIJSON-Java-Server/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java
> > 我暂时没时间，你可以改完后发个 Pull Request 贡献代码，感谢
> 
> 这个的修改方式应该就是直接 return SQL.count("*") 吧，然后去掉上边 origin 的 isName验证，既然HEAD是查询总记录数，返回max(id),也没有意义，像其他非聚合函数(比如一些转换函数cast等)的话， 返回原函数也不对，所以这里直接返回SQL.count("*")就ok吧

对

**Comment by TommyLemon** [comment]
已解决
![image](https://user-images.githubusercontent.com/5738175/164769796-6d4b89c2-a8fa-4dd6-a1db-46939d8b47d2.png)

最新版为 5.0.0：

增强各种功能；腾讯负责人公开称赞；登记万科发起的采筑电商
https://github.com/Tencent/APIJSON/releases/tag/5.0.0
