### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Andy095** [Tencent/APIJSON#127]
无法启动

**Comment by TommyLemon** [comment]
什么都没有怎么帮你解决？

**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**



**错误信息**

**Comment by iswangc** [comment]
win10系统，jdk1.8，mysql5.7.22， apijson_go，编译后请求返回404

**Comment by TommyLemon** [comment]
> win10系统，jdk1.8，mysql5.7.22， apijson_go，编译后请求返回404

去 apijson-go 项目提 issue 吧
https://gitee.com/tiangao/apijson-go
