### ISSUE TITLE
流程还是太长可以简化吗?

### ISSUE THREAD

**Issue by wulinghui** [Tencent/APIJSON#129]
![image](https://user-images.githubusercontent.com/36905201/79412095-33160a00-7fd7-11ea-8f7c-1ca0ff03a72f.png)
可不可以不需要建实体，前端直接通过表名进行操作???

**Comment by TommyLemon** [comment]
用 APIJSONFramework 就不需要定义 Model 了，直接 Access 表新增记录来配置权限
https://github.com/APIJSON/APIJSON/issues/122
