### ISSUE TITLE
PUT请求中，远程函数参数错误

### ISSUE THREAD

**Issue by kiwiw** [Tencent/APIJSON#141]
put请求中，远程函数的参数报错。但是同一个参数，同一个远程函数，在post中调用却完全没问题。报错内容见截图。
![Uploading B1B894D6633E27DC0D8D391E5406F711.jpg…]()

**Comment by TommyLemon** [comment]
图看不了，看起来没上传完

**Comment by kiwiw** [comment]
![微信图片_20200809111627](https://user-images.githubusercontent.com/22953194/89724138-f6609980-da31-11ea-85d8-5ad41ee2e227.jpg)
不好意思，可能网络问题，重传了一下。

**Comment by kiwiw** [comment]
ok,希望能尽快解决此bug

**Comment by TommyLemon** [comment]
已解决
https://github.com/Tencent/APIJSON/commit/3e86b0921069a5fad7358cb45932beae781c2f87
![image](https://user-images.githubusercontent.com/5738175/103154947-5c2da200-47d6-11eb-9af0-c35ff85cfd31.png)
![image](https://user-images.githubusercontent.com/5738175/103154944-4ddf8600-47d6-11eb-8cc2-ea915fb9ba82.png)
