### ISSUE TITLE
APIJSONSQLConfig 实现这个类之后无法进行spring 注入

### ISSUE THREAD

**Issue by JellyfishChips** [Tencent/APIJSON#155]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

这个配置类实现之后，无法进行spring注入，注入进来都为null，是我的方式不对?
导致无法加载配置中心的配置。

**错误信息**

**Comment by JellyfishChips** [comment]
apijson-framework： 4.1.0
apijson-orm： 4.0.0

**Comment by TommyLemon** [comment]
不支持，别这么用，按 文档 和 Demo 来
