### ISSUE TITLE
关联查询时 “/” 的具体含义是什么

### ISSUE THREAD

**Issue by elonsolar** [Tencent/APIJSON#160]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

使用get 请求进行关联查询， "/"表示的整个对象的根 ，还是当前的层级的父级,亦或是其他，  /[] /和 []/ 的区别是什么，

```
{
    "[]": { // 1
        "Zone": {
            "@column": "line_name:ln,zone_name,zone_id",
            "line_name$": "%线%",
            "[]": { //2
                "ZoneUnit": {
                    "zone_id@": "[]/Zone/zone_id",  // 此处的 []  为何 是指代 最外层（1 ），而不是（2）
                   "Unit":{
                       "unit_id@":"/unit_id"  //这里为何不用从根部找了
                   }
                }
            }
        },
        "page": 1,
        "count": 2
    },
    "total@": "/[]/total" //此处 为何是 /[]
}

```
**错误信息**

**Comment by TommyLemon** [comment]
/ 开头的是相对路径，从所处容器的父容器路径开始。如果不了解可以都写成绝对路径，类似
[]/total
[]/Zone/[]/ZoneUnit/unit_id

"total" 这个字段本来就在最外层了，
"total@": "/[]/total"
和
"total@": "[]/total"
最终都会从最外层开始，执行没区别。


7.每个对象都有一个唯一的路径(或者叫地址)，假设对象名为refKey，则用 key0/key1/.../refKey 表示。下同。
https://github.com/Tencent/APIJSON/blob/master/Document.md#31-%E6%93%8D%E4%BD%9C%E6%96%B9%E6%B3%95


获取类似微信朋友圈的动态列表
https://github.com/Tencent/APIJSON/blob/master/Document.md#%E8%8E%B7%E5%8F%96%E7%B1%BB%E4%BC%BC%E5%BE%AE%E4%BF%A1%E6%9C%8B%E5%8F%8B%E5%9C%88%E7%9A%84%E5%8A%A8%E6%80%81%E5%88%97%E8%A1%A8
请求：

{
  "[]":{                             //请求一个数组
    "page":0,                        //数组条件
    "count":2,
    "Moment":{                       //请求一个名为Moment的对象
      "content$":"%a%"               //对象条件，搜索content中包含a的动态
    },
    "User":{
      "id@":"/Moment/userId",        //User.id = Moment.userId  缺省引用赋值路径，从所处容器的父容器路径开始
      "@column":"id,name,head"       //指定返回字段
    },
    "Comment[]":{                    //请求一个名为Comment的数组，并去除Comment包装
      "count":2,
      "Comment":{
        "momentId@":"[]/Moment/id"   //Comment.momentId = Moment.id  完整引用赋值路径
      }
    }
  }
}

**Comment by TommyLemon** [comment]
```js
{
    "[]": {
        "count": 3,
        "page": 0,
        "query": 2,
        "Moment": {
            "@order": "date+"
        },
        "User[]": {
            "count": 3,
            "query": 2,
            "User": {
                "id{}@": "[]/Moment/praiseUserIdList",
                "@column": "id,name"
            }
        },
        "[]": {
            "count": 3,
            "query": 2,
            "Comment": {
                "@order": "date+",
                "momentId@": "[]/Moment/id"
            }
        },
        "praiseCount@": "/User[]/total",  // 缺省路径，对应 完整路径为 []/User[]/total
        "commentCount@": "[]/[]/total"
    },
    "total@": "[]/total"  // 完整路径，最外层用 缺省路径 /[]/total 执行结果也一样
}
```                                                                                                                                                                                                              

![image](https://user-images.githubusercontent.com/5738175/99969658-c1f0cd80-2dd5-11eb-883b-4da1b1c0a752.png)
