### ISSUE TITLE
docker部署数据库链接问题

### ISSUE THREAD

**Issue by chaolei-peng** [Tencent/APIJSON#163]
**环境信息**
 - 系统: linuxCentos7+docker部署（项目，数据库均在容器中运行）
 - JDK: 1.8.0_17 
 - 数据库:Version: '10.5.8-MariaDB-1:10.5.8+maria~focal'docker容器   
 - APIJSON:  4.4.0 

**问题描述**
通过docker部署APijson链接数据库报错，数据库端口都正常，其他项目能够链接上，请教该怎么排查这个问题？致谢！

![image](https://user-images.githubusercontent.com/16797866/100492901-32984100-316c-11eb-8b7d-a7ccc44ec7ff.png)

**Comment by chaolei-peng** [comment]
问题找到了，貌似不能使用localhost,用公网IP是可以的，但我其他springBoot项目使用localHost是正常的，有什么不同么？

**Comment by TommyLemon** [comment]
目前未做 MariaDB 的适配，10.5.8 对应 MySQL 可能是得用 5.7.16 之类的低版本。
