### ISSUE TITLE
查询日期报错

### ISSUE THREAD

**Issue by zemelLeong** [Tencent/APIJSON#168]
**环境信息**
 - 系统: Windows 10 
 - JDK: 1.8.0_17
 - 数据库: MySQL 5.7.14
 - APIJSON:  4.4.6

**问题描述**
执行如下查询语句查询日期报错
![image](https://user-images.githubusercontent.com/26835087/102014243-fd0c6e00-3d8f-11eb-98e9-e6826e6b15bf.png)
![image](https://user-images.githubusercontent.com/26835087/102014255-05fd3f80-3d90-11eb-82a7-3d568901d8c9.png)

**Comment by TommyLemon** [comment]
https://github.com/Tencent/APIJSON/issues/112
