### ISSUE TITLE
请问 com.github.Tencent.APIJSON.4.3.1 源码包为什么没有呢 maven

### ISSUE THREAD

**Issue by wkchunqiu** [Tencent/APIJSON#171]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

**错误信息**

**Comment by TommyLemon** [comment]
应该是网络问题，可以改用 APIJSONBoot/libs/apijson-orm.jar 
https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server/APIJSONBoot/libs

**Comment by wkchunqiu** [comment]
hi：
		<dependency>
			<groupId>com.github.Tencent</groupId>
			<artifactId>APIJSON</artifactId>
			<version>4.3.1</version>
		</dependency>
我的意思是说你这个包没有源码，你提供的lib里面也没有这个jar？ 难道用apijson-orm.jar这个替代？

**Comment by wkchunqiu** [comment]
> 应该是网络问题，可以改用 APIJSONBoot/libs/apijson-orm.jar
> https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server/APIJSONBoot/libs

hi：

com.github.Tencent
APIJSON
4.3.1

我的意思是说你这个包没有源码，你提供的lib里面也没有这个jar？ 难道用apijson-orm.jar这个替代？

**Comment by wkchunqiu** [comment]
> 应该是网络问题，可以改用 APIJSONBoot/libs/apijson-orm.jar
> https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server/APIJSONBoot/libs

com.github.Tencent
APIJSON
4.3.1

apijson-orm.jar这个包是替代APIJSON的包 ，还是 APIJSON的源码包就是apijson-orm.jar

**Comment by TommyLemon** [comment]
apijson-orm.jar 是用 [APIJSON](https://github.com/Tencent/APIJSON) 主项目中 [APIJSONORM](https://github.com/Tencent/APIJSON/tree/master/APIJSONORM) 工程打包出来的，这就是源码

**Comment by wkchunqiu** [comment]
> apijson-orm.jar 是用 [APIJSON](https://github.com/Tencent/APIJSON) 主项目中 [APIJSONORM](https://github.com/Tencent/APIJSON/tree/master/APIJSONORM) 工程打包出来的，这就是源码，按文档或 Demo 来依赖

这个问题解决了，谢谢，点赞
还有一个问题，本地下载demo使用APIJSONBoot这个搭建的一个项目，必须得通过login登录才能操作表的 增加 删除 和修改吗？ 自己建立一个表必须有这个列userId吗？
例如我本地建立一个ddd表
执行删除操作后台强行给我拼接一个userId这个字段，实际我根本没有这个列，必须建表的时候强关联userId吗？
DELETE FROM `wcq`.`ddd` WHERE  (  (`id` = 1) AND (`userId` = 82001)  )

**Comment by TommyLemon** [comment]
https://github.com/Tencent/APIJSON/issues/12
https://github.com/Tencent/APIJSON/issues/67

**Comment by wkchunqiu** [comment]
hi：
问题一：假设有自己的业务逻辑，是自己写函数调用吗？
问题二：假设查询的数据，结果是从数据库的表和RPC或者HTTP接口查询合并出来的结果这个也是通过函数搞定？

**Comment by wkchunqiu** [comment]
hi：
问题一：假设有自己的业务逻辑，是自己写函数调用吗？
问题二：假设查询的数据，结果是从数据库的表和RPC或者HTTP接口查询合并出来的结果这个也是通过函数搞定？

**Comment by wkchunqiu** [comment]
> apijson-orm.jar 是用 [APIJSON](https://github.com/Tencent/APIJSON) 主项目中 [APIJSONORM](https://github.com/Tencent/APIJSON/tree/master/APIJSONORM) 工程打包出来的，这就是源码，按文档或 Demo 来依赖



> #12
> #67

hi：
问题一：假设有自己的业务逻辑，是自己写函数调用吗？
问题二：假设查询的数据，结果是从数据库的表和RPC或者HTTP接口查询合并出来的结果这个也是通过函数搞定？

**Comment by wkchunqiu** [comment]
> > apijson-orm.jar 是用 [APIJSON](https://github.com/Tencent/APIJSON) 主项目中 [APIJSONORM](https://github.com/Tencent/APIJSON/tree/master/APIJSONORM) 工程打包出来的，这就是源码，按文档或 Demo 来依赖
> 
> 这个问题解决了，谢谢，点赞
> 还有一个问题，本地下载demo使用APIJSONBoot这个搭建的一个项目，必须得通过login登录才能操作表的 增加 删除 和修改吗？ 自己建立一个表必须有这个列userId吗？
> 例如我本地建立一个ddd表
> 执行删除操作后台强行给我拼接一个userId这个字段，实际我根本没有这个列，必须建表的时候强关联userId吗？
> DELETE FROM `wcq`.`ddd` WHERE ( (`id` = 1) AND (`userId` = 82001) )

![image](https://user-images.githubusercontent.com/23184234/102327504-cc5f4b00-3fc0-11eb-97f3-3a9e578c2b2e.png)

**Comment by wkchunqiu** [comment]
> > > apijson-orm.jar 是用 [APIJSON](https://github.com/Tencent/APIJSON) 主项目中 [APIJSONORM](https://github.com/Tencent/APIJSON/tree/master/APIJSONORM) 工程打包出来的，这就是源码，按文档或 Demo 来依赖
> > 
> > 
> > 这个问题解决了，谢谢，点赞
> > 还有一个问题，本地下载demo使用APIJSONBoot这个搭建的一个项目，必须得通过login登录才能操作表的 增加 删除 和修改吗？ 自己建立一个表必须有这个列userId吗？
> > 例如我本地建立一个ddd表
> > 执行删除操作后台强行给我拼接一个userId这个字段，实际我根本没有这个列，必须建表的时候强关联userId吗？
> > DELETE FROM `wcq`.`ddd` WHERE ( (`id` = 1) AND (`userId` = 82001) )
> 
> ![image](https://user-images.githubusercontent.com/23184234/102327504-cc5f4b00-3fc0-11eb-97f3-3a9e578c2b2e.png)

返回信息怎么写着对象不存在，不是说新建立表不需要建立实体对象了吗？

**Comment by wkchunqiu** [comment]
> #12
> #67

hi: APIJSON是不是用户没有和具体有强耦合，上送什么角色，和可以访问表的具体方法配置什么角色，一致就OK了是吗？使用这个框架必须使用你们这套权限控制了是吗？

**Comment by TommyLemon** [comment]
> > apijson-orm.jar 是用 [APIJSON](https://github.com/Tencent/APIJSON) 主项目中 [APIJSONORM](https://github.com/Tencent/APIJSON/tree/master/APIJSONORM) 工程打包出来的，这就是源码，按文档或 Demo 来依赖
> 
> > #12
> > #67
> 
> hi：
> 问题一：假设有自己的业务逻辑，是自己写函数调用吗？
> 问题二：假设查询的数据，结果是从数据库的表和RPC或者HTTP接口查询合并出来的结果这个也是通过函数搞定？

业务逻辑都用远程函数解决
https://github.com/Tencent/APIJSON#1%E5%A6%82%E4%BD%95%E5%AE%9A%E5%88%B6%E4%B8%9A%E5%8A%A1%E9%80%BB%E8%BE%91

**Comment by TommyLemon** [comment]
> > > > apijson-orm.jar 是用 [APIJSON](https://github.com/Tencent/APIJSON) 主项目中 [APIJSONORM](https://github.com/Tencent/APIJSON/tree/master/APIJSONORM) 工程打包出来的，这就是源码，按文档或 Demo 来依赖
> > > 
> > > 
> > > 这个问题解决了，谢谢，点赞
> > > 还有一个问题，本地下载demo使用APIJSONBoot这个搭建的一个项目，必须得通过login登录才能操作表的 增加 删除 和修改吗？ 自己建立一个表必须有这个列userId吗？
> > > 例如我本地建立一个ddd表
> > > 执行删除操作后台强行给我拼接一个userId这个字段，实际我根本没有这个列，必须建表的时候强关联userId吗？
> > > DELETE FROM `wcq`.`ddd` WHERE ( (`id` = 1) AND (`userId` = 82001) )
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/23184234/102327504-cc5f4b00-3fc0-11eb-97f3-3a9e578c2b2e.png)
> 
> 返回信息怎么写着对象不存在，不是说新建立表不需要建立实体对象了吗？

用了 apijson-framework 就不需要写代码，直接 Access 表配置权限

**Comment by TommyLemon** [comment]
> > #12
> > #67
> 
> hi: APIJSON是不是用户没有和具体有强耦合，上送什么角色，和可以访问表的具体方法配置什么角色，一致就OK了是吗？使用这个框架必须使用你们这套权限控制了是吗？

语句不通。默认的权限控制可以重写方法来扩展或者屏蔽，先看文档、搜 issue ，都找不到再问，避免重复提问
https://github.com/Tencent/APIJSON/issues/12#issuecomment-462603308
