### ISSUE TITLE
请求过慢

### ISSUE THREAD

**Issue by shanhan0** [Tencent/APIJSON#172]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

由于后端在表中加了索引，所以导致请求过慢，快一分钟了如何解决呢？

**Comment by TommyLemon** [comment]
这个要具体分析，把详细的 DDL、表数据量、APIJSON 请求及结果、控制台日志 发下。
可以自己先用 @explain: true 检查 SQL 语句
https://www.jianshu.com/p/ea3fc71fdc45

**Comment by TommyLemon** [comment]
如果是在批量 增/删/改 时导致，应该是因为频发查库读 Request 表的参数校验规则 structure 导致，已经在 [4.4.5](https://github.com/Tencent/APIJSON/releases/tag/4.5.1) 修复，建议升级到 [4.5.1](https://github.com/Tencent/APIJSON/releases/tag/4.5.1) 以上
https://github.com/Tencent/APIJSON/releases
