### ISSUE TITLE
请问，如果本身已经有统一登录系统，APIJSON，还必须登录才能操作，这个登录有兼容考虑吗

### ISSUE THREAD

**Issue by wkchunqiu** [Tencent/APIJSON#174]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

**错误信息**

**Comment by TommyLemon** [comment]
https://github.com/Tencent/APIJSON/issues/12#issuecomment-462603308
