### ISSUE TITLE
sum求和和分组一起使用，导致分页不对

### ISSUE THREAD

**Issue by shanhan0** [Tencent/APIJSON#176]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

问题：   由于使用了分组查询，所以分页的总数不对了。

本来不用分组和不求总和，总数量2000条。
用了分组之后总数是100条，
初始化显示的是对的,但是一点击分页就变成2000条了

**Comment by TommyLemon** [comment]
APIJSON 请求、APIJSON 结果、直接把 SQL 放数据库执行结果，都截屏发出来，JSON 文本也都发下
