### ISSUE TITLE
有直接将JSON转换成SQL的方法吗？

### ISSUE THREAD

**Issue by everything8** [Tencent/APIJSON#177]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

后台内部使用APIJSON，查询条件来自于内部逻辑，而不是来自前端请求，是否可以直接封装JSON对象，然后直接执行？有没有这样的方法？

**Comment by TommyLemon** [comment]
AbstractSQLConfig 有两个方法
newSQLConfig 传 JSON 构造实例
getSQL 转为 SQL
https://github.com/Tencent/APIJSON/blob/7fa6ac181e4871e54f9215d2c2ec9726693bd219/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java

有个纯粹就是 JSON->SQL 的 APIJSON 第三方库
https://github.com/Zerounary/APIJSONParser

**Comment by everything8** [comment]
我用第一个试下，第二个毕竟是第三方库，不能保证可以一直跟APIJSON同步更新

**Comment by wulinghui** [comment]
fdsa
