### ISSUE TITLE
后台要访问的数据表，一定要定义Model吗？

### ISSUE THREAD

**Issue by everything8** [Tencent/APIJSON#178]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

数据表如果没定义Model是否支持查询？期望在动态新增表时，不需要修改后台代码

**Comment by TommyLemon** [comment]
可以用 apijson-framework，不用写代码，在 Access 表配置权限就行了，调用 /reload 接口还可以热重载配置，服务都不用重启
https://github.com/APIJSON/apijson-framework

APIJSON-Demo 里的 3 个都是用了 apijson-framework
https://github.com/APIJSON/APIJSON-Demo
