### ISSUE TITLE
说明文档错误

### ISSUE THREAD

**Issue by bodian520** [Tencent/APIJSON#180]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:    apijson-java-server/java-springboot

**问题描述**

https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server

  必须先导入sys.sql到数据库中，否则启动报错，无法连接到sys.access表
    说明文档中第二步 配置后端工程 内容中，并没有提示需要先导入数据文件

**错误信息**

**Comment by TommyLemon** [comment]
文档确实没跟上代码改动，感谢建议
