### ISSUE TITLE
Access表插入新表行记录，表名带下划线，启动提示表名不合法

### ISSUE THREAD

**Issue by bodian520** [Tencent/APIJSON#181]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

https://my.oschina.net/tommylemon/blog/889074

1.按照该文档，在ACCESS表插入一行，原始表名为‘t_task’，插入行记录name或者alias='t_task'，启动报错，提示表名不合法，
但是't_task'应该是mysql的合法表名

**错误信息**

**Comment by TommyLemon** [comment]
请求 JSON 参数 和 Access 表中 APIJSON 表名都以大写字母开头
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.1
![image](https://user-images.githubusercontent.com/5738175/103212041-c82e1880-4944-11eb-9d36-35b48d918b31.png)

数据库实际表名则不一定，因为 MySQL 默认大小写不敏感，大写小写都对，如果是 PostgreSQL 这种大小写敏感的，可以配置 alias
