### ISSUE TITLE
数据库资源未释放

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Tencent/APIJSON#183]
statement未释放
https://github.com/Tencent/APIJSON/blob/297c251f36bfacac4fb896f002f2c6a90c4cddf0/APIJSONORM/src/main/java/apijson/orm/AbstractSQLExecutor.java#L181-L189
https://github.com/Tencent/APIJSON/blob/297c251f36bfacac4fb896f002f2c6a90c4cddf0/APIJSONORM/src/main/java/apijson/orm/AbstractSQLExecutor.java#L768
https://github.com/Tencent/APIJSON/blob/297c251f36bfacac4fb896f002f2c6a90c4cddf0/APIJSONORM/src/main/java/apijson/orm/AbstractSQLExecutor.java#L773
rs可能因异常未释放
https://github.com/Tencent/APIJSON/blob/297c251f36bfacac4fb896f002f2c6a90c4cddf0/APIJSONORM/src/main/java/apijson/orm/AbstractSQLExecutor.java#L194-L202
https://github.com/Tencent/APIJSON/blob/297c251f36bfacac4fb896f002f2c6a90c4cddf0/APIJSONORM/src/main/java/apijson/orm/AbstractSQLExecutor.java#L235-L299
https://github.com/Tencent/APIJSON/blob/297c251f36bfacac4fb896f002f2c6a90c4cddf0/APIJSONORM/src/main/java/apijson/orm/AbstractSQLExecutor.java#L400-L433
https://github.com/Tencent/APIJSON/blob/297c251f36bfacac4fb896f002f2c6a90c4cddf0/APIJSONORM/src/main/java/apijson/orm/AbstractSQLExecutor.java#L194-L203
程序不应依赖于虚拟机自动的回收数据库资源，而应手动在finally代码块中进行数据库资源释放操作。

**Comment by TommyLemon** [comment]
会在请求会话结束后通过 close 方法中调 connection.close 
![image](https://user-images.githubusercontent.com/5738175/103267841-7097b780-49ed-11eb-9ac5-90f45129b711.png)

来间接 closeAllOpenStatements
![image](https://user-images.githubusercontent.com/5738175/103267818-61b10500-49ed-11eb-835c-5dde36b3bbfd.png)

如果提前调 statement.close，可能会影响 PreparedStatement 对 SQL 模板的复用，这里我后面再仔细研究下

**Comment by QiAnXinCodeSafe** [comment]
PreparedStatement 复用确实不能即时关闭，ResultSet可以，可能因异常未释放，可以完善到finally块中

**Comment by TommyLemon** [comment]
确实有可能中间抛异常导致 rs.close 未及时调用，感谢

**Comment by TommyLemon** [comment]
已修复
https://github.com/Tencent/APIJSON/commit/f05df3a1887999769ac6db18cfa8f314a5585165
