### ISSUE TITLE
流资源未释放

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Tencent/APIJSON#184]
https://github.com/Tencent/APIJSON/blob/297c251f36bfacac4fb896f002f2c6a90c4cddf0/APIJSONORM/src/main/java/apijson/orm/AbstractSQLExecutor.java#L572-L579

程序不应依赖于Java虚拟机自动回收流资源，而需要手动在finally代码块中进行流资源的释放。

**Comment by TommyLemon** [comment]
感谢反馈

**Comment by TommyLemon** [comment]
已修复
https://github.com/Tencent/APIJSON/commit/f05df3a1887999769ac6db18cfa8f314a5585165
