### ISSUE TITLE
数组上调用toString()

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Tencent/APIJSON#185]
直接使用method拼接，默认调用toString方法
数组类中toString进行重写，仅仅是重载为类的静态方法。所以数组直接调用toString方法的结果并不是数组中元素的值，而是[数组的类型@内存地址哈希码]
https://github.com/Tencent/APIJSON/blob/297c251f36bfacac4fb896f002f2c6a90c4cddf0/APIJSONORM/src/main/java/apijson/orm/AbstractFunctionParser.java#L170
可以手工拼接或者使用Java工具类Arrays中的toString方法转化数组为字符串。

**Comment by TommyLemon** [comment]
这里是写错了，应该改用 ml，感谢反馈
![image](https://user-images.githubusercontent.com/5738175/103268141-f6b3fe00-49ed-11eb-9cc5-82addaf65a77.png)

**Comment by kxlv2000** [comment]
您好，请问问题解决了吗，我们可以尝试修复此 bug 吗
