### ISSUE TITLE
请问REQUEST 表如何配置？

### ISSUE THREAD

**Issue by bodian520** [Tencent/APIJSON#188]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

麻烦补充下文档

![image](https://user-images.githubusercontent.com/62273402/103515864-76d4da80-4eaa-11eb-9c73-3beb6ab42e13.png)

**错误信息**

**Comment by TommyLemon** [comment]
https://github.com/Tencent/APIJSON/wiki#%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86
