### ISSUE TITLE
多表关联

### ISSUE THREAD

**Issue by shanhan0** [Tencent/APIJSON#192]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

查询：
"[]": {
        "TaxInfo": {
            "@column": "tax"
        },
        "query": 2,
        "page": 0,
        "count": 10
    },
    "total@": "/[]/total"

返回：

"[]":  [
           {
              "ExCompanyTaxInfo":  {
                  "tax": 0
               }
          },
         {
            "ExCompanyTaxInfo":  {
               "tax": 0
             }
        }]

换成关联查询
"[]": {
        "ExXsrInfoViews": {
            "@group": "userId",
            "@column": "sum(lrlTotal):lrlTotal;sum(cjTotal):cjTotal;sum(cjhtTotal):cjhtTotal;sum(zTotal):zTotal;sum(sfeTotal):sfeTotal;time"
        },
        "ExXsDealInfos": {
            "@group": "company_id",
            "sign_org_full_id@": "/ExXsrInfoViews/xsr_org_full_id",
            "@column": "company_id"
        },
        "ExCompanyTaxInfo": {
            "company_id@": "/ExXsDealInfos/company_id",
            "@group": "company_id,year",
            "@column": "tax"
        },
        "query": 2,
        "page": 0,
        "count": 10
    },
    "total@": "/[]/total"

返回
"[]":  [
 {
        "ExXsrInfoViews":  {
        "userId": 69 ,
        "userName": "哈哈" ,
        "xsr_org_dept_id": 61 ,
        "xsr_org_full_id": "1/67" ,
        "lrlTotal": 70 ,
        "cjTotal": 0 ,
        "cjhtTotal": 0 ,
        "zTotal": 0 ,
        "sfeTotal": 0 ,
        "time": "2020-09-14"
    }
}]

就没有tax字段，  希望返回tax字段，

关联表的顺序是否影响返回结果？

**Comment by shanhan0** [comment]
感觉是只返回了一个表的数据

**Comment by TommyLemon** [comment]
因为主表 @column 没把副表关联用到的字段 xsr_org_full_id 写进去
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2
![image](https://user-images.githubusercontent.com/5738175/104689530-a05cf400-573d-11eb-9669-f1c84b3cc7e3.png)

如果不允许，报错 not allow full_group_by，可以改数据库配置，或者多加一个 ExXsrInfoViews 表对象，例如
"ExXsrInfoViews:first": {
"userId@": "/ExXsrInfoViews/userId"
}
下面 ExXsDealInfos 和 ExXsrInfoViews:first 关联

**Comment by shanhan0** [comment]
你好，我想请教下具体是怎么使用的？
三个表关联，主表的字段里面，必须另外两个副表的关联的那个字段是这个意思不




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/APIJSON"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 下午2:32
收件人:&nbsp;"Tencent/APIJSON"<APIJSON@noreply.github.com&gt;;
抄送:&nbsp;"2993369376"<2993369376@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/APIJSON] 多表关联 (#192)





 
因为主表 @column 没把副表关联用到的字段 xsr_org_full_id 写进去
 https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2
 
 
如果不允许，报错 not allow full_group_by，可以改数据库配置，或者多加一个 ExXsrInfoViews 表对象，例如
 "ExXsrInfoViews:first": {
 "userId@": "/ExXsrInfoViews/userId"
 }
 下面 ExXsDealInfos 和 ExXsrInfoViews:first 关联

**Comment by TommyLemon** [comment]
对，改成
```js
"@column": "xsr_org_full_id;sum(lrlTotal):lrlTotal;sum(cjTotal):cjTotal;sum(cjhtTotal):cjhtTotal;sum(zTotal):zTotal;sum(sfeTotal):sfeTotal;time"
```
引用赋值查不到关联的 refKey(这里是xsr_org_full_id) 的值时会认为这个记录不存在

**Comment by shanhan0** [comment]
我这个就是这么写的，我没复制全，还是只是返回一个表的的数据

**Comment by TommyLemon** [comment]
最外层加 
"@explain":true
看下 SQL，粘贴到数据库试试。
还可以看控制台日志

**Comment by shanhan0** [comment]
好的，感谢解答

**Comment by shanhan0** [comment]
还是不行 

{
    "@Explain": true,
    "[]": {
        "ExXsrInfo": {
           "@column": "userId,userName,xsr_org_dept_id,xsr_org_full_id;sum(zTotal):zTotal;sum(sfeTotal):sfeTotal;time",
            "@group": "userId"
        },
        "ExXsDeal": {
            "sign_org_full_id@": "/ExXsrInfo/xsr_org_full_id",
            "@group": "company_id",
            "@column": "company_id,sign_org_full_id"
        },
        "ExCompanyTaxInfo": {
            "company_id@": "/ExXsDeal/company_id",
            "@group": "company_id,year"，
            "@column": "tax,company_id,year",
        },
        "query": 2,
        "page": 0,
        "count": 10
    },
    "total@": "/[]/total"
}
                         

返回：  还是最上面表查找到的字段

{
      "ExXsrInfo":  {
      "userId": 69 ,
      "userName": "小和" ,
      "xsr_org_dept_id": 68999 ,
      "xsr_org_full_id": "1/99999" ,
      "zTotal": 0 ,
      "sfeTotal": 0 ,
      "time": "2020-09-14"
}


三个表关联查询，还是只返回第一个表的字段

**Comment by shanhan0** [comment]
写上    "@explain": true,
会报错
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'EXPLAIN SELECT * FROM `bi`.`ex_xsr_info_view` GROUP BY `userId`) a'

**Comment by TommyLemon** [comment]
> 写上 "@Explain": true,
> 会报错
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'EXPLAIN SELECT * FROM `bi`.`ex_xsr_info_view` GROUP BY `userId`) a'

为啥最后多一个字母 a ？具体看 APIJSON 日志
