### ISSUE TITLE
APIJSONORM would not compile on newer version of JDK starting from 11 

### ISSUE THREAD

**Issue by sunxiaoguang** [Tencent/APIJSON#195]
APIJSONORM does not compile on newer version of JDK starting from 11 as javax.activation package were removed from J2SE per JEP 320 request. There is a simple patch #194 to fix it,  please take a look, thanks.

**Comment by TommyLemon** [comment]
Thank you very much, the pr was merged and we added you as one of APIJSON's contributors!

https://github.com/Tencent/APIJSON#%E5%BC%80%E6%BA%90%E8%AE%B8%E5%8F%AF
![image](https://user-images.githubusercontent.com/5738175/105135561-340e3600-5b2b-11eb-8165-51774644caa7.png)

https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md
![image](https://user-images.githubusercontent.com/5738175/105135769-88191a80-5b2b-11eb-9f1c-55e546fa964d.png)

**Comment by TommyLemon** [comment]
And also, welcome to join the APIJSON Contributors Group(Wechat) by contacting LonelyExplorer.
