### ISSUE TITLE
比如创建一个菜单，我想由后端赋值创建时间和创建人，请问怎么操作？

### ISSUE THREAD

**Issue by ImagineL** [Tencent/APIJSON#196]
**具体说下**
比如创建一个菜单，我想由后端赋值创建时间和创建人，请问怎么操作？
![image](https://user-images.githubusercontent.com/9377813/105487616-5cdd2980-5ceb-11eb-9621-24c345f4fb4d.png)
`{
    "Application":{
        "name":"测试应用",
        "appkey": "kdyh",
        "type": 2,
        "gmt_create()":"getNow()"
    },
    "tag":"Application"
}`

我觉得我比较理想的方式应该是这样： "gmt_create()":"getNow()"，后端就识别到赋值并写入数据库了。但是实际上，这个是将当前时间返回给前端。

求大佬帮助 [哭泣][哭泣][哭泣]

**为什么**
因为这个场景我太常用了。我试过远程函数调用，但是都是以response的方式返回。

**Comment by TommyLemon** [comment]
### 如果每个接口逻辑不一样，可以在你已经做到的基础上新增
```js
"gmt_create@":"/Application/gmt_create"
```
当然需要保证
```js
"gmt_create()":"getNow()" 
```
先执行，所以可以用优先级更高的标识：
```js
"gmt_create-()":"getNow()" 
```
最终是
```js
{
    "Application": {
        "name": "测试应用",
        "appkey": "kdyh",
        "type": 2,
        "gmt_create-()": "getNow()",
        "gmt_create@": "/Application/gmt_create"
    },
    "tag": "Application"
}
```
或者干脆把远程函数写在 Application 上方
```js
{
    "gmt_create-()": "getNow()",
    "Application": {
        "name": "测试应用",
        "appkey": "kdyh",
        "type": 2,
        "gmt_create@": "gmt_create"
    },
    "tag": "Application"
}
```


### 如果是要统一处理，可以：
在重写 DemoObjectParser 重写 newSQLConfig，把从 Controller 经过 DemoParser 传过来的 create_time, creator_id 等 put 进去
https://github.com/Tencent/APIJSON/issues/148#issuecomment-728653332

**Comment by ImagineL** [comment]
超级感谢～～～感谢大佬回复，一会就去试试～谢谢

**Comment by ImagineL** [comment]
非常灵活的框架～
