### ISSUE TITLE
这个项目太混乱了

### ISSUE THREAD

**Issue by wenj91** [Tencent/APIJSON#197]
感觉项目立意理念挺好的，为什么搞得一团糟的感觉，readme完全就是在吹嘘

**Comment by TommyLemon** [comment]
没调研清楚不要胡乱下结论，看 Star APIJSON 的前 10 页几乎每页都有 Tencent 员工账号，另外微软、腾讯、阿里、蚂蚁金服、美团、字节跳动、京东、拼多多、百度、滴滴、华为、Twitter 这么多国内外大厂的员工都是好忽悠的吗？
https://github.com/Tencent/APIJSON/stargazers?after=Y3Vyc29yOnYyOpO5MjAyMC0xMi0xNVQxNDoxNDo1OCswODowMADODv3EFQ%3D%3D

![image](https://user-images.githubusercontent.com/5738175/105845881-62ea4780-6016-11eb-8788-e1c696403d1e.png)
https://github.com/Tencent/APIJSON/stargazers?after=Y3Vyc29yOnYyOpO5MjAyMS0wMS0xM1QyMjo0NDoxNSswODowMADOD0FMXw%3D%3D
![image](https://user-images.githubusercontent.com/5738175/105846016-8a411480-6016-11eb-8adc-30a749e2b4aa.png)
![image](https://user-images.githubusercontent.com/5738175/105846116-ac3a9700-6016-11eb-973d-c1aa8619901f.png)
![image](https://user-images.githubusercontent.com/5738175/105846349-063b5c80-6017-11eb-8d9d-5ef2a1af9057.png)
![image](https://user-images.githubusercontent.com/5738175/105846889-caed5d80-6017-11eb-8a9a-817e04b23685.png)
![image](https://user-images.githubusercontent.com/5738175/105846981-f40dee00-6017-11eb-8040-5bf606c3d166.png)
![image](https://user-images.githubusercontent.com/5738175/105847072-156eda00-6018-11eb-8b8f-ce06c05d3d5d.png)

![image](https://user-images.githubusercontent.com/5738175/105846720-8b267600-6017-11eb-98ab-47dd5a710827.png)

![image](https://user-images.githubusercontent.com/5738175/105845685-23bbf680-6016-11eb-9ee7-57b89065f410.png)
![image](https://user-images.githubusercontent.com/5738175/105845836-54039500-6016-11eb-9c31-041ade4e2fe1.png)


这个是腾讯同事写的，有提到 APIJSON
https://zhuanlan.zhihu.com/p/346552437
![image](https://user-images.githubusercontent.com/5738175/105845044-21a56800-6015-11eb-8f4f-8224987d0f4f.png)

**Comment by TommyLemon** [comment]
这个是腾讯同事写的，有提到 APIJSON
https://zhuanlan.zhihu.com/p/346552437
![image](https://user-images.githubusercontent.com/5738175/105845044-21a56800-6015-11eb-8f4f-8224987d0f4f.png)

**Comment by wenj91** [comment]
本意不是批评这个项目，而是想让作者多关注开发文档，其他一些宣传广告就没必要占用wiki资源；
而且感觉没必要上来就甩一堆stargazers，作为想参与的开发者来说这些就是废话

**Comment by TommyLemon** [comment]
中文文档、英文文档、视频教程、在线体验
![image](https://user-images.githubusercontent.com/5738175/105938652-a5ea0080-6092-11eb-8b20-f9263c5c01ad.png)

各种文章和生态周边项目的链接
https://github.com/Tencent/APIJSON#%E7%9B%B8%E5%85%B3%E6%8E%A8%E8%8D%90
![image](https://user-images.githubusercontent.com/5738175/105938750-ce71fa80-6092-11eb-8055-c063828f1330.png)

**Comment by TommyLemon** [comment]
不宣传怎么吸引用户？绝不部分人都懒得看文档/源码

**Comment by maple5233** [comment]
底气就是真的很混乱，调研代码仓库的依据难道是看star的人是谁吗？

**Comment by papachong** [comment]
作者以前是学生会的吗？仅好奇。

**Comment by saosir** [comment]
@wenj91 他急了，你不配参与这个项目

**Comment by qiyeboy** [comment]
问题关了吧，没想到在github看到了喷子，自己啥都没付出，指责别人这不对，那不对，你有好的想法创意，提pull呀

**Comment by cyf333333** [comment]
> 问题关了吧，没想到在github看到了喷子，自己啥都没付出，指责别人这不对，那不对，你有好的想法创意，提pull呀

我买冰箱的时候评价冰箱好不好，还要自己参与了冰箱的流水线才可以？冰箱买回来不好用，我还得自己会制冷才能评价？

**Comment by qiyeboy** [comment]
@cyf333333 你知道为啥淘宝需要购买完东西才能给评价吗？为了防止没有价值的评价。你知道 没有深入了解过动心，没有事实根据就评价，是多么让人讨厌的事情吗？没说不让你评价，但是没有事实根据，只会让人讨厌罢了。

**Comment by qiyeboy** [comment]
这个项目假如确实有问题，比如你觉得文档少，看不懂，那你就实事求是的提，然后问问作者是不是很忙，需不需要帮助，可以一块协作，都挺暖的。上来就指责，还没说明原因，你对你刚认识的人就这样态度 ？？？

**Comment by pskun** [comment]
> 感觉项目立意理念挺好的，为什么搞得一团糟的感觉，readme完全就是在吹嘘

大胸弟，被这满屏的头像吓到了吗

**Comment by metroluffy** [comment]
> > 感觉项目立意理念挺好的，为什么搞得一团糟的感觉，readme完全就是在吹嘘
> 
> 大胸弟，被这满屏的头像吓到了吗

三屏翻不到头🤪🤪，太疯狂了

**Comment by mocceli** [comment]
急了？
