### ISSUE TITLE
使用自增id项目第一次启动时，自增id配置不生效导致插入失败

### ISSUE THREAD

**Issue by junlin-2019** [Tencent/APIJSON#199]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

在项目启动后第一次被访问时DemoSQLConfig类晚于APIJSONSQLConfig初始化，导致第一次插入的时候在DemoSQLConfig中SIMPLE_CALLBACK中配置自增id不生效，

**错误信息**
Error updating database.  Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Out of range value for column 'id' at row 1

**Comment by TommyLemon** [comment]
断点调试，然后把关键信息截屏发下
