### ISSUE TITLE
是否有纯净的初始化SQL

### ISSUE THREAD

**Issue by everything8** [Tencent/APIJSON#200]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

demo中，sql脚本包含一系列表，以及测试数据，有些表是不需要的。不清楚哪些表是必须的，有没有一份可以用于生产环境的，干净的sql脚本，仅包含必须的表？

**Comment by TommyLemon** [comment]
右侧数据字典对配置表有注释(必须)
http://apijson.cn/api/
