### ISSUE TITLE
对于稍微复杂的业务处理APIJSON可以如何在后端框架中使用？

### ISSUE THREAD

**Issue by Fnckerpoi** [Tencent/APIJSON#201]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**
业务情景：前端访问接口传入一个ID，后端需要根据ID查询多张表获取较多数据进行业务计算处理，并对表的数据更新，最后并返回结果。
APIJSON可以解决后端接口返回的时候后端业务处理时的冗余字段（这些冗余字段不需要返回给前端，前端也不需要下一个接口传回给后端）。这里就我有一个疑惑，就是前端通过访问直接从DB自动联查数据后，中途后端需要先完成一系列的业务处理的这种情况该如何解决？一个业务的处理时较为复杂，例如一个查询详情，前端传入单据ID，后端并不是仅需要查出单据主表信息和详情信息，还需要对一些字段的可编辑修改范围值计算处理，像这样的业务处理APIJSON是否适用呢？

**错误信息**

**Comment by TommyLemon** [comment]
常见问题
1.如何定制业务逻辑？
在后端编写 远程函数，可以拿到 session、version、当前 JSON 对象、参数名称 等，然后对查到的数据自定义处理
https://github.com/Tencent/APIJSON/issues/36

**Comment by Fnckerpoi** [comment]
好的谢谢，能再请问一个问题么？就是现在我的项目已经有在使用自己的框架，是在业务开发的一定阶段的时候遇到瓶颈，APIJOSN能够兼容的接入框架么？我看介绍APISJON是另外自己的一套独立框架，那是否意味着要想使用APIJSON就得将业务搬到APIJSON的框架下重新搞？

**Comment by TommyLemon** [comment]
兼容各种项目 (对各类 Web 框架集成友好且提供 SpringBoot, JFinal 的 Demo，协议不限 HTTP，与其它库无冲突)

先把首页文档看完吧
https://github.com/Tencent/APIJSON
![image](https://user-images.githubusercontent.com/5738175/108816422-20099880-75f1-11eb-9fa8-8fa3ef420db3.png)

**Comment by Fnckerpoi** [comment]
好的，非常感谢，因为我看了部分文档包括交流视频，第一时间把APIJSON和我当前的项目如何融合没有一个清晰的了解，所有来直接请教一下看能不能有明确的指向解答

**Comment by TommyLemon** [comment]
参考 Demo，由易到难，从最简单的 Demo 开始入手，按照 【官方上手文档】 一步步来
https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server
