### ISSUE TITLE
是否可以将apijson的数据库跟业务数据库分开

### ISSUE THREAD

**Issue by everything8** [Tencent/APIJSON#202]
**具体说下**
希望可以将apijson的数据库与业务数据库的连接信息分开配置

**为什么**
现在数据库连接只能配置一个，因此，apijson的表就会跟业务表耦合在一个数据库下。apijson自带17张表，再加上业务的一些表，看起来会十分雍容，而且也会影响数据库的客户性和可维护性

**Comment by TommyLemon** [comment]
只有少数几张表必须
https://github.com/Tencent/APIJSON/issues/200

可以在 DemoSQLConfig 重写方法 getConfigSchema 等来隔离 APIJSON 配置表和你的业务表
https://github.com/APIJSON/apijson-framework/blob/master/src/main/java/apijson/framework/APIJSONSQLConfig.java
![image](https://user-images.githubusercontent.com/5738175/108823583-97dcc080-75fb-11eb-8373-fe120b402076.png)
