### ISSUE TITLE
使用count(*)字段时，返回json结构的key不符合预期

### ISSUE THREAD

**Issue by zhipeng-zhao** [Tencent/APIJSON#204]
系统： ubuntu 18.x
平台： Chrome 87

如图，使用count(*)作为查询字段，返回的json中count(*)的key变成了 count('*') 多了一个引号。
预期应该是count(*)跟字段保持一致
![image](https://user-images.githubusercontent.com/73329517/108981272-895bdb00-76c7-11eb-99b5-850c7317f5bb.png)

**Comment by TommyLemon** [comment]
* 等不符合 单词、数字 格式的字符会被当成普通字符强制加引号防止 SQL 注入，改为 count(0), count(1), count(id) 都行

**Comment by zhipeng-zhao** [comment]
@TommyLemon 已经解决，感谢
