### ISSUE TITLE
跟GraphQL的区别是什么？

### ISSUE THREAD

**Issue by yuenushan** [Tencent/APIJSON#205]
跟GraphQL的区别是什么？支持的功能有什么不一样？能出个对比吗？

**Comment by TommyLemon** [comment]
APIJSON 在 功能、安全、性能、易用性、Java 版生态(继承 JSON 的相关生态) 等都大幅领先 GraphQL
https://github.com/Tencent/APIJSON/issues/2

![image](https://user-images.githubusercontent.com/5738175/104417275-103d7400-55b0-11eb-8ad8-737867d92456.png)
