### ISSUE TITLE
支持golang吗？

### ISSUE THREAD

**Issue by B1anker** [Tencent/APIJSON#206]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

**错误信息**

**Comment by TommyLemon** [comment]
协议不限任何语言，只是现在还没有一个能用的 Golang 版实现，期待热心的开发者实现一个
https://github.com/Tencent/APIJSON/issues/38

**Comment by TommyLemon** [comment]
可以点 Star 支持下作者
https://gitee.com/tiangao/apijson-go

**Comment by TommyLemon** [comment]
@B1anker 
零代码接口和文档 apijson-go 开源，腾讯 APIJSON 的 Golang 版实现
https://github.com/Tencent/APIJSON/issues/520

**Comment by B1anker** [comment]
> 

nice
