### ISSUE TITLE
有没有可能上传 MAVEN 中央仓库

### ISSUE THREAD

**Issue by zhengbinger** [Tencent/APIJSON#207]
有没有可能上传 MAVEN 中央仓库

**Comment by zhengbinger** [comment]
maven 中央仓库可否进行版本更新

**Comment by TommyLemon** [comment]
APIJSONORM 和 apijson-framework 都支持 Maven, Gradle 远程依赖，都有版本管理
https://github.com/Tencent/APIJSON/tree/master/APIJSONORM
https://github.com/APIJSON/apijson-framework

**Comment by zhengbinger** [comment]
好的，感谢回复
