### ISSUE TITLE
咨询个问题：apijson如何支持数据库连接池？多谢啦。（看源码都是直接使用jdbc）

### ISSUE THREAD

**Issue by healthybaobao** [Tencent/APIJSON#210]
apijson对多用户压力场景如何支持？我理解，一旦并发的请求多了会导致后端数据库测连接被占用完，特此请教您，咋们apijson目前对于高并发场景下是如何支持？非常感谢。

**Comment by TommyLemon** [comment]
https://github.com/Tencent/APIJSON/issues/153

**Comment by healthybaobao** [comment]
非常感谢。另外，咨询一下，apijson后续有没有计划支持“创建数据库，自定义字段”这样的特性？多谢您啦。

**Comment by TommyLemon** [comment]
不会支持创建数据库、改表结构这种危险的功能，建议用 MySQLWorkbench, DataGrip, Navicat 等数据库工具。
不过已经提供了 https://github.com/APIJSON/apijson-column 来支持 字段名映射 和 !key 反选字段。

**Comment by TommyLemon** [comment]
新增 连接池及多数据源 Demo（Druid + HikariCP）
https://gitee.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server
