### ISSUE TITLE
实体类属性与表字段不一致问题！

### ISSUE THREAD

**Issue by cslgithub** [Tencent/APIJSON#211]
**环境信息**
 - 系统:  Windows 10
 - JDK:  1.8.0_17 
 - 数据库:  MySQL 5.7.14
 - APIJSON:  4.6.1

**问题描述**

新增一个model类ClassInfo，对应数据库表tb_class,ClassInfo类的属性字段**classNo**与表TB_CLASS里的表字段**class_no**不一致，在进行post 新增的时候，传的参数是ClassNo的话，会报错，提示Unknown column 'classNo' in 'field list'，如图：

![err](https://user-images.githubusercontent.com/16893343/112927256-4cac5500-9147-11eb-98eb-d7d02a481cd0.jpg)
如果换成class_no 即可，如何处理以实体model属性为参数传递？
**错误信息**
`"ok": false,
    "code": 500,
    "msg": "Unknown column 'classNo' in 'field list'",
    "sql:generate|cache|execute|maxExecute": "1|0|1|200",
    "depth:count|max": "1|5",
    "time:start|duration|end": "1617072883132|14|1617072883146",
    "throw": "java.sql.SQLSyntaxErrorException",`

**Comment by TommyLemon** [comment]
不需要写实体类，和实体类的字段完全无关，ORM 内部全程通过 JSONObject 传数据，不用 JavaBean

**Comment by cslgithub** [comment]
> 不需要写实体类，和实体类的字段完全无关，ORM 内部全程通过 JSONObject 传数据，不用 JavaBean

不用javaBean封装业务模型的话，那请求参数怎么传？请求参数是否必须和业务表字段保持一致？这点儿还是不太明白

**Comment by TommyLemon** [comment]
前端传，默认必须和数据库表字段一致。需要不一致就自己在 DemoSQLConfig 重写 getKey 做映射

**Comment by TommyLemon** [comment]
APIJSON 字段插件，支持字段映射
https://github.com/APIJSON/apijson-column/
