### ISSUE TITLE
response过滤数据不成功

### ISSUE THREAD

**Issue by JerryWwang** [Tencent/APIJSON#214]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

response表中的数据看起来是可以控制返回数据，但是使用不生效，也没有找到对应的文档介绍
如将user的structure改为{"put": {"extra": "Response works! "}, "remove": "head"}
重启服务依旧返回了head字段，也没有添加extra字段
![image](https://user-images.githubusercontent.com/82087906/113842294-1ca72680-97c5-11eb-82fd-726d85457144.png)
![image](https://user-images.githubusercontent.com/82087906/113842390-35174100-97c5-11eb-9bef-27b159c2ec97.png)

**Comment by TommyLemon** [comment]
https://github.com/Tencent/APIJSON
![image](https://user-images.githubusercontent.com/5738175/113845398-0e0e3e80-97c8-11eb-9b44-66d45c8c3e28.png)

**Comment by JerryWwang** [comment]
文档中没有response表的用法

**Comment by TommyLemon** [comment]
对 Response 的校验配置，几年前刚实现没几天就取消支持了，也从来没写过对应的文档。
https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractParser.java
![image](https://user-images.githubusercontent.com/5738175/113878576-4de71d00-97ec-11eb-87c1-e0031301a26c.png)

可以用远程函数来做
https://github.com/Tencent/APIJSON/issues/101
