### ISSUE TITLE
apijson的性能如何？有比较权威的数据吗？

### ISSUE THREAD

**Issue by zhukj** [Tencent/APIJSON#231]

**Comment by TommyLemon** [comment]
https://github.com/Tencent/APIJSON/releases/tag/4.6.0
![image](https://user-images.githubusercontent.com/5738175/118244878-a2a84280-b4d2-11eb-963e-30f0df3e7924.png)

**Comment by TommyLemon** [comment]
腾讯业务百万数据 6s 响应，APIJSON 性能优化背后的故事
https://zhuanlan.zhihu.com/p/447844661
