### ISSUE TITLE
1.已经有了登录，如何和apijson集成2、已有权限校验的框架如何和apijson集成3、已有角色如何和apijson集成

### ISSUE THREAD

**Issue by xuedie12369** [Tencent/APIJSON#242]
1.已经有了登录，如何和apijson集成2、已有权限校验的框架如何和apijson集成3、已有角色如何和apijson集成。
希望能够提供示例代码

**Comment by TommyLemon** [comment]
13.自己已经有一套鉴权系统了，不想用 APIJSON 的这套怎么办？

15.如何集成到自己现有的项目？

https://github.com/Tencent/APIJSON/issues/36
