### ISSUE TITLE
apijson分页限制无法解除

### ISSUE THREAD

**Issue by 997959066** [Tencent/APIJSON#243]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**
分页限制无法解除

![image](https://user-images.githubusercontent.com/40293676/119956285-837dda80-bfd3-11eb-90e6-312e7ccd26c1.png)

**错误信息**
根据文档"query": 2 并未查出全部

**Comment by 997959066** [comment]
扩展 taos和 clikehouse 都是一样的效果。

**Comment by TommyLemon** [comment]
必须分页，不分页在数据量大的时候容易拖垮数据库。
可以在 DemoParser 重写 getMaxQueryCount，给一个比较大的值。

"query": 2 不是指查全部数据，是指同时查 0.数据 和 1.数量 以上全部。
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2
![image](https://user-images.githubusercontent.com/5738175/120134073-f2d81200-c1ff-11eb-89b7-85f60d260652.png)

另外对接 taos 和 clikehouse 的 Demo 可以开源下吗？帮助其它用户使用，开源需要大家一起贡献才会更美好~

**Comment by 997959066** [comment]
> 必须分页，不分页在数据量大的时候容易拖垮数据库。
> 可以在 DemoParser 重写 getMaxQueryCount，给一个比较大的值。
> 前端传字段 count 来指定每页数量。
> 
> "query": 2 不是指查全部数据，是指同时查 0.数据 和 1.数量 以上全部。
> https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2
> ![image](https://user-images.githubusercontent.com/5738175/120134073-f2d81200-c1ff-11eb-89b7-85f60d260652.png)
> 
> 另外对接 taos 和 clikehouse 的 Demo 可以开源下吗？帮助其它用户使用，开源需要大家一起贡献才会更美好~
