### ISSUE TITLE
请问会不会支持kotlin呢？

### ISSUE THREAD

**Issue by FrankyLee-dev** [Tencent/APIJSON#247]

**Comment by TommyLemon** [comment]
这是说 后端 还是 客户端 ？
客户端当然支持
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Android/APIJSONApp/app/src/main/java/apijson/demo/client/util/TestRequestAndResponse.kt

几乎所有通用语言都支持 HTTP API，这里有多种语言的 Demo
https://github.com/APIJSON/APIJSON-Demo

至于后端，Kotlin 可以调用 Java 库，也没问题

**Comment by FrankyLee-dev** [comment]
好的
