### ISSUE TITLE
不等于 null 并且 不等于 '' 查询条件怎么写（name is not null and name <>''）

### ISSUE THREAD

**Issue by daichangya** [Tencent/APIJSON#254]
不等于 null 并且 不等于 '' 查询条件怎么写
sql 是这样的（name is not null and name <>''）
不知道apijson 怎么写

**Comment by TommyLemon** [comment]
"name{}": "!=null",
"name!": ""

**Comment by daichangya** [comment]
谢谢

**Comment by transtone** [comment]
> AND 连接： "name{}": "!=null", "name!": ""
> 
> OR 连接： "name{}": "!=null", "name!": "" "@combine": "name{},name!"
> 
> NOT 连接： "name{}": "!=null", "name!": "" "@combine": "!name{},!name!"
> 
> 见通用文档 #功能符 https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2

@TommyLemon 

OR 连接：
```
"name{}": "=null",
"name": ""
"@combine": "name{},name"
```
这样写会报错：
`@combine:value 中的value里 'name' 对应的条件 'name':value 中 value 不能为 null！`
