### ISSUE TITLE
官网分组demo报错

### ISSUE THREAD

**Issue by 2720851545** [Tencent/APIJSON#257]
**环境信息**
 - 系统: Mac 10.15.7
 - JDK: 16.0.1.hs-adpt
 - 数据库: MySQL 8.0.23
 - APIJSON: 4.7.0

**问题描述**

![image](https://user-images.githubusercontent.com/28623614/123380268-d2626400-d5c1-11eb-8295-b0ba989a83db.png)

使用官网分组demo报错, 在查询列带入分组列报错, 虽然这列信息可以从传入请求的数据获取, 提个issue看是bug还是文档问题, 谢谢

**错误信息**

![image](https://user-images.githubusercontent.com/28623614/123380866-8ebc2a00-d5c2-11eb-8bdb-29dc20023dcf.png)

![image](https://user-images.githubusercontent.com/28623614/123380341-e7d78e00-d5c1-11eb-9b89-0b2fbe6b4161.png)

**Comment by TommyLemon** [comment]
以通用文档为准
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2

**Comment by 2720851545** [comment]
哦, thanks
