### ISSUE TITLE
如何去除数组查询中的 limit 10 ？

### ISSUE THREAD

**Issue by soldiergit** [Tencent/APIJSON#259]
**环境信息**
 - 系统: Windows 10
 - JDK: 1.8.0_17
 - 数据库: MySQL 5.7.24
 - APIJSON:  

**问题描述**

![image](https://user-images.githubusercontent.com/43507354/123571359-a0891180-d7fc-11eb-9750-dac6076f1d39.png)

已生成 1 条 SQL sql = 
SELECT `id` FROM `sys`.`Moment` LIMIT 10

`想查询数据表中的全部数据 而不限制大小`

**错误信息**

**Comment by TommyLemon** [comment]
提问前必看 常见问题 18
https://github.com/Tencent/APIJSON/issues/36
