### ISSUE TITLE
支持mysql全文检索吗

### ISSUE THREAD

**Issue by MaDaMaDaMaDa** [Tencent/APIJSON#265]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**
如题: 支持mysql全文检索吗?

**错误信息**

**Comment by MaDaMaDaMaDa** [comment]
有的话能否给个实现例子, 文档里都没有啊

**Comment by TommyLemon** [comment]
可以看下这个是否满足你的搜索需求
https://github.com/chenyanlann/APIJSONDemo_ClickHouse

Elasticsearch 和 Clickhouse 基本查询对比
https://zhuanlan.zhihu.com/p/353296392

**Comment by MaDaMaDaMaDa** [comment]
感谢

**Comment by TommyLemon** [comment]
试试这个，应该支持 MySQL 全文检索的表达式了
https://github.com/qiujunlin/APIJSON

**Comment by TommyLemon** [comment]
4.8.3-4.9.1 可以在 @column 中用，5.0+ 可以在  @having 和 id{}:"SQL 片段" 中用 MySQL 全文检索了
https://github.com/Tencent/APIJSON/releases/tag/5.0.0
![image](https://user-images.githubusercontent.com/5738175/161416589-d066c783-f98a-4f37-aa5d-79061e5aa5d3.png)
