### ISSUE TITLE
你这个开始文档写的简直一塌糊涂

### ISSUE THREAD

**Issue by orchief** [Tencent/APIJSON#271]
请减少功能介绍 给一个最小 最快的能运行起来的demo代码 说了一大堆牛逼之处结果改配置还得找源码改 你这不是来搞笑呢

**Comment by orchief** [comment]
![image](https://user-images.githubusercontent.com/33409040/125943957-4643855f-0c2e-438e-b79e-2191e2301dff.png)
一堆改成你自己的  你就这么懒 不能放到配置文件里边?

**Comment by TommyLemon** [comment]
用 APIJSONBoot-MultiDataSource 或 APIJSONDemo-Druid 或 APIJSONDemo-HikariCP
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONBoot-MultiDataSource/src/main/resources/application.yml

**Comment by TommyLemon** [comment]
首先 APIJSON 的文档不管是从数量还是质量上都起码在国内 1W+ Star 的各大免费开源项目中都已经是较好的了，花了大量时间精力，连标点符号、空格、换行都一丝不苟。
https://github.com/Tencent/APIJSON/commit/d2c47d482f6112564226d979b7a72e9f66592d34
https://github.com/Tencent/APIJSON/commit/9b82b5ed4768bd9bb30029ec44c5803968c458eb
https://github.com/Tencent/APIJSON/commit/05917c19d4479a8dcea10980fdbc513708757729

多个大学生都能快速上手做出生态项目及视频教程
https://github.com/Tencent/APIJSON#%E8%85%BE%E8%AE%AF%E7%8A%80%E7%89%9B%E9%B8%9F%E5%BC%80%E6%BA%90%E4%BA%BA%E6%89%8D%E5%9F%B9%E5%85%BB%E8%AE%A1%E5%88%92

![image](https://user-images.githubusercontent.com/5738175/134530772-69f00da9-be91-463b-92f5-8c75d708472a.png)

<br /><br /><br />


1、民事诉讼法第64条规定，当事人对自己提出的主张，有责任提供证据。
https://splcgk.court.gov.cn/gzfwww/sszn/details?id=ff808081739db03e01749acfb22505e7

开源本来就是众人拾柴火焰高，你不贡献就想着白嫖就算了，还要在社区 无礼漫骂破坏氛围，哪里来的底气？欠你什么了吗？
