### ISSUE TITLE
多表关联查询不同字段如何模糊查询

### ISSUE THREAD

**Issue by han-1023** [Tencent/APIJSON#274]
"[]": {
        "Organization": {
            "@column": "id,name,categoryCodeList,createTime,remarks,status,principleId",
        },
        "User": {
            "@column": "id,realName,mobile;count(organization_id):userCount",
            "id@": "/Organization/principleId",
        }
    }
像这样的关联查询我想对User表里的realName进行模糊查询，请问realName$该写在哪里呢，如果要是对两张表的字段多条件模糊查询“@combine”该写在主表还是副表呢

**Comment by TommyLemon** [comment]
字段的条件只能写在字段所在对象。

多表关联查询，当需要条件组合的字段在不同表中，要先 JOIN 得到一个临时表

![image](https://user-images.githubusercontent.com/5738175/126519510-41ccb269-bfcf-486c-b25b-ed913c533f4e.png)

{
    "[]": {
        "Comment": {
            "name$": "%a%",
            "content$": "%a%",
            "@combine": "name$,content$",  // 临时表内条件组合
            "@from@": {  // JOIN 得到一个临时表
                "from": "Comment",
                "join": "&/User/id@",
                "Comment": {},
                "User": {
                    "id@": "/Comment/userId",
                    "@column": "name,sex"
                }
            }
        }
    }
}

**Comment by han-1023** [comment]
{
    //  "@explain": true,
    "[]": {
        
        "Organization": {
            "name$":"%%",
            "mobile$":"%%",
            "categoryCodeList$":"%%",
            "real_name$":"%%",
            "@combine":"name$,mobile$,real_name$,categoryCodeList$",
            "@order":"status-,createTime-",
            "@from@": { 
                "from": "Organization",
                "join": "&/User/id@",
                "Organization": {
                    "@column":"name,categoryCodeList,status,createTime",
                    "@group":"id"
                },
                "User": {
                    "delete":1,
                    "@column":"realName,mobile;count(organization_id):userCount",
                    "id@": "/Organization/principle_id"
                }
            }
        }
    }
}

为什么我在临时表中添加了模糊查询就查不到任何数据呢

**Comment by TommyLemon** [comment]
带上 "@explain": true, 把整个请求完整截屏发出来。初步判断是 count(organization_id) 导致的问题，聚合函数必然是要分组的，分组后每组最多查出该组一条记录，应该单独查询

**Comment by han-1023** [comment]
{
     "@explain": true,
    "[]": {
        
        "Organization": {
            "name$":"%%",
            "mobile$":"%%",
            "categoryCodeList$":"%%",
            "real_name$":"%%",
            "@combine":"name$,mobile$,real_name$,categoryCodeList$",
            "@order":"status-,createTime-",
            "@from@": { 
                "from": "Organization",
                "join": "&/User/id@",
                "Organization": {
                    "@column":"name,categoryCodeList,status,createTime",
                    "@group":"id"
                },
                "User": {
                    "delete":1,
                    "@column":"realName,mobile",
                    "id@": "/Organization/principle_id"
                }
            }
        }
    }
}

返回信息如下，sql命令也没啥问题但跟了一个list回来  并不是我要的数据
{
    "[]": [
        {
            "Organization": {
                "@explain": {
                    "sql": "SELECT * FROM (SELECT `Organization`.`name`,`Organization`.`category_code_list`,`Organization`.`status`,`Organization`.`create_time`, `User`.`real_name`,`User`.`mobile` FROM `xyerp`.`t_organization` AS `Organization`  \n   INNER JOIN `xyerp`.`t_user` AS `User` ON `User`.`id` = `Organization`.`principle_id` WHERE  (  (  (  (`User`.`delete` = 1)  )  )  )  GROUP BY `Organization`.`id`)  AS `Organization`  WHERE  (  (`name` LIKE '%%') OR (`mobile` LIKE '%%') OR (`real_name` LIKE '%%') OR (`category_code_list` LIKE '%%')  )  ORDER BY `status` DESC ,`create_time` DESC  LIMIT 10",
                    "list": [
                        {
                            "id": 1,
                            "select_type": "PRIMARY",
                            "table": "<derived2>",
                            "type": "ALL",
                            "rows": 2,
                            "filtered": 93.75,
                            "Extra": "Using where; Using filesort"
                        },
                        {
                            "id": 2,
                            "select_type": "DERIVED",
                            "table": "User",
                            "type": "ALL",
                            "possible_keys": "PRIMARY",
                            "rows": 10,
                            "filtered": 10.0,
                            "Extra": "Using where; Using temporary; Using filesort"
                        },
                        {
                            "id": 2,
                            "select_type": "DERIVED",
                            "table": "Organization",
                            "type": "ALL",
                            "possible_keys": "PRIMARY,t_organization_name_uindex",
                            "rows": 4,
                            "filtered": 25.0,
                            "Extra": "Using where; Using join buffer (Block Nested Loop)"
                        }
                    ]
                }
            }
        }
    ],
    "ok": true,
    "code": 200,
    "msg": "success",
    "sql:generate|cache|execute|maxExecute": "1|0|1|200",
    "depth:count|max": "5|5",
    "time:start|duration|end": "1626944384404|38|1626944384442"
}

然后把聚合函数与模糊查询注释掉
{
     "@explain": true,
    "[]": {
        
        "Organization": {
            // "name$":"%%",
            // "mobile$":"%%",
            // "categoryCodeList$":"%%",
            // "real_name$":"%%",
            // "@combine":"name$,mobile$,real_name$,categoryCodeList$",
            "@order":"status-,createTime-",
            "@from@": { 
                "from": "Organization",
                "join": "&/User/id@",
                "Organization": {
                    "@column":"name,categoryCodeList,status,createTime",
                    "@group":"id"
                },
                "User": {
                    "delete":1,
                    "@column":"realName,mobile",
                    "id@": "/Organization/principle_id"
                }
            }
        }
    }
}

成功返回数据：
{
    "[]": [
        {
            "Organization": {
                "@explain": {
                    "sql": "SELECT * FROM (SELECT `Organization`.`name`,`Organization`.`category_code_list`,`Organization`.`status`,`Organization`.`create_time`, `User`.`real_name`,`User`.`mobile` FROM `xyerp`.`t_organization` AS `Organization`  \n   INNER JOIN `xyerp`.`t_user` AS `User` ON `User`.`id` = `Organization`.`principle_id` WHERE  (  (  (  (`User`.`delete` = 1)  )  )  )  GROUP BY `Organization`.`id`)  AS `Organization`  ORDER BY `status` DESC ,`create_time` DESC  LIMIT 10",
                    "list": [
                        {
                            "id": 1,
                            "select_type": "PRIMARY",
                            "table": "<derived2>",
                            "type": "ALL",
                            "rows": 2,
                            "filtered": 100.0,
                            "Extra": "Using filesort"
                        },
                        {
                            "id": 2,
                            "select_type": "DERIVED",
                            "table": "User",
                            "type": "ALL",
                            "possible_keys": "PRIMARY",
                            "rows": 10,
                            "filtered": 10.0,
                            "Extra": "Using where; Using temporary; Using filesort"
                        },
                        {
                            "id": 2,
                            "select_type": "DERIVED",
                            "table": "Organization",
                            "type": "ALL",
                            "possible_keys": "PRIMARY,t_organization_name_uindex",
                            "rows": 4,
                            "filtered": 25.0,
                            "Extra": "Using where; Using join buffer (Block Nested Loop)"
                        }
                    ]
                },
                "name": "1231231231451",
                "categoryCodeList": "0102,03,02,01",
                "status": "1",
                "createTime": "2021-07-21 03:27:47.0",
                "real_name": "敌人节",
                "mobile": "19818528888"
            }
        },
        {
            "Organization": {
                "name": "1231231",
                "categoryCodeList": "03,0102",
                "status": "1",
                "createTime": "2021-07-21 03:20:13.0",
                "real_name": "大风冠",
                "mobile": "234234"
            }
        },
        {
            "Organization": {
                "name": "测试部门4号",
                "categoryCodeList": "01",
                "status": "1",
                "createTime": "2021-07-06 10:27:19.0",
                "real_name": "电风扇",
                "mobile": "2334223"
            }
        },
        {
            "Organization": {
                "name": "测试部门1",
                "categoryCodeList": "01",
                "status": "1",
                "createTime": "2021-06-24 20:53:13.0",
                "real_name": "胡图图",
                "mobile": "766666666"
            }
        }
    ],
    "ok": true,
    "code": 200,
    "msg": "success",
    "sql:generate|cache|execute|maxExecute": "1|0|1|200",
    "depth:count|max": "5|5",
    "time:start|duration|end": "1626944504474|37|1626944504511"
}
我在APIAUTO上测试过  并没有出现这样的问题
实在不好意思耽误您时间了
