### ISSUE TITLE
[bug] 远程函数调用拿不到请求体中数据

### ISSUE THREAD

**Issue by jerrylususu** [Tencent/APIJSON#281]
**环境信息**
 - 系统: Windows 10
 - JDK: 13
 - 数据库: MySQL 5.7
 - APIJSON:  4.7.0

**问题描述**

使用 APIJSONBoot 示例项目，在 POST Moment 时，`pictureList` 输入错误的 URL 列表，请求依然成功。但是根据 Request 表中相关行，`pictureList` 应该会被远程函数 `verifyURLList` 进行验证。在 `verifyURLList` 函数下断点，发现调用时 `current` 为一个空 `JSONObject`，即请求体没有被正确传入。

**错误信息**

请求与响应
![image](https://user-images.githubusercontent.com/17522475/127711548-ac7e9bf6-a798-4317-8ae2-2ac114a2927d.png)

断点截图
![image](https://user-images.githubusercontent.com/17522475/127711532-453ca2cb-0c5a-4608-8128-7f6a3d9c47ee.png)

原始请求体
```json
{
 "Moment":{
      "content":"今天天气不错，到处都是提拉米苏雪",
      "userId":1627466921423,
      "pictureList": ["111:/222"]
 },
  "tag":"Moment"
}
```

**Comment by jerrylususu** [comment]
另外顺便询问下，在 POST/PUT 中如果远程函数返回 null，是否远程函数的 key 就不会出现在最后的 SQL 中？我在尝试实现一个比较复杂的鉴权逻辑，需要在 POST/PUT 的时候调用远程函数完成鉴权，现在是如果鉴权成功返回 null，鉴权失败就抛异常，这样实现是否符合 APIJSON 的要求？

**Comment by TommyLemon** [comment]
确实有这个 bug，应该是最近的版本新出现的，感谢反馈。

**Comment by TommyLemon** [comment]
> 另外顺便询问下，在 POST/PUT 中如果远程函数返回 null，是否远程函数的 key 就不会出现在最后的 SQL 中？我在尝试实现一个比较复杂的鉴权逻辑，需要在 POST/PUT 的时候调用远程函数完成鉴权，现在是如果鉴权成功返回 null，鉴权失败就抛异常，这样实现是否符合 APIJSON 的要求？

不管返回什么都不会用于生成 SQL 。这个鉴权方式可以

**Comment by TommyLemon** [comment]
![image](https://user-images.githubusercontent.com/5738175/127746852-01d42607-3ca3-4dae-aedd-0b589f6d6ad6.png)

优化性能的版本改出了 bug，AbstractObjectParser.onFunctionResponse 这里需要回滚下
```java
			//			JSONObject json = "-".equals(type) ? request : response; // key-():function 是实时执行，而不是在这里批量执行

			for (Entry<String, String> entry : functionSet) {

				//				parseFunction(json, entry.getKey(), entry.getValue());
				parseFunction(entry.getKey(), entry.getValue(), parentPath, name, response);
			}
```
改为
```java
                        JSONObject json = "-".equals(type) ? request : response; 

			for (Entry<String, String> entry : functionSet) {
				parseFunction(entry.getKey(), entry.getValue(), parentPath, name, json);
			}
```

https://github.com/Tencent/APIJSON/blob/4f4a197a65f90b648ed84ca6e9e8df5d53130c0a/APIJSONORM/src/main/java/apijson/orm/AbstractObjectParser.java

**Comment by TommyLemon** [comment]
已解决
https://github.com/Tencent/APIJSON/commit/3ccd9674ce572e36907dd961ae9386e31abc2483

**Comment by TommyLemon** [comment]
4.7.2 发布
https://github.com/APIJSON/APIJSON-Demo/releases/tag/4.7.2

**Comment by jerrylususu** [comment]
4.7.2 验证已解决。感谢帮助！
