### ISSUE TITLE
如何逻辑删除

### ISSUE THREAD

**Issue by bullhe4d** [Tencent/APIJSON#301]
在Roadmap里看到支持逻辑删除？但是并没看到相关代码？想知道4.7.2版本下支持逻辑删除么？应该怎么做？

**Comment by TommyLemon** [comment]
用 /put，把 is_deleted 改为 1

**Comment by bullhe4d** [comment]
谢谢回复，在需要查询未删除数据的时候应该把判断（ is_deleted != 1）加在哪里呢？

**Comment by TommyLemon** [comment]
直接在请求 JSON 表对象里加，或者在 DemoObjectParser 重写 newSQLConfig，RequestMethod.isQueryMethod(method, true) 时固定把 is_deleted, 0 加进去
