### ISSUE TITLE
POST操作，后端调用云函数进行字段赋值出现问题

### ISSUE THREAD

**Issue by ikay666** [Tencent/APIJSON#302]
POST操作，后端调用云函数赋值出现以下问题，没有找到相关文档，
按照 #196  issues进行的操作

![image](https://user-images.githubusercontent.com/43111379/129514142-65b861fe-8cb7-477f-a156-5c3bc17ec0e7.png)

**Comment by ikay666** [comment]
![image](https://user-images.githubusercontent.com/43111379/129547712-d644ab8a-aa4e-4cb7-a137-2a28818f87c0.png)
![image](https://user-images.githubusercontent.com/43111379/129547735-6cbeda02-b68f-4275-af3e-6566d468df28.png)
![image](https://user-images.githubusercontent.com/43111379/129547862-61db770f-2281-4b93-ad83-2f98f34666cb.png)

我是按图上这样配置的，是否有问题

**Comment by TommyLemon** [comment]
看不出问题，重启服务或调 /reload 重载配置后试试

**Comment by TommyLemon** [comment]
同类问题
https://github.com/Tencent/APIJSON/issues/320
