### ISSUE TITLE
文档太烂!

### ISSUE THREAD

**Issue by toplinuxsir** [Tencent/APIJSON#314]
国内开源项目高质量的没有几个，文档太差了， 一入群,上来就要github的关注，沽名钓誉而已!

**Comment by TommyLemon** [comment]
“一入群,上来就要github的关注，沽名钓誉” ，关于这几点请给证据谢谢，APIJSON 所有官方群没有一次公告是要求为 APIJSON 主项目（注意是主项目，不是其它作者写的生态项目）要关注。

1、民事诉讼法第64条规定，当事人对自己提出的主张，有责任提供证据。
https://splcgk.court.gov.cn/gzfwww/sszn/details?id=ff808081739db03e01749acfb22505e7
