### ISSUE TITLE
希望可以支持替换特殊字符

### ISSUE THREAD

**Issue by fanpocha** [Tencent/APIJSON#317]
**具体说下**
查询列表的“[]”，希望可以自定义符号，比如用“$list”

**为什么**
由于部分组件不支持这个格式

**Comment by TommyLemon** [comment]
建议用 format: true
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2

不建议改 JSONRequest.KEY_ARRAY = "$list"

**Comment by fanpocha** [comment]
通过改源码方式修改确实不太友好，建议可以做一个配置对应。我已经通过修改前端请求解决了这个问题
