### ISSUE TITLE
希望可以新增加菜单树返回格式

### ISSUE THREAD

**Issue by fanpocha** [Tencent/APIJSON#318]
**具体说下**
希望可以新增加菜单树返回格式

**为什么**
菜单展示的功能场景比较多，希望可以支持这种返回格式

**Comment by TommyLemon** [comment]
有限层级可以直接在前端传参实现，无限层级需要 后端/前端 写代码处理

**Comment by fanpocha** [comment]
文档中未找到如何传参
我现在有这样一张菜单表：
CREATE TABLE `menu` (
  `id` bigint(64) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `parent_id` bigint(64) DEFAULT '0' COMMENT '父级菜单',
  `name` varchar(255) DEFAULT NULL COMMENT '菜单名称',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=333DEFAULT CHARSET=utf8mb4 COMMENT='菜单表';

我之前设计接口返回格式：
[
{ "id":1,
"parentId":0,
"name":"menu1",
"child":[
 "id":2,
"parentId":1,
"name":"menu11",
]
},
{ "id":3,
"parentId":0,
"name":"menu2",
"child":[
 "id":4,
"parentId":3,
"name":"menu21",
]
}
]
这里id与parentId是对应的
请问 我需要如何传参数，才会有类似的返回结果
@TommyLemon

**Comment by fanpocha** [comment]
文档中,我还未找到如何传参
我现在有这样一张菜单表：
CREATE TABLE `menu` (
  `id` bigint(64) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `parent_id` bigint(64) DEFAULT '0' COMMENT '父级菜单',
  `name` varchar(255) DEFAULT NULL COMMENT '菜单名称',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=333DEFAULT CHARSET=utf8mb4 COMMENT='菜单表';

我之前设计接口返回格式：
[
{ "id":1,
"parentId":0,
"name":"menu1",
"child":[
 "id":2,
"parentId":1,
"name":"menu11",
]
},
{ "id":3,
"parentId":0,
"name":"menu2",
"child":[
 "id":4,
"parentId":3,
"name":"menu21",
]
}
]
这里id与parentId是对应的
请问 我需要如何传参数，才会有类似的返回结果
@TommyLemon

**Comment by TommyLemon** [comment]
http://apijson.cn/api/?json={%22[]%22:{%22Comment%22:{%22toId%22:0},%22Comment[]%22:{%22Comment%22:{%22toId@%22:%22[]%2FComment%2Fid%22}}},%22@explain%22:true}
![image](https://user-images.githubusercontent.com/5738175/135252514-5e1386f5-d258-4d88-bb06-de2377197e41.png)

**Comment by fanpocha** [comment]
感谢回复!
不过这种只支持两个层级，三个及以上都不能支持
@TommyLemon

**Comment by transtone** [comment]
这种多层的查询方式，在有 '@form@' 的这种复杂查询下不生效。
不知道是不是引用赋值的路径问题，没有尝试到正确的写法。
