### ISSUE TITLE
APIJSONBoot Mysql无法自定义的数据库配置

### ISSUE THREAD

**Issue by ChinaAstephen** [Tencent/APIJSON#332]
**环境信息**
 - 系统: Windows 10 
 - JDK: 1.8.0_17 
 - 数据库:  MySQL 8.0.25
 - APIJSON:   2.9.1 

**问题描述**

	@JSONField(serialize = true)  // 不在日志打印 账号/密码 等敏感信息，用了 UnitAuto 则一定要加
	@Override
	public String getDBAccount() {
		if (isMySQL()) {
			Log.i(TAG,"-------------------获取账号_________________________");
			return "Astephen";
		}
		return null;
	}

**错误信息**

 !!!! 查询权限配置异常 !!!
Access denied for user 'root'@'localhost' (using password: YES)

**Comment by ChinaAstephen** [comment]
![微信图片_20211102140553](https://user-images.githubusercontent.com/49969244/139795212-6386b06c-d802-475b-9267-818dd90fbdc4.png)
![微信图片_202111021405531](https://user-images.githubusercontent.com/49969244/139795236-29aaf9d2-7b04-4300-8d8b-5ca3ff3eebd7.png)

**Comment by ChinaAstephen** [comment]
DemoSqlConfig  里面的我填写的数据库信息不起作用,打印日志也没有输出走的还是APIJSONSQLConfig里面的内容,能看下是什么问题么?其他几个例子都完美运行了,就这个boot运行有问题!

**Comment by TommyLemon** [comment]
APIJSON 版本 2.9.1 也太老旧了，换最新的 4.8.0 试试，另外注意 apijson-framework, apijson-column, APIJSON-Demo 等的版本也要对应。

这是 4.8.0
https://github.com/APIJSON/APIJSON-Demo/releases/tag/4.8.0

这是最新版，目前等价于 4.8.0
https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server

**Comment by ChinaAstephen** [comment]
> APIJSON 版本 2.9.1 也太老旧了，换最新的 4.8.0 试试，另外注意 apijson-framework, apijson-column, APIJSON-Demo 等的版本也要对应。
> 
> 这是 4.8.0 https://github.com/APIJSON/APIJSON-Demo/releases/tag/4.8.0
> 
> 这是最新版，目前等价于 4.8.0 https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server

**Comment by ChinaAstephen** [comment]
![image](https://user-images.githubusercontent.com/49969244/139806316-70fd8f50-382f-40d8-9554-303b5adb2983.png)
我刚换了包,最新的4.8.0  另外lib目录下的jar包我也删了,从maven拉下来的最新代码

**Comment by ChinaAstephen** [comment]
@TommyLemon columen   那个也要4.8.0么?

**Comment by ChinaAstephen** [comment]
<dependency>
			<groupId>com.github.APIJSON</groupId>
			<artifactId>apijson-column</artifactId>
			<version>1.1.2</version>
		</dependency>   这个也要4.8.0么?

**Comment by TommyLemon** [comment]
> ![image](https://user-images.githubusercontent.com/49969244/139806316-70fd8f50-382f-40d8-9554-303b5adb2983.png) 我刚换了包,最新的4.8.0 另外lib目录下的jar包我也删了,从maven拉下来的最新代码

apijson-column 版本应该是 1.1.3
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONBoot/pom.xml
![Uploading image.png…]()
