### ISSUE TITLE
分布式缓存后，removeCache调用逻辑在哪里？

### ISSUE THREAD

**Issue by jianan789** [Tencent/APIJSON#337]
**具体说下**
AbstractSQLExecutor:
execute函数对GET/GETS/HEAD/HEADS 触发 getCache和putCache，
对应的 POST/ PUT/DELETE  并没有看到 removeCache 相关逻辑？

                    case GET:
                    case GETS:
                    case HEAD:
                    case HEADS:
                        result = isHead ? null : this.getCacheItem(sql, position, config.getCache());
                        Log.i("AbstractSQLExecutor", ">>> execute  result = getCache('" + sql + "', " + position + ") = " + result);

**为什么**
如果没有主动触发removeCache逻辑，缓存过期如何设定？定时触发？脏数据？

**Comment by TommyLemon** [comment]
默认是 session 级缓存，一次请求结束，AbstractSQLExecutor 实例就释放了，自然 cacheMap 也清空了，没必要  removeCache，只是提供给用户自定义缓存逻辑的接口，例如接入 Redis 做全局缓存
