### ISSUE TITLE
数据表名称区分大小写，提示找不到对应的数据表，请问有什么解决方法吗

### ISSUE THREAD

**Issue by vaseniu** [Tencent/APIJSON#343]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

**错误信息**

**Comment by TommyLemon** [comment]
数据库忽略大小写或者在 Access 表配置 alias（对外暴露的表名，必须大写英文字母开头），对应的 name 就是真实表名

**Comment by vaseniu** [comment]
使用方不想设置数据库，我们也没有用到Access表，还有其他方法吗

**Comment by vaseniu** [comment]
> 数据库忽略大小写或者在 Access 表配置 alias（对外暴露的表名，必须大写英文字母开头），对应的 name 就是真实表名
> 
> ![image](https://user-images.githubusercontent.com/5738175/143675561-91480872-831b-413f-a62e-ffaceb86d607.png)
使用方不想设置数据库，我们也没有用到Access表，还有其他方法吗

**Comment by TommyLemon** [comment]
在 DemoSQLConfig 重写 getSQLTable ，return table.toLowerCase();

**Comment by vaseniu** [comment]
> 在 DemoSQLConfig 重写 getSQLTable ，return table.toLowerCase();



好的，谢谢
