### ISSUE TITLE
apijson依赖的表如：request,access  我项目里可以不建这些表吗

### ISSUE THREAD

**Issue by 28-HuaSheng** [Tencent/APIJSON#344]
**具体说下**
apijson目前来看是依赖 request，access等表的，
假如我项目自己有权限层去验证权限，我只想使用apijson的sql自动化功能，那么我是否可以不依赖 request，access等表
这样也不会侵入我的业务表

**为什么**
希望不侵入我的业务数据库，所以我们项目这边不希望引入request，access等表，
那么这样apijson是否能支持？

**Comment by TommyLemon** [comment]
支持，见常见问题 14
https://github.com/Tencent/APIJSON/issues/36
