### ISSUE TITLE
A Join B，B的字段不能重命名？？？

### ISSUE THREAD

**Issue by TORRYGUO** [Tencent/APIJSON#346]
http://apijson.cn:8080/get/%7B%22[]%22:%7B%22count%22:5,%22join%22:%22&/User/id@,%3C/Comment/momentId@%22,%22Moment%22:%7B%22@column%22:%22id,userId,content%22,%22@group%22:%22id%22%7D,%22User%22:%7B%22name~%22:%22t%22,%22id@%22:%22/Moment/userId%22,%22@column%22:%22id,name,head%22%7D,%22Comment%22:%7B%22momentId@%22:%22/Moment/id%22,%22@column%22:%22id:ids,momentId,content%22%7D%7D%7D

**Comment by TORRYGUO** [comment]
join的demo对Comment的id做了重命名，请求失败

**Comment by TommyLemon** [comment]
> [http://apijson.cn:8080/get/%7B%22[]%22:%7B%22count%22:5,%22join%22:%22&/User/id@,%3C/Comment/momentId@%22,%22Moment%22:%7B%22@column%22:%22id,userId,content%22,%22@group%22:%22id%22%7D,%22User%22:%7B%22name~%22:%22t%22,%22id@%22:%22/Moment/userId%22,%22@column%22:%22id,name,head%22%7D,%22Comment%22:%7B%22momentId@%22:%22/Moment/id%22,%22@column%22:%22id:ids,momentId,content%22%7D%7D%7D](http://apijson.cn:8080/get/%7B%22%5B%5D%22:%7B%22count%22:5,%22join%22:%22&/User/id@,%3C/Comment/momentId@%22,%22Moment%22:%7B%22@column%22:%22id,userId,content%22,%22@group%22:%22id%22%7D,%22User%22:%7B%22name~%22:%22t%22,%22id@%22:%22/Moment/userId%22,%22@column%22:%22id,name,head%22%7D,%22Comment%22:%7B%22momentId@%22:%22/Moment/id%22,%22@column%22:%22id:ids,momentId,content%22%7D%7D%7D)

给的这个例子没问题，不过也没取别名。
http://apijson.cn/api/?url=http://apijson.cn:8080/get&type=JSON&json=%7B%22%5B%5D%22%3A%7B%22count%22%3A5%2C%22join%22%3A%22%26%2FUser%2Fid%40%2C%3C%2FComment%2FmomentId%40%22%2C%22Moment%22%3A%7B%22%40column%22%3A%22id%2CuserId%2Ccontent%22%2C%22%40group%22%3A%22id%22%7D%2C%22User%22%3A%7B%22name~%22%3A%22t%22%2C%22id%40%22%3A%22%2FMoment%2FuserId%22%2C%22%40column%22%3A%22id%2Cname%2Chead%22%7D%2C%22Comment%22%3A%7B%22momentId%40%22%3A%22%2FMoment%2Fid%22%2C%22%40column%22%3A%22id%2CmomentId%2Ccontent%22%7D%7D%7D

![image](https://user-images.githubusercontent.com/5738175/144415742-440b4760-4218-408a-b549-7a00b03fc32a.png)

INNER JOIN  副表取别名没问题，
![image](https://user-images.githubusercontent.com/5738175/144416656-91568ad0-a71f-4795-a4e6-711f51680cd7.png)

LEFT JOIN 需要再多返回一个没有别名的原始字段名
![image](https://user-images.githubusercontent.com/5738175/144417388-e651f971-ba6a-4aa0-aca1-a488be9b98ef.png)

否则报错
![image](https://user-images.githubusercontent.com/5738175/144417248-c58be2b9-1367-489b-9c1b-c9a1f92f8206.png)

**Comment by TommyLemon** [comment]
是个 bug，解决方式是 
https://github.com/Tencent/APIJSON/issues/341#issuecomment-976392482

**Comment by TommyLemon** [comment]
已解决
https://github.com/Tencent/APIJSON/commit/6023bc0fba0ad9a6d4101e361d9fc987d4548139#diff-90f54e68621e69e78a57b01f11fa6ee7ed0b604123e0ee711fce12342cf0c25aL1504-L1509

![image](https://user-images.githubusercontent.com/5738175/144718861-81300403-a394-4714-9ce5-f866ded5aa02.png)
