### ISSUE TITLE
put请求可以直接修改数据库json字段吗

### ISSUE THREAD

**Issue by WaizLee** [Tencent/APIJSON#362]
**环境信息**
 - APIJSON:   4.8.0 

**问题描述**

{
    "ReviewApply": {
        "id": "1470678208578899968", //申请表id
        "document_list": [
            "test_v1.1.docx"
        ]
    },
    "tag": "updateReviewApply"
}
不使用+ -号，无法直接替换document_list字段

**Comment by weiwei162** [comment]
这里代码后边使用了数据库查出来的值，还是不能整个替换掉原来的

**Comment by WaizLee** [comment]
改成字符串 "[...]" ，会报错
Data truncation: Invalid JSON text: \"Invalid value.\" at position 2 in value for column 'review_apply.document_list
"ReviewApply": {
        "id": "1470678208578899968",
        "document_list": "[test1111.docx,test2222.docx]"
    }

如果不转按原来的
{
"ReviewApply": {
"id": "1470678208578899968", //申请表id
"document_list": [
"test_v1.1.docx"
]
},
"tag": "updateReviewApply"
}

没有报错，可以看到sql语句是查原来的值，再update，没有替换传入的新值。
![image](https://user-images.githubusercontent.com/91610687/151274763-22a0ec5b-eea5-449b-b8a1-47752de49b9f.png)

**Comment by TommyLemon** [comment]
> 改成字符串 "[...]" ，会报错 Data truncation: Invalid JSON text: "Invalid value." at position 2 in value for column 'review_apply.document_list "ReviewApply": { "id": "1470678208578899968", "document_list": "[test1111.docx,test2222.docx]" }
> 
> 如果不转按原来的 { "ReviewApply": { "id": "1470678208578899968", //申请表id "document_list": [ "test_v1.1.docx" ] }, "tag": "updateReviewApply" }
> 
> 没有报错，可以看到sql语句是查原来的值，再update，没有替换传入的新值。 ![image](https://user-images.githubusercontent.com/91610687/151274763-22a0ec5b-eea5-449b-b8a1-47752de49b9f.png)

字符串没用 "" 包裹，这不是一个合法的 JSON String，得改成
"[\"test1111.docx\",\"test2222.docx\"]"

**Comment by TommyLemon** [comment]
> 之前不允许的这个限制在最近的版本（可能 4.7.2）就取消了 https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractObjectParser.java ![image](https://user-images.githubusercontent.com/5738175/151006987-251373a8-b774-403d-8931-30d55c2dc673.png)

这里需要改下源码，判断 putType == 0 时直接用 value，不再从数据库查值。

**Comment by TommyLemon** [comment]
@WaizLee 解决了吗？解决了的麻烦贡献下代码
https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md#%E5%85%B6%E4%B8%AD%E7%89%B9%E5%88%AB%E8%87%B4%E8%B0%A2-
![image](https://user-images.githubusercontent.com/5738175/157060395-c367cf04-1831-47de-8fb2-8b47450c9712.png)

**Comment by WaizLee** [comment]
已收到！

**Comment by WaizLee** [comment]
已收到！
