### ISSUE TITLE
为啥配置了Schema 不生效

### ISSUE THREAD

**Issue by MuJianxuan** [Tencent/APIJSON#363]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

![image](https://user-images.githubusercontent.com/50062346/151010512-6629add3-f4b0-459d-805c-a226e2d5148d.png)
下载的demo 

还有一个我觉得奇怪的是
![image](https://user-images.githubusercontent.com/50062346/151010720-8d771ca5-c1df-4c09-a0f1-cb75c50f5f2f.png)
我本地可以连接的，但是 在项目运行却提示运行 访问权限问题，我不太确定是不是 sys.Test导致的。
![image](https://user-images.githubusercontent.com/50062346/151010920-a9ec3bc8-0769-4f97-8245-9779c52a5922.png)
![image](https://user-images.githubusercontent.com/50062346/151011031-c68b4c72-71ff-413f-be44-a0ac498290d9.png)

**错误信息**

**Comment by TommyLemon** [comment]
DemoSQLConfig 重写 getSchema，判断 getDatasource 的值不为空就 return null，或者登录接口 defaults 里传 "@schema":""

https://github.com/Tencent/APIJSON/issues/364#issuecomment-1031357714
