### ISSUE TITLE
当QPS超过200时性能表现大幅下降

### ISSUE THREAD

**Issue by kevin2008001** [Tencent/APIJSON#366]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  apijson-demo-druid
 - Version: 4.8.3
**问题描述**
在进行单条数据查询压测实验时，当QPS达到200时 99百分位平均达到700甚至更高，CPU利用率上升到70%以上
![image](https://user-images.githubusercontent.com/43140674/154432753-6fbf0c14-4f76-44e7-89b9-8e40edc80aa5.png)

**Comment by TommyLemon** [comment]
Log.DEBUG = false 关掉日志，另外可以升级 APIJSON 及 apijson-framework 版本为 4.9.1

**Comment by kevin2008001** [comment]
logging.level.root=INFO
为什么我debug日志关了还是会打呢？
![image](https://user-images.githubusercontent.com/43140674/154674538-4f36930c-f68a-4c6f-9b78-321cecb023e7.png)

**Comment by TommyLemon** [comment]
> logging.level.root=INFO

"logging.level.root=INFO" 这和 APIJSON 有什么关系？请用官方的方式关日志
![image](https://user-images.githubusercontent.com/5738175/154698195-1bb0c419-2933-4076-8fd3-c964c6806b96.png)

**Comment by kevin2008001** [comment]
非常感谢，优化后性能提升还是比较明显的

![image](https://user-images.githubusercontent.com/43140674/155491139-ff045a1a-8850-4d47-8780-d69c849eb0d9.png) ![image](https://user-images.githubusercontent.com/43140674/155491704-6b4a5ded-7ab5-4e6d-bf54-06af1c88fc7c.png)


**另外还想请教下 有没有更进一步的调优措施呢？**

**Comment by xiaokek** [comment]
这广告真硬
