### ISSUE TITLE
大佬,如果我想用APIJSON,但是apisix做网关,鉴权这块有啥好建议吗?

### ISSUE THREAD

**Issue by caobingsheng** [Tencent/APIJSON#369]

**Comment by TommyLemon** [comment]
网关层和应用服务层又不冲突，两者的鉴权可以都用，也可以只用一个。
如果只用网关的鉴权，可以把鉴权的相关信息传到应用服务层。

https://github.com/Tencent/APIJSON/issues/242

**Comment by caobingsheng** [comment]
明白了，也就是说我可以自己实现APIJSONVerifier，来适配现有权限框架，谢谢
