### ISSUE TITLE
最新QQ群无法加入，验证问题？

### ISSUE THREAD

**Issue by JackBlack666** [Tencent/APIJSON#373]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

**错误信息**

**Comment by TommyLemon** [comment]
首页 README 就有答案
https://github.com/Tencent/APIJSON#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
