### ISSUE TITLE
参数校验失效

### ISSUE THREAD

**Issue by yiyishifei** [Tencent/APIJSON#379]
**环境信息**
 - 系统: Windows 10 
 - JDK: 1.8.0_17
 - 数据库:  MySQL 8.0.22 
 - APIJSON:  5.0.0 

**问题描述**
APIJSONDemo-HikariCP，DemoController设置setNeedVerify(false)时校验参数会失效，请问校验参数必须setNeedVerify(true)吗？如果只需要校验参数不校验权限怎么做呢？

**Comment by TommyLemon** [comment]
不是失效，是你关掉了校验，setNeedVerify 是统一开关，也可以 setNeedVerifyContent, setNeedVerifyAccess, setNeedVerifyLogin 单独设置，见常见问题 14，里面明确说明的问题不要再问了
https://github.com/Tencent/APIJSON/issues/36
