### ISSUE TITLE
关于级联查询返回结果优化的问题

### ISSUE THREAD

**Issue by daniellimin** [Tencent/APIJSON#380]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**
项目中需要做一个三级树形结构的查询。
请求：
![image](https://user-images.githubusercontent.com/34907277/161931695-64ac8d64-b2f0-49df-8c75-2b64dba4b9dc.png)
返回：
![image](https://user-images.githubusercontent.com/34907277/161931967-f0f1e380-2017-448f-9adc-f421b8a23754.png)
功能可以实现，不过能不能通过数组名与表名相同的方法提取下返回信息，优化下返回数据。
我尝试的请求如下：
![image](https://user-images.githubusercontent.com/34907277/161932982-89eb9f1b-d71b-453d-8955-2423afb064d6.png)

不知道是赋值的路径写的不对还是不支持这样实现。

**Comment by TommyLemon** [comment]
提取字段后，非提取字段都会丢弃。
你这里应该只提取最内层的 CapThreeType，外面两层不应该提取

**Comment by daniellimin** [comment]
明白了。非常感谢。
