### ISSUE TITLE
oracle分页查询语句 生成的语句无法在oracle中获取数据

### ISSUE THREAD

**Issue by SingleDogL** [Tencent/APIJSON#384]
数据库版本  ORACLE 12.2.0.1.0
JDK 1.8

示例

SELECT * FROM (SELECT * FROM TABLE_NAME WHERE  (  COL_1 = 'abc' )  )  WHERE ROWNUM BETWEEN 10 AND 20
这种语句在oracle中无法获取数据，能不能将数据库生成语句时
SELECT * FROM (SELECT *，ROWNUM r FROM TABLE_NAME WHERE  (  COL_1 = 'abc' )  )  WHERE r BETWEEN 10 AND 20
改成生成这种样子的？这样子的可以获取数据

**Comment by SingleDogL** [comment]
或者其他分页样式的也一样？

**Comment by TommyLemon** [comment]
"@column":"ROWNUM,其他字段"

**Comment by SingleDogL** [comment]
如果是按照我示例的那种 是不行的  要给ROWNUM取别名才行 比如r  因为您在
AbstractSQLConfig.getLimitString(int page, int count, boolean isTSQL, boolean isOracle)
这一方法里 限制了“WHERE ROWNUM between” 这一语句生成形式  而按照我的示例  要改成“WHERE r between” 这种 才能执行
单纯的ROWNUM还是不行的

**Comment by TommyLemon** [comment]
> 如果是按照我示例的那种 是不行的 要给ROWNUM取别名才行 比如r 因为您在 AbstractSQLConfig.getLimitString(int page, int count, boolean isTSQL, boolean isOracle) 这一方法里 限制了“WHERE ROWNUM between” 这一语句生成形式 而按照我的示例 要改成“WHERE r between” 这种 才能执行 单纯的ROWNUM还是不行的

那你改下源码试试吧，我电脑和服务器空间都不够，装不了 Oracle
