### ISSUE TITLE
apijson怎么做到对字段级别的控制

### ISSUE THREAD

**Issue by wang190416941** [Tencent/APIJSON#386]
我需要自己定义用户，控制到到字段级别，这个怎么操作。我现在使用postmen做请求发送做测试，我怎么来登陆账户。

**Comment by TommyLemon** [comment]
字段及权限控制
https://github.com/Tencent/APIJSON/issues/357

要登录就调登录接口，和 APIJSON 没有必然的关系，和你自己的登录代码实现有关，参考 Demo
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONBoot-MultiDataSource/src/main/java/apijson/boot/DemoController.java#L585-L601

https://github.com/xlongwei/light4j/tree/master/apijson
![image](https://user-images.githubusercontent.com/5738175/162986969-6b6a4840-4cbf-43b2-86bd-17871c71c861.png)
