### ISSUE TITLE
如何实现连表插入数据

### ISSUE THREAD

**Issue by fdw1466** [Tencent/APIJSON#391]
**环境信息**
系统: Windows 10
JDK: 1.8.0_17
数据库: MySQL 8.0.28
APIJSON: 5.0.0

**问题描述**
当进行连接表操作时，引用赋值不起效果。

数据库结构如下：
主表：
CREATE TABLE `tb_fence` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `customer_id` int(11) NOT NULL COMMENT '所属客户',
  `name` varchar(64) NOT NULL COMMENT '名称',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
) ;
从表：
CREATE TABLE `tb_fence_loc` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `customer_id` int(11) NOT NULL COMMENT '所属客户',
  `fence_id` int(11) NOT NULL COMMENT '围栏',
  `axis_x` varchar(32) DEFAULT NULL COMMENT 'x坐标',
  `axis_y` varchar(32) DEFAULT NULL COMMENT 'y坐标',
  `axis_z` varchar(32) DEFAULT NULL COMMENT 'z坐标',
);

执行的apijson如下：
{
    "Fence": {
        "name": "test",
    },
    "FenceLoc": {
        "fence_id": "Fence/id",    //引用赋值不起效果
        "axis_x": 1,
        "axis_y": 1,
        "axis_z": 1
    },
    "tag": "Fence:{}",
    "@role": "OWNER"
}

执行结果：
{
    "Fence": {
        "name": "test"
    },
    "FenceLoc": {
        "fence_id": "Fence/id",
        "axis_x": 1,
        "axis_y": 1,
        "axis_z": 1
    },
    "ok": false,
    "code": 500,
    "msg": "数据库驱动执行异常SQLException，非 Log.DEBUG 模式下不显示详情，避免泄漏真实模式名、表名等隐私信息"
}

异常信息：
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
已生成 1 条 SQL
execute  startTime = 1652166281308
database = ; schema = ; sql = 
INSERT INTO `indoor`.`tb_fence`(`name`,`customer_id`) VALUES('test',1)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-05-10 03:04:41.309: 
AbstractSQLExecutor.DEBUG: <<<<<<<<<<<<<< TRANSACTION begin transactionIsolation = 4 >>>>>>>>>>>>>>>>>>>>>>> 
2022-05-10 03:04:41.313: AbstractParser.DEBUG: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
 已执行 1/200 条 SQL 
 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
已生成 2 条 SQL
execute  startTime = 1652166281313
database = ; schema = ; sql = 
INSERT INTO `indoor`.`tb_fence_loc`(`fence_id`,`axis_x`,`axis_y`,`axis_z`,`customer_id`) VALUES('Fence/id',1,1,1,1)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-05-10 03:04:41.313: 
AbstractSQLExecutor.DEBUG: <<<<<<<<<<<<<< TRANSACTION begin transactionIsolation = 4 >>>>>>>>>>>>>>>>>>>>>>> 
2022-05-10 03:04:41.330: AbstractParser.DEBUG: <<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
 已执行 2/200 条 SQL 
 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Incorrect integer value: 'Fence/id' for column 'fence_id' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)

异常分析：
根据生成的第二条SQL可看出，引用赋值不起效果。

**Comment by TommyLemon** [comment]
没看出来问题，可能表名映射错误或字段名错误等，需要把控制台打印的 SQL 发出来。你自己复制 SQL 去数据库执行下，应该可以确定问题所在
