### ISSUE TITLE
PUT修改数据时，非主键作为where条件的疑问

### ISSUE THREAD

**Issue by LeoGZ** [Tencent/APIJSON#397]
系统: windows
JDK: 1.8
数据库: Mysql
APIJSON: 5.0.0

问题描述
假设业务上需要两张表做关联修改，PUT例子如下：
![image](https://user-images.githubusercontent.com/16578406/168984288-db363eec-5ca2-41f9-859f-82b71ae79f87.png)

但目前已知在开启 AbstractSQLConfig.prepared 的情况下，如果通过非ID主键进行修改如有以下正则限制。
目前是可以通过修改 prepared 为false 跳过限制。但还是存在一些疑问

```
Pattern PATTERN_RANGE = Pattern.compile("^[0-9%,!=\\<\\>/\\.\\+\\-\\*\\^]+$");

for(int j = 0; j < ccs.length; ++j) {
    String c = ccs[j];
    if ("=null".equals(c)) {
        c = SQL.isNull();
    } else if ("!=null".equals(c)) {
        c = SQL.isNull(false);
    } else if (this.isPrepared() && (c.contains("--") || !PATTERN_RANGE.matcher(c).matches())) {
        throw new UnsupportedOperationException(key + ":value 的 value 中 " + c + " 不合法！预编译模式下 key{}:\"condition\" 中 condition 必须 为 =null 或 !=null 或 符合正则表达式 " + PATTERN_RANGE + " ！不允许连续减号 -- ！不允许空格！");
    }

    expr = expr + (j <= 0 ? "" : lk) + fk + c;
}
```

只允许数字作为where条件 ，请问是出于什么考虑？

**Comment by TommyLemon** [comment]
处于安全考虑。
可以用 选项范围
"TEST1_ID{}":["0198...7ff4"]

替代以上截屏中对应的 条件范围
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2
