### ISSUE TITLE
关于20220523的fastjson的安全漏洞，作者是否考虑升级到2.0？

### ISSUE THREAD

**Issue by LeoGZ** [Tencent/APIJSON#400]
1. 风险描述
fastjson已使用黑白名单用于防御反序列化漏洞，经研究该利用在特定条件下可绕过默认autoType关闭限制，攻击远程服务器，风险影响较大。建议fastjson用户尽快采取安全措施保障系统安全。

2. 影响版本
特定依赖存在下影响 ≤1.2.80

 具体漏洞如下
https://github.com/alibaba/fastjson/wiki/security_update_20220523
https://github.com/alibaba/fastjson/releases/tag/1.2.83

**Comment by TommyLemon** [comment]
感谢反馈和建议，目前临时解决方案是 setSafaMode，后续打算提供扩展方式，开发者可以选用其它 JSON 库

**Comment by TommyLemon** [comment]
感谢 @NeoGitCrt1 帮忙升级 fastjson 到 2.0.4 👍

https://github.com/Tencent/APIJSON/pull/401

**Comment by TommyLemon** [comment]
@LeoGZ  APIJSON 8 已经去掉 fastjson
https://github.com/Tencent/APIJSON/commit/6712e9602cd1a2db95667a3c7cbd29e35233ef66
https://github.com/APIJSON/apijson-framework/commit/df9ca577411b248f642c8ace72252925db858186

3 个 Demo 已使用 APIJSON 8
https://github.com/APIJSON/APIJSON-Demo/commits/master/APIJSON-Java-Server
<img width="1531" alt="Image" src="https://github.com/user-attachments/assets/cd87aa83-5e2e-476e-b046-d083698e80fb" />

当然这个也导致初始化麻烦一些，需要重写 parseObject, parseArray 等方法，用具体的 JSON 库来反序列化，
打算后续提供 apijson-fastjson2, apijson-jackson, apijson-gson 等对应插件，引入后可以简化这部分代码：
https://github.com/APIJSON/APIJSON-Demo/blob/eb051b0df273f30479b10d1238d666e4ed2efadd/APIJSON-Java-Server/APIJSONDemo/src/main/java/apijson/demo/DemoApplication.java#L81-L127
