### ISSUE TITLE
如何动态创建数据库表？

### ISSUE THREAD

**Issue by gemufeng** [Tencent/APIJSON#404]
非常感谢apijson团队。但是我有另外一个需求，就是我希望数据库表的创建也是动态的，根据前端传过去的json描述来创建table，请问有什么好的办法吗？或者说有没有可以推荐的框架。

**Comment by TommyLemon** [comment]
不支持，MySQLWorkbench, DataGrip, Navicat 等数据库工具都能很简单方便且安全可控地 创建和修改 表结构。
如果只是内部极少人员使用，直接编写或转为 DDL  的 SQL 发到数据库执行即可。
