### ISSUE TITLE
路径错了^_^

### ISSUE THREAD

**Issue by wahowaho** [Tencent/APIJSON#406]
![image](https://user-images.githubusercontent.com/28621460/172323036-6afca415-34f9-4227-90b0-a1c27934cc2f.png)

**Comment by TommyLemon** [comment]
确实错了，可以帮忙改下发个 Pull Request，谢谢。
开源要大家一起参与贡献才会更美好~
![image](https://user-images.githubusercontent.com/5738175/172325029-b410d90f-0989-4aaa-865d-5a845aca2f1b.png)

https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%80%E5%AE%9A%E8%A6%81%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81

**Comment by TommyLemon** [comment]
感谢 @[jianlvliu](https://github.com/jianlvliu)  修复了这个问题~
