### ISSUE TITLE
主键问题

### ISSUE THREAD

**Issue by cyfrank124** [Tencent/APIJSON#410]
版本：APIJSON 5.1.0
类 apijson.orm.AbstractSQLConfig#newSQLConfig方法下的关于主键的默认赋值操作，我如果想自己修改我的主键字段名称可以重写Callback<T> callback，但是我数据库设置了主键递增，我POST请求就是不想传主键，这种有什么好的解决办法

**Comment by TommyLemon** [comment]
都看到这段代码了，为啥不看看旁边的注释？

**Comment by cyfrank124** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
