### ISSUE TITLE
word文档错别字

### ISSUE THREAD

**Issue by Finkyky** [Tencent/APIJSON#420]
![image](https://user-images.githubusercontent.com/82637350/179472944-d9be81e7-6fb2-4940-badd-9e8e1a92ca41.png)
应该是“接口”，不是借口

**Comment by TommyLemon** [comment]
确实错了，感谢反馈，可以帮忙改下发个 Pull Request，谢谢。
开源要大家一起参与贡献才会更美好~
<img width="906" alt="image" src="https://user-images.githubusercontent.com/5738175/179498656-963dc7d3-dce7-4be3-8d2e-e4f8ad5f2a43.png">

https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%80%E5%AE%9A%E8%A6%81%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81


https://github.com/Tencent/APIJSON/issues/406
