### ISSUE TITLE
子查询关联多个条件

### ISSUE THREAD

**Issue by feishu** [Tencent/APIJSON#422]
![HB @%_XI~5JM(}C`I}5D_`L](https://user-images.githubusercontent.com/950717/179908980-87653da9-e587-4d52-9fab-f4629e496f7e.jpg)
想得到如下结果。

现提示如下错误 "msg": "服务器内部错误，解析子查询 []/0/Cep_user_measure_test/dept_id}{@:{ } 为 Subquery 对象失败！", 会报这样的错

![B4$Q~)B29W4P{L$))JQZ9N1](https://user-images.githubusercontent.com/950717/179909051-a62c4ee9-99cd-48b5-a79e-dd94e0ba2c40.jpg)

**Comment by TommyLemon** [comment]
路径写错了，多看文档！
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/5738175/179949910-1065996e-a7da-4747-9cc6-1764c81d954a.png">

<img width="922" alt="image" src="https://user-images.githubusercontent.com/5738175/179949747-3b70ca5f-e575-4932-8a43-2eef324ea229.png">

目前可以改用 IN，里面不需要写任何引用赋值键值对。


或者
用 @raw 实现 EXISTS 关联字段
```js
"id":"xxx_test.dept_id",
"his_dept_id":"xxx_test.dept_id",
"@combine":"id,his_dept_id"
```

另外，既然你懒得发文本，我也不想浪费时间帮你具体一个个字符打出来。
