### ISSUE TITLE
跨库查询列表语法

### ISSUE THREAD

**Issue by transtone** [Tencent/APIJSON#423]
用的postgresql，写在代码中的默认 schema 是 apijson , 此时要查询另外一个 schema dict 中的 user_list 表数据，应该怎么查呢？
```json
{
    "[]": {	
	"user_list": {        
		"@column": "id,user_name",
                "@schema": "dict",
	},
        "count": 3,
    },
}
```
这样写会报错：
`数组 []:{} 中每个 key:{} 都必须是表 TableKey:{} 或 数组 arrayKey[]:{}`

===============

经测试，发现有这样的现象：
1. 修改Access表的内容(name, alias)之后，必须重启程序，否则不生效。
2. 表的名称不能有下划线，如果有下划线，必须用 alias 。

满足上面两个条件之后，则可以正常查询。
对于1，用了数据库表还必须重启程序才能生效的做法十分不理解。
对于2，没看到faq里有提到，表名不能包含下划线。

**Comment by TommyLemon** [comment]
1.你没认真看完常见问题 issue，里面提到调接口热重载方式

2.不是下划线问题，是首字母没大写问题，这点不管是首页 README 注意事项、通用文档、常见问题 issue 全都有说明

**Comment by transtone** [comment]
> 1.你没认真看完常见问题 issue，里面提到调接口热重载方式
> 
> 2.不是下划线问题，是首字母没大写问题，这点不管是首页 README 注意事项、通用文档、常见问题 issue 全都有说明


感谢回复。
1. 接口热重载，也就是自动重启，那也是需要重启，只不过是自动触发重启。
2. 也就是说首字母不是大写的表，都需要alias了，和是不是下划线没有本质区别。

这些使用中经常遇到的问题，我看还是有人问的，`apijson-doc` 是否可以把这些都加进来呢？ 
![image](https://user-images.githubusercontent.com/46688/180107393-59791c60-f70c-430b-808a-0d883e65028c.png)

**Comment by transtone** [comment]
这个截图我觉得可以说明一些问题，使用者关注的`重点`只是很小的字，也不加粗，而无用的废话又粗又大。表面上在FAQ里有了，可不仔细找还真找不到，对有心尝鲜的童鞋很不友好呀。
![image](https://user-images.githubusercontent.com/46688/180107867-c3c30353-4498-4644-ad5d-9853be3b7ece.png)

**Comment by TommyLemon** [comment]
我提到 3 处，你找到了第 4 处。

首页注意事项不够显眼吗？
https://github.com/Tencent/APIJSON#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
<img width="893" alt="image" src="https://user-images.githubusercontent.com/5738175/180174544-b9cd2153-8470-4321-9c9d-385c90d92c44.png">

常见问题上方
https://github.com/Tencent/APIJSON/issues/36
<img width="796" alt="image" src="https://user-images.githubusercontent.com/5738175/180174846-b56618de-48b4-4e57-a2cf-02bd2a530cd8.png">

3.设计规范
3.1 操作方法
https://github.com/Tencent/APIJSON/blob/master/Document.md#31-%E6%93%8D%E4%BD%9C%E6%96%B9%E6%B3%95
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/5738175/180175033-557523ab-7fe8-494d-9209-ebe36c883618.png">

另外配套的接口工具 APIAuto 也有静态检查，是没用它还是没看旁边注释？
http://apijson.cn/api/
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/5738175/180175357-b6ec0763-b1f2-4f58-afc0-520752b18b4a.png">
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/5738175/180175395-841e79d6-7694-4921-9829-8aab6a1958fc.png">


你要是觉得还不够可以提个 PR 优化文档，或者改源码

**Comment by TommyLemon** [comment]
MySQL 默认大小写不敏感，SELECT * FROM `Moment` 也可以访问到 `moment` 表。
对于 PostgreSQL, Oracle 等默认大小写敏感的数据库，可以设置为不敏感，或者在 APIJSON 项目
DemoSQLConfig 重写 getSQLTable，直接 toLowerCase/toUpperCase

**Comment by transtone** [comment]
> 1.并没有重启，只是重新加载了配置数据，你可以看 APIJSONController.reload 实现代码
> 
> 2.MySQL 默认大小写不敏感，SELECT * FROM `Moment` 也可以访问到 `moment` 表。 对于 PostgreSQL, Oracle 等默认大小写敏感的数据库，可以设置为不敏感，或者在 APIJSON 项目 DemoSQLConfig 重写 getSQLTable，直接 toLowerCase/toUpperCase #343

可以给一个重写 getSqLTable 的例子吗？
```java
    private String table;

    @Override
    public String getSQLTable() {
        return table.toLowerCase();
    }

```
这样写根本跑不起来。

**Comment by TommyLemon** [comment]
Access 表里可以配置 name 和 alias，单个指定请求传参表名和数据库真是表名的映射关系
