### ISSUE TITLE
为什么限制在GETS中使用@combine

### ISSUE THREAD

**Issue by aldag** [Tencent/APIJSON#425]
在GETS请求中使用@combine时得到了这样的提示：
` "msg": "StandardAdvice:{} 里的 @combine:value 不合法！DELETE,GETS,HEADS 请求不允许传 @combine:value !"`
查代码发现，这个检查逻辑是硬编码在AbstractSQLConfig类中的。

为什么在这些类型的请求中限制@combine的使用呢？

**Comment by TommyLemon** [comment]
防止前端传参越权操作，例如把后端设置的条件 AND 连接改为 OR 连接

**Comment by aldag** [comment]
> 防止前端传参越权操作，例如把后端设置的条件 AND 连接改为 OR 连接
在AbstractSQLConfig做检查，后端也用不了@combine了，检查点能否前移呢？

**Comment by TommyLemon** [comment]
可以的，把 AbstractSQLConfig 里的检查移到 AbstractVerifier，判断 JSONRequest.KEY_COMBINE.equals(rk) 就抛异常 
https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractVerifier.java#L1006

**Comment by TommyLemon** [comment]
6.0.0 已支持后端在 Request 表中配置 @combine，感谢 @cloudAndMonkey 的贡献 
https://github.com/Tencent/APIJSON/pull/493
