### ISSUE TITLE
远程函数对request的修改不生效

### ISSUE THREAD

**Issue by aldag** [Tencent/APIJSON#426]
Demo项目里自带一个`removeKey`函数，其描述是“从对象里移除 key”
![image](https://user-images.githubusercontent.com/7386239/180429226-f8899ea4-89a4-4f6c-923f-eaab0a1cac0f.png)

在使用中发现，其移除未生效：
![image](https://user-images.githubusercontent.com/7386239/180429532-dbbbf7d5-68c2-466d-bf7a-53108b970e4c.png)
从返回的sql语句看，`name`字段没被移除。

于是我debug了一下，发现`removeKey`函数确实移除了`name`字段。
![image](https://user-images.githubusercontent.com/7386239/180429801-d190f780-882b-4494-ab34-3d06d9fb0041.png)
![image](https://user-images.githubusercontent.com/7386239/180429844-e684d105-9cbf-40c8-acf8-42a8538f8e1b.png)

以上情况令人迷惑。`removeKey`函数不是这么用得吗？远程调用函数的“字段拼接、结构变换”怎么实现呢？
![image](https://user-images.githubusercontent.com/7386239/180430874-35fc5480-41cd-4191-8e76-f5c894d11fa9.png)

**Comment by TommyLemon** [comment]
是个 bug，可能是反射调用，对 request 传的不是引用而是 clone 的值

**Comment by TommyLemon** [comment]
request 已经解析完了，作为和数据库 SQL 直接相关的都存到 sqlRequest 对象了，所以移除 request 里面的 key 没用，得再加上移除 sqlRequest 的代码
https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractObjectParser.java#L483
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/5738175/180436760-1f497245-82d2-4d7e-bf23-1e0b83ea436e.png">

**Comment by TommyLemon** [comment]
目前可以把远程函数写在最前面执行来解决这个问题

**Comment by TommyLemon** [comment]
已解决
https://github.com/Tencent/APIJSON/commit/08581418850ed44449390d1404e49832bc15a488

**Comment by cloudAndMonkey** [comment]
1、 继承 APIJSONParser

**Comment by cloudAndMonkey** [comment]
5.2版本
1、 继承 APIJSONParser
![image](https://user-images.githubusercontent.com/12228225/200757521-b5d70b12-4f45-4097-9eb7-dc6758687305.png)
![image](https://user-images.githubusercontent.com/12228225/200757630-2fac25ec-fee3-4aa5-bad1-f8bf5709ad83.png)
2、重载 executeSQL方法
执行sql语句之前, 进行替换
![image](https://user-images.githubusercontent.com/12228225/200757693-62ea609a-a7e7-4b59-8f71-cff2a47f8671.png)
![image](https://user-images.githubusercontent.com/12228225/200757804-6519aa5d-332c-4a3a-aaf6-015d418584a1.png)

**Comment by TommyLemon** [comment]
> 5.2版本 1、 继承 APIJSONParser ![image](https://user-images.githubusercontent.com/12228225/200757521-b5d70b12-4f45-4097-9eb7-dc6758687305.png) ![image](https://user-images.githubusercontent.com/12228225/200757630-2fac25ec-fee3-4aa5-bad1-f8bf5709ad83.png) 2、重载 executeSQL方法 执行sql语句之前, 进行替换 ![image](https://user-images.githubusercontent.com/12228225/200757693-62ea609a-a7e7-4b59-8f71-cff2a47f8671.png) ![image](https://user-images.githubusercontent.com/12228225/200757804-6519aa5d-332c-4a3a-aaf6-015d418584a1.png)

感谢分享解决方案~

**Comment by cloudAndMonkey** [comment]
> 已解决 [0858141](https://github.com/Tencent/APIJSON/commit/08581418850ed44449390d1404e49832bc15a488)

看了作者的源码实现
就是把 request 改成了 sqlRequest 😂
![image](https://user-images.githubusercontent.com/12228225/202624255-6073a80c-be5b-4578-8f9f-e4bc604d0de4.png)
为啥要传递 sqlRequest, 后面通过 sqlRequest生成column、value, 然后将数据组装sql插入数据库
![image](https://user-images.githubusercontent.com/12228225/202627508-dc9f3c9e-42da-4813-b979-65e101c3f7f2.png)
![image](https://user-images.githubusercontent.com/12228225/202627866-33d2ee7c-1e2d-43fc-9701-dd06cc4df7c4.png)
![image](https://user-images.githubusercontent.com/12228225/202628145-990485fd-94f0-4006-9471-4b1cc4f46b30.png)
![image](https://user-images.githubusercontent.com/12228225/202628597-471eed38-b3f0-4f34-abc7-d2cd14aab18a.png)

**Comment by TommyLemon** [comment]
是这样，有时候就是一两行代码，甚至只是改个单词或者标点符号就解决了。
只是我实在时间精力有限，改完还得再回归测试、提交代码等。
所以小问题大家也可以帮忙提个 PR，有的问题我也会提供解决方案。
开源要大家一起参与贡献才会更美好~
![image](https://user-images.githubusercontent.com/5738175/172325029-b410d90f-0989-4aaa-865d-5a845aca2f1b.png)

https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%80%E5%AE%9A%E8%A6%81%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81
