### ISSUE TITLE
不支持 postgresql 的 date 字段格式时的类型转换

### ISSUE THREAD

**Issue by transtone** [Tencent/APIJSON#436]
使用如下查询时出错：
```json
{
	"data[]": {	
		"User": {        
			"birthday>=": "2022-08-28",
		},
        "format": true,
        "count": 3,
	},

}
```
```shell
org.postgresql.util.PSQLException: ERROR: operator does not exist: date >= character varying
  建议：No operator matches the given name and argument types. You might need to add explicit type casts.

```

==================

需要这样转换一下字段格式：
```json
{
	"data[]": {	
		"User": {        
			"birthday>=": "2022-08-28",
                        "@cast": "birthday>=:DATE",
		},
        "format": true,
        "count": 3,
	},

}
```

`Document.md` 文档中查不到，可以补上这个功能的文档。

**Comment by TommyLemon** [comment]
stringtype=unspecified 这样最省事，Demo 就提供了

https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONBoot/src/main/java/apijson/demo/DemoSQLConfig.java#L175
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/5738175/187483772-e0979d1e-dc29-44b1-95c8-ed8fbb3a946a.png">
