### ISSUE TITLE
APIJSON同时操作新增和修改时，在修改的请求体里面套新增的远程函数，其中修改可以成功，但是新增就提示‘未登录或登录过期，请登录后再操作’，怎么处理？在线等

### ISSUE THREAD

**Issue by AwenJackson** [Tencent/APIJSON#439]
运行前的数据：
![image](https://user-images.githubusercontent.com/95326431/187644715-9a9ddb73-bb94-4b50-957d-e55428aa2f99.png)
运行后的数据：
![image](https://user-images.githubusercontent.com/95326431/187644764-d44b9e05-b8e8-47ad-ac9b-94b70b646883.png)
远程函数java代码：
![image](https://user-images.githubusercontent.com/95326431/187644795-d909b566-4c86-40d8-bf96-48c8f441bc02.png)
远程函数日志：
[out_log.txt](https://github.com/Tencent/APIJSON/files/9460283/out_log.txt)
请求：
![image](https://user-images.githubusercontent.com/95326431/187645352-d61ba60c-5edd-4773-8ace-3af943e572ac.png)

--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------
我看了一下，session也没有问题，不知道为什么报错”登录过期“

**Comment by TommyLemon** [comment]
远程函数内不要调 Controller 方法，否则就额外创建了 Parser，不在一个事务里。
直接调 parser 方法就行了，判断 ! JSONResponse.isSuccess 就抛异常

**Comment by AwenJackson** [comment]
@TommyLemon 那如果一个远程函数里面需要同时运行新增修改删除方法，该怎么办

**Comment by TommyLemon** [comment]
支持，你试试不就知道了
