### ISSUE TITLE
一对多关联查询，副表数据为重复问题

### ISSUE THREAD

**Issue by liny1224** [Tencent/APIJSON#442]
问题：一对多关联查询，使用join。 查询结果副表全是重复数据。
<img width="511" alt="image" src="https://user-images.githubusercontent.com/54567105/188610075-c9c1490e-d36a-4bfe-b4e1-410188e32fac.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/54567105/188610546-f10bc752-c98d-4a98-9a2a-a459b0115f32.png">

**Comment by TommyLemon** [comment]
提问前先搜下现有的 issue
https://github.com/Tencent/APIJSON/issues/424

**Comment by TommyLemon** [comment]
@liny1224  已解决 SQL JOIN 在一对多或多对多时返回单独查询的重复副表数据，而不是 SQL 结果集里的副表数据。
（之前必须用 DISTINCT 或 ORDER BY 去重来解决，但可能去重后的结果不符合某些需求）

https://github.com/Tencent/APIJSON/commit/2f5d947de21664ce77d16c20ec8851cd3d76e1dd

<img width="1531" alt="Image" src="https://github.com/user-attachments/assets/bde77283-9d50-4ae4-a1c8-f34b4dd61b9f" />

https://apijson.cn/api/?send=true&type=JSON&url=http%3A%2F%2Flocalhost%3A8080%2Fget&json={%22[]%22:{%22count%22:3,%22join%22:%22%3C%2FComment%22,%22User%22:{%22@column%22:%22id%2Cname%22},%22Comment%22:{%22@column%22:%22id%2CuserId%22,%22userId@%22:%22%2FUser%2Fid%22}},%22@explain%22:true}
