### ISSUE TITLE
多表关联模糊查询时，查询条件顺序错乱bug

### ISSUE THREAD

**Issue by transtone** [Tencent/APIJSON#445]
**环境信息**

系统: Windows 10
JDK: 1.8.0_17
数据库: postgresql-12
APIJSON: 5.2.0
APIJSON-framework: 5.2.0
项目：https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server/APIJSONDemo-Druid 

**问题描述**

在使用临时表进行多表关联查询，执行如下sql时，查询条件的顺序会颠倒，导致查询报错。

```json
{
    "[]": {
        "Comment": {  
            "name$": "%a%",
            "content$": "%a%",
            "@combine": "name$,content$", 
            "@from@": {  
                "from": "Comment",
                "join": "&/User/id@",
                "Comment": {},
                "User": {
                    "id@": "/Comment/userId",
		    "sex": 1, // 这个条件会和全局条件相调换
                    "@column": "name,sex"  
                }
            }
        }
    },
    "@explain": true
}
```
执行时sql参数顺序乱了，`sex=1` 变成了 `sex=%a%`
![image](https://user-images.githubusercontent.com/46688/191498100-430c55d4-27c9-4411-aee7-ffb80f8bcd20.png)

**explain返回的sql是正确的**
![image](https://user-images.githubusercontent.com/46688/191440744-ce47482f-71c6-4f5f-b2ab-6c89f0716a60.png)

**Comment by transtone** [comment]
用官方测试站 http://apijson.cn:8080 (mysql?)测试，没有报错，但貌似返回结果错误：
![image](https://user-images.githubusercontent.com/46688/191152856-0ed2b7e7-1c5a-436d-a33e-b876b3751f38.png)

explain 里的 sql 稍作语法改造，放到pg控制台查询，是正常的：
![image](https://user-images.githubusercontent.com/46688/191153157-1bd17566-eb2e-40d8-844d-21e387be4018.png)

**Comment by transtone** [comment]
打断点单步发现，explain返回的执行sql是正确的，但执行时参数循序乱了。
![image](https://user-images.githubusercontent.com/46688/191439629-3daa8537-d50a-4631-ab06-38244069c230.png)

**Comment by TommyLemon** [comment]
升级到 5.2.0 试试
https://github.com/Tencent/APIJSON/releases/tag/5.2.0

**Comment by transtone** [comment]
已经升级过，当前版本是 apijson-framework-5.2.0

```xml
        <dependency>
            <groupId>com.github.APIJSON</groupId>
            <artifactId>apijson-framework</artifactId>
            <version>5.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.APIJSON</groupId>
            <artifactId>apijson-column</artifactId>
            <version>1.2.5</version>
        </dependency>
        <dependency>
            <groupId>com.github.APIJSON</groupId>
            <artifactId>apijson-router</artifactId>
            <version>1.0.5</version>
        </dependency>
```

![image](https://user-images.githubusercontent.com/46688/191497675-d743c291-0e1a-45e8-93c2-baee6a281ea0.png)

**Comment by TommyLemon** [comment]
有没有哪里单独指定了 APIJSON 5.1.5？

**Comment by transtone** [comment]
> 有没有哪里单独指定了 APIJSON 5.1.5？ apijson-framework 和 APIJSON 是两个项目

没有单独指定。是两个项目，但是apijson-framework 是需要引用 APIJSON 的， 
IDEA debug 的显示不会错的吧。是不是`APIJSON-5.2.0`针对

**Comment by TommyLemon** [comment]
这里得把 preparedValueList 反过来装
https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L4027-L4030

![image](https://user-images.githubusercontent.com/5738175/191499724-15f77829-dbc6-42e4-9dfb-3294ade6661f.png)

参考 concatJoinWhereString，先外查询 preparedValueList、子查询的 preparedValueList 取出来用一个变量暂存，然后清空，再用子查询的 subPreparedValueList.add(preparedValueList) 然后 setPreparedValueList
https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L2924-L3049
![image](https://user-images.githubusercontent.com/5738175/191500320-70decd09-b7da-4b48-856e-99e5cfb39965.png)

**Comment by transtone** [comment]
很抱歉，不会修。静待您的更新。
如果不是因为explain返回的sql是正确的，还发现不了这个问题。
还一度想添加一个接口，直接获取 `config.getSQL()` 的值，手动执行呢。

**Comment by transtone** [comment]
> 这里得把 preparedValueList 反过来装 https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L4027-L4030
> 
> 参考 concatJoinWhereString，先外查询 preparedValueList、子查询的 preparedValueList 取出来用一个变量暂存，然后清空，再用子查询的 subPreparedValueList.add(preparedValueList) 然后 setPreparedValueList https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L2924-L3049 


`getConditionString` 这个函数是反复调用的，也就是说 `getSubqueryString` 会执行多次，依据什么来判断当前条件包含外查询和子查询，并且需要反装呢？

**Comment by TommyLemon** [comment]
> > 这里得把 preparedValueList 反过来装 https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L4027-L4030
> > 参考 concatJoinWhereString，先外查询 preparedValueList、子查询的 preparedValueList 取出来用一个变量暂存，然后清空，再用子查询的 subPreparedValueList.add(preparedValueList) 然后 setPreparedValueList https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L2924-L3049
> 
> `getConditionString` 这个函数是反复调用的，也就是说 `getSubqueryString` 会执行多次，依据什么来判断当前条件包含外查询和子查询，并且需要反装呢？

getFrom 值不为 null 就一定是有 FROM(SELECT ...) 这种子查询，getSubqueryString 执行多次，其实是前端传参子查询数量的两倍，一倍用来生成完整 SQL，另一倍用来生成 WHERE id=? 这种预编译的 SQL。
具体见  getSQL(boolean prepared)

**Comment by TommyLemon** [comment]
> 很抱歉，不会修。静待您的更新。 如果不是因为explain返回的sql是正确的，还发现不了这个问题。 还一度想添加一个接口，直接获取 `config.getSQL()` 的值，手动执行呢。

取两个列表、合并两个列表、设置两个列表，也就 5 行代码

**Comment by transtone** [comment]
>getSubqueryString 执行多次，其实是前端传参子查询数量的两倍，一倍用来生成完整 SQL，另一倍用来生成 WHERE id=? 这种预编译的 SQL，具体见 getSQL(boolean prepared)

总得区分是否预编译吧，在预编译的最后一遍的时候，来做这个校正操作是最合适的，但怎么判断这个条件，还在折腾。

>取两个列表、合并两个列表、设置两个列表，也就 5 行代码

对熟悉java的人很简单。生手只能F7/F8慢慢摸索，还不知道改了源码之后怎么调试呢。
唉，项目着急用，5行代码又不会写，折腾两周了...  赶鸭子上架继续折腾ing

**Comment by transtone** [comment]
正在做一个前端用的查询组件，配置好表、字段、关联关系之后自动生成报表。单表查询没任何问题，但在多表模糊查询这块用不了了，卡着不能上线。
![image](https://user-images.githubusercontent.com/46688/193294070-aece810e-4f7e-439b-a269-d4c3e3d3814b.png)
有哪位关心APIJSON的高手看到了能顺手帮帮吗，感激不尽。
表格项目内部使用没问题后，会第一时间公开给大家试用，也算是apijson的一个前端配套表格工具吧。

**Comment by gxmanito** [comment]
> > > 这里得把 preparedValueList 反过来装 https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L4027-L4030
> > > 参考 concatJoinWhereString，先外查询 preparedValueList、子查询的 preparedValueList 取出来用一个变量暂存，然后清空，再用子查询的 subPreparedValueList.add(preparedValueList) 然后 setPreparedValueList https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L2924-L3049
> > 
> > 
> > `getConditionString` 这个函数是反复调用的，也就是说 `getSubqueryString` 会执行多次，依据什么来判断当前条件包含外查询和子查询，并且需要反装呢？
> 
> getFrom 值不为 null 就一定是有 FROM(SELECT ...) 这种子查询， getSubqueryString 执行多次，其实是前端传参子查询数量的两倍，一倍用来生成完整 SQL，另一倍用来生成 WHERE id=? 这种预编译的 SQL，具体见 getSQL(boolean prepared)

6.3.0版本，List<Object> subPvl = cfg.getPreparedValueList()一直是空集合，导致最终No value specified for parameter 4

**Comment by TommyLemon** [comment]
> > > > 这里得把 preparedValueList 反过来装 https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L4027-L4030
> > > > 参考 concatJoinWhereString，先外查询 preparedValueList、子查询的 preparedValueList 取出来用一个变量暂存，然后清空，再用子查询的 subPreparedValueList.add(preparedValueList) 然后 setPreparedValueList https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L2924-L3049
> > > 
> > > 
> > > `getConditionString` 这个函数是反复调用的，也就是说 `getSubqueryString` 会执行多次，依据什么来判断当前条件包含外查询和子查询，并且需要反装呢？
> > 
> > 
> > getFrom 值不为 null 就一定是有 FROM(SELECT ...) 这种子查询， getSubqueryString 执行多次，其实是前端传参子查询数量的两倍，一倍用来生成完整 SQL，另一倍用来生成 WHERE id=? 这种预编译的 SQL，具体见 getSQL(boolean prepared)
> 
> 6.3.0版本，List subPvl = cfg.getPreparedValueList()一直是空集合，导致最终No value specified for parameter 4

@gxmanito 升级 6.4+ 或 7.0.3 试试。还不行的话麻烦提供详细信息，方便排查问题

**Comment by gxmanito** [comment]
项目使用的是springboot2.x和jdk8，升级6.4+ 或 7.0.3 会向下兼容吗？

**Comment by TommyLemon** [comment]
@gxmanito 
升级到 6.4+ 后只支持 JDK 17+ 的版本，7.0+ 兼容  SpringBoot2 但 JDK 也必须是 17+

JOIN 带条件有占位符错误问题，我们再排查下

**Comment by TommyLemon** [comment]
官网 7.0.3 试了未复现
<img width="1531" alt="image" src="https://github.com/user-attachments/assets/dd471d45-ff83-41d5-b9df-ae77823f1341">
http://apijson.cn/api/?send=true&type=JSON&url=http%3A%2F%2Fapijson.cn%3A8080%2Fget&json={%22[]%22:{%22join%22:%22%26%2FUser%2C%40%2FComment%2C%3C%2FPraise%22,%22Moment%22:{%22content~%22:%22a%22,%22@column%22:%22id%2CuserId%2Ccontent%22},%22User%22:{%22sex{}%22:[1,0],%22@column%22:%22id%2Cname%22,%22id@%22:%22%2FMoment%2FuserId%22},%22Comment%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22date%3E%22:%222019-02-17%2000%3A00%3A00%22,%22@column%22:%22id%2CmomentId%2Ccontent%22},%22Praise%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22userId!%22:0}},%22@explain%22:true}


<img width="1531" alt="image" src="https://github.com/user-attachments/assets/d019da89-b5d7-4012-870f-fafefc66d578">

http://apijson.cn/api/?send=true&type=JSON&url=http%3A%2F%2Fapijson.cn%3A8080%2Fget&json={%22[]%22:{%22join%22:%22%26%2FUser%2C%40%2FComment%2C%3E%2FPraise%22,%22Moment%22:{%22content~%22:%22a%22,%22@column%22:%22id%2CuserId%2Ccontent%22},%22User%22:{%22sex{}%22:[1,0],%22@column%22:%22id%2Cname%22,%22id@%22:%22%2FMoment%2FuserId%22},%22Comment%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22date%3E%22:%222019-02-17%2000%3A00%3A00%22,%22@column%22:%22id%2CmomentId%2Ccontent%22},%22Praise%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22userId!%22:0}},%22@explain%22:true}

**Comment by gxmanito** [comment]
https://github.com/Tencent/APIJSON/issues/445#issuecomment-2254497266
可以试试两张表inner join且都有模糊查询，其中一张子表既有inner还有left join

**Comment by gxmanito** [comment]
https://github.com/Tencent/APIJSON/issues/445#issuecomment-2246965729
另针对这个情况是这样复现的，当开启ENABLE_WITH_AS = true;   且子查询有where条件时，会报此错误No value specified for parameter 2
![image](https://github.com/user-attachments/assets/049c5e6c-bb95-46ba-945c-fbc2d5286fdd)

不加where不会报错
![image](https://github.com/user-attachments/assets/227c0ece-3c6d-4fa4-893b-ae6b6a852c02)

**Comment by TommyLemon** [comment]
WITH AS 确实有这个问题，可以先关掉，只是对性能有点影响

**Comment by TommyLemon** [comment]
@gxmanito  改用刚发布的 7.0.3-jdk1.8.0 试试，如果有用到 apijson-framework，必须 6.3.0+，并且排除它依赖的 APIJSON ORM， apijson-column, apijson-router 都只能用 1.8.0+，并且排除它们依赖的 APIJSON ORM
```xml
        <dependency>
            <groupId>com.github.Tencent</groupId>
            <artifactId>APIJSON</artifactId>
            <version>7.0.3-jdk1.8.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.APIJSON</groupId>
            <artifactId>apijson-framework</artifactId>
            <version>6.3.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.github.Tencent</groupId>
                    <artifactId>APIJSON</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.APIJSON</groupId>
            <artifactId>apijson-column</artifactId>
            <version>1.8.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.github.Tencent</groupId>
                    <artifactId>APIJSON</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.APIJSON</groupId>
            <artifactId>apijson-router</artifactId>
            <version>1.8.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.github.Tencent</groupId>
                    <artifactId>APIJSON</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by TommyLemon** [comment]
[Uploading APIJSONBoot-MultiDataSource-jdk1.8-springboot2.5.zip…]()

**Comment by TommyLemon** [comment]
[APIJSONBoot-MultiDataSource-jdk1.8-springboot2.5.zip](https://github.com/user-attachments/files/16404335/APIJSONBoot-MultiDataSource-jdk1.8-springboot2.5.zip)

**Comment by TommyLemon** [comment]
复现了：
<img width="1531" alt="image" src="https://github.com/user-attachments/assets/1c8b5da0-2a14-41bb-898b-5738a323b4e4">


http://apijson.cn/api/?send=true&type=JSON&url=http%3A%2F%2Fapijson.cn%3A8080%2Fget&json={%22[]%22:{%22join%22:%22%26%2FUser%2C%26%2FPraise%2C%3C%2FComment%2C%3C%2FComment%3Ato%22,%22Moment%22:{%22content$%22:%22%25a%25%22,%22@column%22:%22id%2CuserId%2Ccontent%22},%22User%22:{%22sex%22:0,%22@column%22:%22id%2Cname%22,%22id@%22:%22%2FMoment%2FuserId%22},%22Praise%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22userId!%22:0},%22Comment%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22date$%22:%22%2520%25%22,%22@column%22:%22id%2CmomentId%2Ccontent%22},%22Comment:to%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22toId!%22:0,%22@column%22:%22id%2CtoId%2CmomentId%2Ccontent%22}},%22@explain%22:true}

删除第一个 INNER JOIN 对应表里的条件可以正常返回结果：

<img width="1531" alt="image" src="https://github.com/user-attachments/assets/91204775-c1f1-4f5f-adcc-7cc0dfa4c474">

http://apijson.cn/api/?send=false&type=JSON&url=http%3A%2F%2Fapijson.cn%3A8080%2Fget&json={%22[]%22:{%22join%22:%22%26%2FUser%2C%26%2FPraise%2C%3C%2FComment%2C%3C%2FComment%3Ato%22,%22Moment%22:{%22content$%22:%22%25a%25%22,%22@column%22:%22id%2CuserId%2Ccontent%22},%22User%22:{%22@column%22:%22id%2Cname%22,%22id@%22:%22%2FMoment%2FuserId%22},%22Praise%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22userId!%22:0},%22Comment%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22date$%22:%22%2520%25%22,%22@column%22:%22id%2CmomentId%2Ccontent%22},%22Comment:to%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22toId!%22:0,%22@column%22:%22id%2CtoId%2CmomentId%2Ccontent%22}},%22@explain%22:true}

这个得继续排查是 AbstractSQLConfig 哪步出错的。
每个条件最后都会调用  getValue，里面 preparedValueList.add(value) 发生在同步拼接 JOIN SQL 片段时候
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/d314e9a3-b622-48a9-bf63-8ccc14940b75">

可能 getJoinString 对 LEFT/RIGHT 等 OUTER JOIN 处理条件时清空现有副表的 preparedValueList，然后加到主表，这块有问题
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/c34e134c-494c-4a4c-9b19-2fb32ce4e5bf">

<img width="1532" alt="image" src="https://github.com/user-attachments/assets/6bed1583-dac5-4ad1-ba9c-c9f9b59747d5">

<img width="1532" alt="image" src="https://github.com/user-attachments/assets/9048169c-fe09-43a3-8f28-b596dc8006e3">

**Comment by TommyLemon** [comment]
临时解决方法是把带条件的 LEFT JOIN 都改成 APP JOIN
<img width="1531" alt="image" src="https://github.com/user-attachments/assets/ac45dd60-332b-43b3-97d1-3e62972fdbaf">

http://apijson.cn/api/?send=true&type=JSON&url=http%3A%2F%2Fapijson.cn%3A8080%2Fget&json={%22[]%22:{%22join%22:%22%26%2FUser%2C%26%2FPraise%2C%40%2FComment%2C%40%2FComment%3Ato%22,%22Moment%22:{%22@column%22:%22id%2CuserId%2Ccontent%22,%22content$%22:%22%25a%25%22},%22User%22:{%22id@%22:%22%2FMoment%2FuserId%22,%22@column%22:%22id%2Cname%22,%22sex%22:0},%22Praise%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22userId%3E%22:82001},%22Comment%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22@column%22:%22id%2CmomentId%2Ccontent%22,%22date$%22:%22%2520%25%22},%22Comment:to%22:{%22momentId@%22:%22%2FMoment%2Fid%22,%22@column%22:%22id%2CtoId%2CmomentId%2Ccontent%22,%22toId!%22:0}},%22@explain%22:true}
