### ISSUE TITLE
关于update操作 去掉id后，如何增加字符类型的where条件

### ISSUE THREAD

**Issue by wanghongfeng** [Tencent/APIJSON#446]
你好，
    数据建模过程中，id不一定是主键，所以我解除了主键id的默认项，可能存在其他varchar类型的字段作为主键
新增是没有问题的，确定传主键即可
可修改就会出问题，主键是varchar类型，请问如何处理呢？

我提交的是
{
    "Newtable": {
        "column1": "1",
        "column1{}": "='1'"
    },
    "@database": "POSTGRESQL",
    "@schema": "sys"
}
会报错，报特殊字符
那如何是字符类型该如何作为条件呢？

![image](https://user-images.githubusercontent.com/9864409/191671049-29243b59-f2ea-4ae7-832e-5202001ec790.png)

 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.lang.UnsupportedOperationException: column1{}:value 的 value 中 ='1' 不合法！预编译模式下 key{}:"condition" 中 condition 必须 为 =null 或 !=null 或 符合正则表达式 ^[0-9%,!=\<\>/\.\+\-\*\^]+$ ！不允许连续减号 -- ！不允许空格！       ---|-----APIJSON SYSTEM INFO-----|---       
 **环境信息**  
 系统: Windows 10 10.0 
 数据库: POSTGRESQL 11.5 
 JDK: 14.0.2 amd64 
 APIJSON: 5.2.0
AbstractParser.DEBUG: <<<<<<<<<<<<<<<<<<<<<<< rollback >>>>>>>>>>>>>>>>>>>>>>> 

**问题描述**

AbstractSQLConfig类中验证不合法字符中就会把where条件下的字符类型判断为非法字符

else if (isPrepared() && (c.contains("--") || PATTERN_RANGE.matcher(c).matches() == false)) {
throw new UnsupportedOperationException(key + ":value 的 value 中 " + c + " 不合法！"
		+ "预编译模式下 key{}:\"condition\" 中 condition 必须 为 =null 或 !=null 或 符合正则表达式 " + PATTERN_RANGE + " ！不允许连续减号 -- ！不允许空格！");
}

**Comment by TommyLemon** [comment]
“id不一定是主键，所以我解除了主键id的默认项，可能存在其他varchar类型的字段作为主键”
主键名可以改，类型也可以为 String，具体看常见问题。

```java
"column1{}": "=\"safa\""
```
为什么写成这样？通用文档已明确说明等价条件直接用
```java
"key": value
```
形式，你写成
```
"column1": 'safa'
```
或用 IN
```
"column1{}": ['safa']
```
不就行了？

多看文档和常见问题，以后这种明显是因为没看过文档/常见问题的简单问题不再回复，直接关 issue

**Comment by wanghongfeng** [comment]
多谢，多谢
in的方式"column1{}": ["safa"]是可以的
你确定 "column1{}": "=\"safa\""不会报非法字符？"column1": "safa"是真的可以作为where？

**Comment by TommyLemon** [comment]
"column1": "safa" 可以，自己试试不就知道了
