### ISSUE TITLE
 jitpack.io 5.1.5貌似构建失败了缺少文件。只有build.log

### ISSUE THREAD

**Issue by bullhe4d** [Tencent/APIJSON#453]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/20084624/196343388-1b46aa70-da49-4102-b74c-ab87976975d0.png">

5.1.5版本
<img width="634" alt="image" src="https://user-images.githubusercontent.com/20084624/196343504-1a22ec93-0a5e-403a-ad26-9b03163dad2f.png">
正常版本
<img width="693" alt="image" src="https://user-images.githubusercontent.com/20084624/196343552-8453f292-7fc7-4ac8-8e07-0c8909f24b7a.png">

**Comment by TommyLemon** [comment]
感谢反馈，是有问题。建议不要用这个旧版本的远程依赖，可以直接用 jar 包依赖，但目前最推荐最新版 5.3.0
https://github.com/Tencent/APIJSON/releases
