### ISSUE TITLE
MySQL高版本当执行拼接出来的SQL语句带有group by时，select的字段不属于group by的字段的话，报错this is incompatible with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by Willdas** [Tencent/APIJSON#457]
APIJSON版本号：5.3.0
MySQL版本号：8.0.20

1、JSON示例：
{
    "[]": {
        "count": 5,
        "join": "&/User/id@,</Comment",
        "Moment": {
            "@column": "id,userId,content",
            "@group": "id"
        },
        "User": {
            "name~": "t",
            "id@": "/Moment/userId",
            "@column": "id,name,head"
        },
        "Comment": {
            "momentId@": "/Moment/id",
            "@column": "id,momentId,content"
        }
    },
    "@explain": true
}
2、拼接的SQL:
SELECT
    `Moment`.`id`,
    `Moment`.`userId`,
    `Moment`.`content`,
    `User`.`id`,
    `User`.`name`,
    `User`.`head`,
    `Comment`.* 
FROM
    `sys`.`Moment` AS `Moment`
    INNER JOIN `sys`.`apijson_user` AS `User` ON `User`.`id` = `Moment`.`userId`
    LEFT JOIN ( SELECT `id`, `momentId`, `content` FROM `sys`.`Comment` ) AS `Comment` ON `Comment`.`momentId` = `Moment`.`id` 
WHERE
    (
        ( ( ( `User`.`name` REGEXP BINARY 't' ) ) ) 
    ) 
GROUP BY
    `Moment`.`id` 
    LIMIT 5
3、错误提示：
1055 - Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'Comment.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by, Time: 0.000000s
4、解决方式：
4-1：使用函数ANY_VALUE()包含报错字段
4-2：修改配置my.cnf文件(Linux)，找到sql-mode的位置，去掉ONLY_FULL_GROUP_BY

**Comment by TommyLemon** [comment]
就按 4、解决方式 来
