### ISSUE TITLE
column中使用if判断问题

### ISSUE THREAD

**Issue by yangSpica27** [Tencent/APIJSON#458]
![企业微信截图_16674458094085](https://user-images.githubusercontent.com/38589186/199642107-857da0b6-9e24-4112-936b-41ba40ad3d05.png)

**Comment by TommyLemon** [comment]
StringUtil.isName("status>3") == false 判断不是字段，所以被当成了值处理
可以通过 @raw 和空格来解决
```json
"@column":"if(status > 3,3,2)",
"@raw": "@column"
```
见 见通用文档 3.设计规范>3.2 功能符
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.1
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/5738175/199659380-0aaba9b6-19f8-4d8e-96bb-0dc0c9e30623.png">

**Comment by yangSpica27** [comment]
谢谢解答
