### ISSUE TITLE
参考通用文档里面的Demo 获取用户列表返回结果不正确出现404

### ISSUE THREAD

**Issue by Phosphor-zhl** [Tencent/APIJSON#460]
![image](https://user-images.githubusercontent.com/17038799/200095599-52def667-b96d-48e3-8d63-1a3223cf6199.png)

**Comment by TommyLemon** [comment]
请先打好基础，APIJSON 使用门槛虽然低但也有最基本的要求，连 HTTP 端口都不知道就先不要用 APIJSON 
https://baike.baidu.com/item/%E7%BD%91%E7%BB%9C%E7%AB%AF%E5%8F%A3/792237

**Comment by Phosphor-zhl** [comment]
谢谢! 漏掉了端口
