### ISSUE TITLE
控制查询结果 reponse key是否显示

### ISSUE THREAD

**Issue by cloudAndMonkey** [Tencent/APIJSON#466]
实现方式两种:
1、临时变量方式
2、远程函数
参见后面评论
版本:5.2.0
实现思路:
1、查询传递临时变量
2、返回结果之前进行处理
并没有在添加数据的地方进行处理,太琐碎了,所以如果框架直接支持最好,哈哈
应用场景:
1、json模版化
2、用户端查询不关心apijson,只传递参数
3、尽量通过别名、合并结果集、删除无关返回字段 减轻用户端前端工作量
实现流程:
json格式如下:
{
	"@show_reponse": true,
	//"@show_reponse_keys": "func,data",
	//"@show_reponse_exclude_keys": "func,tag",
    "func": {
        "id()": "getCurrentUserId()"
    },
    "User:data": {
        "id@": "/func/id"
    },
    "tag": "User",
    "@explain": true
}
AbstractParser.java parseResponse方法
你可以自己继承
![image](https://user-images.githubusercontent.com/12228225/201043440-1f90756c-ec23-4538-82da-5b5579632d9e.png)

**Comment by TommyLemon** [comment]
赞，感谢分享。
另外也可以通过远程函数来实现。
```json
{
  "rmv()":"removeKey(func)",
  "rmv2()":"removeKey(tag)"  // 一般 tag 不会返回
}
```
还可以实现一个自定义远程函数
```java
public void removeKeys(@NotNull JSONObject current, String keys) {
  String[] ks = StringUtil.split(keys, ";");  // 用分号 ;  分割
  //TODO 根据 ks remove 掉 current 里的字段
}
```
前端调用
```json
{
  "rmv()":"removeKey(func;tag)"
}
```

**Comment by cloudAndMonkey** [comment]
是的, 远程函数更合理和方便, 当时想熟悉一下临时变量,如何解决不同请求类型
我改一下

**Comment by cloudAndMonkey** [comment]
远程函数实现:
添加远程函数:
public void removeKeys(@NotNull JSONObject current, String keys) {
		String[] ks = StringUtil.split(keys, ";"); // 用分号 ; 分割
		// 根据 ks remove 掉 current 里的字段
		for (int i = 0; i < ks.length; i++) {
			current.remove(ks[i]);
		}
	}
配置数据库 Function:
![image](https://user-images.githubusercontent.com/12228225/201250192-8fe44999-4882-4ee1-99ef-7786595b882f.png)
postman:
{
	"id@-()": "getCurrentUserId()",
    "User[]": {
        "User": {
            "@from@": {
                "from": "User_address",
                "join": "&/User/id@",
                "User_address": {
                	"user_id@": "id",
                    "@column": "id:addr_id,user_id,addr"
                },
                "User": {
                   "id@": "/User_address/user_id",
                   "@column": "id,username"
                }
            }
        }
    },
    "rmv()": "removeKeys(tag;id;rmv)",
    "@explain": true
}
返回结果前后对比:
![image](https://user-images.githubusercontent.com/12228225/201250260-8c549752-15d6-4bc9-827d-be783fbf3fb7.png)

**Comment by TommyLemon** [comment]
应该不需要传 rmv，因为远程函数返回类型为 void 或者 return null，最终都不会返回这个键值对
