### ISSUE TITLE
线上用了用了快一年得服务，现在突然提示不允许 UNKNOWN 用户的 HEAD 请求！

### ISSUE THREAD

**Issue by 12345ZMTHL** [Tencent/APIJSON#469]
去年起的APIJSON服务，今天线上突然提示不允许 UNKNOWN 用户的 HEAD 请求！查看access表啥得都是有配置得，当时表权限配置得就是不需要登录就能，现在APIJSON相关得东西忘得差不多了，根本无从下手，拉代码本地起服务unitauto-jar2.6.3也从maven仓库中移除，变成2.7.2
![image](https://user-images.githubusercontent.com/46614808/201599882-7919e027-c0f4-4bfb-b276-2613fec7c6c3.png)
![image](https://user-images.githubusercontent.com/46614808/201599946-2cfe6c73-ef5b-451a-ba1e-87e86540ef49.png)
![image](https://user-images.githubusercontent.com/46614808/201599599-681bd4a1-f3c9-4a4b-9f1b-4d05e80b1124.png)

**Comment by TommyLemon** [comment]
<img width="90" alt="image" src="https://user-images.githubusercontent.com/5738175/201873156-d32b5c2e-72fe-4d15-a004-5b60115013a0.png">

**Comment by 12345ZMTHL** [comment]
> <img alt="image" width="90" src="https://user-images.githubusercontent.com/5738175/201873156-d32b5c2e-72fe-4d15-a004-5b60115013a0.png">

jar包问题昨天下午已经解决，启动又提示MySQL查询数据包过大啥的异常，可能是对MySQL8有点不兼容吧，这个服务是一年前部署的当时数据库用的MySQL5，前段时间数据库迁移到MySQL8了，其他配置不变，昨天线上就突然提示不允许UNKNOWN 用户的HEAD请求。然后就去看文档、看数据库、看issues都没找到问题原因，没办法就把调用APIJSON的地方用Java重写了.......

**Comment by TommyLemon** [comment]
应该是你设置的数据库配置不兼容，URI 少了 serverTimezone, useUnicode 等参数
jdbc:mysql://localhost:3306?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8

https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONDemo/src/main/java/apijson/demo/DemoSQLConfig.java#L50-L54

**Comment by 12345ZMTHL** [comment]
> > > <img alt="image" width="90" src="https://user-images.githubusercontent.com/5738175/201873156-d32b5c2e-72fe-4d15-a004-5b60115013a0.png">
> > 
> > 
> > jar包问题昨天下午已经解决，启动又提示MySQL查询数据包过大啥的异常，可能是对MySQL8有点不兼容吧，这个服务是一年前部署的当时数据库用的MySQL5，前段时间数据库迁移到MySQL8了，其他配置不变，昨天线上就突然提示不允许UNKNOWN 用户的HEAD请求。然后就去看文档、看数据库、看issues都没找到问题原因，没办法就把调用APIJSON的地方用Java重写了.......
> 
> @12345ZMTHL 应该是你设置的数据库配置不兼容，URI 少了 userSSL, serverTimezone, useUnicode 等参数 jdbc:mysql://localhost:3306?userSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
> 
> https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONBoot/src/main/java/apijson/demo/DemoSQLConfig.java#L169-L173

感谢感谢，不是少了userSSL, serverTimezone, useUnicode，而是我数据库配置改错地方了，当时迁库是在application.yml中改新的数据库链接，但是实际application.yml中配置的是使用多数据源，APIJSON需要的库是在SQLConfig这个Java类中修改的，因为时间有点久了给忘记了。还有一点就是给的错误提示不是很友好，因为之前的数据库已经停止使用了，按理说给的错误信息应该是数据库连接失败，但实际给的是 Packet for query is too large (5,526,600 > 65,535)，第一时间不会让人觉得是数据库连接问题
![image](https://user-images.githubusercontent.com/46614808/202072524-93c39c36-01ee-4a71-a6bd-2f6f56239557.png)
![image](https://user-images.githubusercontent.com/46614808/202074036-f769ada9-b7bb-41c4-a740-43126d9b6dc4.png)

**Comment by TommyLemon** [comment]
适配连接池需要重写 AbstractSQLExecutor.getConnection
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONBoot/src/main/java/apijson/demo/DemoSQLExecutor.java#L50-L69

**Comment by 12345ZMTHL** [comment]
> 

嗯嗯，感谢感谢
