### ISSUE TITLE
数据库字段数据为null时，返回json报文没有包含这个字段

### ISSUE THREAD

**Issue by ikenneth** [Tencent/APIJSON#486]
### APIJSON Version/APIJSON 版本号

5.4.0

### Database Type & Version/数据库类型及版本号

MySQL 5.7.35

### Environment/环境信息

```markdown
- JDK/基础库:1.8.0_17
- OS/系统:MacOS Monterey 12.6 (21G115) M1
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

<img width="855" alt="image" src="https://user-images.githubusercontent.com/7484551/205856900-a98c8ebd-1f56-40b5-b6b0-3647dbf1fc84.png">

### Current Behavior/问题描述

```markdown
数据库字段数据为null时，返回json报文没有包含这个字段，
前端使用需要判断比较麻烦，
这个怎么配置才能查的数据为null返回字段名:null呢？
```

### Expected Behavior/期望结果

字段名:null

**Comment by TommyLemon** [comment]
```js
"@column:":"ifnull(key,'')"
```

**Comment by cloudAndMonkey** [comment]
@TommyLemon 
管理系统偷懒, 确实有这个需求, 前端不用每个字段去判断, 如果想框架层面解决, 需要处理两个地方:

![image](https://user-images.githubusercontent.com/12228225/221865385-076b31ad-6cb7-4047-917e-0b5daa574f00.png)


https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractParser.java#LL363
改成:
```java
return JSON.toJSONString(parseResponse(request), SerializerFeature.WriteMapNullValue);
```
