### ISSUE TITLE
ElasticSearch什么时候可以支持？可以支持原生的ElasticSearch语法查询吗？

### ISSUE THREAD

**Issue by SalomonQiu** [Tencent/APIJSON#496]
### Description

ElasticSearch什么时候可以支持？可以支持原生的ElasticSearch语法查询吗？

**Comment by cloudAndMonkey** [comment]
https://github.com/cloudAndMonkey/APIJSON-Demo/tree/master/APIJSON-Java-Server/APIJSONDemo-Elasticsearch
![image](https://user-images.githubusercontent.com/12228225/212001826-61116180-683c-4316-9d6a-2d8a503b56d2.png)
![image](https://user-images.githubusercontent.com/12228225/212001844-ea9041e2-88dc-4f5b-a045-cbe1621ef7c5.png)
![image](https://user-images.githubusercontent.com/12228225/212001868-d1aed240-4504-477b-8772-f616512e2d54.png)
![image](https://user-images.githubusercontent.com/12228225/212001892-1c3382eb-a207-445e-9561-2d7fc9fed1aa.png)

![image](https://user-images.githubusercontent.com/12228225/212001907-bd6a1f8f-5bd1-4029-89a8-32412f7d02e8.png)
![image](https://user-images.githubusercontent.com/12228225/212001927-c4aef64c-06e6-4184-9b9f-f636487563f8.png)

**Comment by TommyLemon** [comment]
还有 @cloudAndMonkey 贡献的
https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server/APIJSONDemo-MultiDataSource-Elasticsearch

文档更全 👍
