### ISSUE TITLE
如何定义json请求参数,来删除2个以上关联表的数据

### ISSUE THREAD

**Issue by zhonghuali** [Tencent/APIJSON#511]
### Description

APIJSON,自带的用户表,user , privacy, 是关联表. 
我可以通过以下的创请求:
http://localhost:8088/post

{
    "User":{
        "name":"test01"
    },
    "Privacy":{
        "id@":"/User/id",
        "phone":"18888888112",
        "_password":"123456"        
    }
}
能够成功分别在2个表里创建记录,并且ID的值是一样的.

但我却没有成功一起删除他们,我尝试过各种请求格式,没有成功
比如:
http://localhost:8088/delete
{
    "User":{
        "name":"test01",
        "@column":"id"
    },
    "Privacy":{
        "id":"/User/id"     
    }    
}
只删除User表的数据, privacy表对应ID的数据没有删除
请问,如何一个请求参数,来删除关联表里的关联数据?

谢谢

**Comment by TommyLemon** [comment]
自己粗心写错了，提 issue 还不规范
https://github.com/Tencent/APIJSON/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml&title=%5BBug%5D+
