### ISSUE TITLE
[Bug] Demo项目多表插入报错

### ISSUE THREAD

**Issue by aldag** [Tencent/APIJSON#512]
### APIJSON Version/APIJSON 版本号

6.0.0

### Database Type & Version/数据库类型及版本号

mysql 5.7.38

### Environment/环境信息

```markdown
- JDK/基础库: 1.8.0_202
- OS/系统: win10
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

![](https://raw.githubusercontent.com/aldag/pic/main/Quicker_20230216_112429.png)

### Current Behavior/问题描述

```markdown
6.0.0版APIJSON-Demo项目多表插入报错，如截图中的register用例。
APIJSON-Demo项目除数据库连接外，未做其他代码修改；数据库中的Request表等关键表未做修改。
```

**Comment by TommyLemon** [comment]
是个 bug，我这边复现了，改用 5.4.0 以下试试
https://github.com/APIJSON/APIJSON-Demo/releases

**Comment by cloudAndMonkey** [comment]
@aldag 
你可以使用APIJSON全能接口 crud, 校验调用远程函数, 能实现一样的效果
crud: 
相同数据源,不同语句 支持事物
支持校验apijson校验
{
	"@datasource": "master",
	"@post": {
		"Access": {
			 "tag": "Access"
		},
		"Request[]": {
			 "tag": "Request[]"
		}
	},
    "Access": {
        "name": "Iinterface_list",
         "get": "[\"OWNER\", \"ADMIN\",\"LOGIN\"]",
                "head": "[\"OWNER\", \"ADMIN\",\"LOGIN\"]",
                "gets": "[\"OWNER\", \"ADMIN\",\"LOGIN\"]",
                "heads": "[\"OWNER\", \"ADMIN\",\"LOGIN\"]",
                "post": "[\"OWNER\", \"ADMIN\",\"LOGIN\"]",
                "put": "[\"OWNER\", \"ADMIN\",\"LOGIN\"]",
                "delete": "[\"OWNER\", \"ADMIN\",\"LOGIN\"]",
        "detail": "接口表"
    },
     "Request[]": [
        {
          "method": "POST",
          "tag": "Iinterface_list",
          "structure": "{\"MUST\": \"name,url,method,appId\", \"UPDATE\": {\"@role\": \"OWNER\"}, \"REFUSE\": \"id\"}",
          "detail": "新增"
        },
        {
          "method": "POST",
          "tag": "Iinterface_list[]",
          "structure": "{\"Iinterface_list[]\": [{\"MUST\": \"name,url,method,appId\", \"REFUSE\": \"id\"}], \"UPDATE\": {\"@role\": \"OWNER,ADMIN\"}}",
          "detail": "批量新增"
        },
        {
          "method": "PUT",
          "tag": "Iinterface_list",
          "structure": "{\"Iinterface_list\":{ \"MUST\":\"id\",\"REFUSE\": \"userId\", \"UPDATE\": {\"@role\": \"OWNER,ADMIN\"}} }",
          "detail": "修改"
        },
        {
          "method": "DELETE",
          "tag": "Iinterface_list",
          "structure": "{\"Iinterface_list\":{ \"MUST\":\"id\",\"REFUSE\": \"!\", \"INSERT\": {\"@role\": \"OWNER,ADMIN\"}} }",
          "detail": "批量删除"
        }
      ],
    "@explain": true
}

**Comment by TommyLemon** [comment]
> 版本6.0.0的APIJSON 您好：这种格式的请求现在不适配了吗 ![123123123](https://user-images.githubusercontent.com/28621460/231428666-deaaedc4-024c-481c-aac9-7bd1aa6b400c.png) ![2222222](https://user-images.githubusercontent.com/28621460/231428694-5f749ebf-7ec9-4152-a9f8-6cc5004f58f8.png) 我看每个子json都是单独解析的 ![333331](https://user-images.githubusercontent.com/28621460/231429601-b4555aa9-cdc0-4ee7-bbf6-710fdc4bdbd5.png)

这里不应该只 requestItem.put(_key, obj)，丢了 "Request":{} 对象导致 objectVerify 抛异常，
应该把原始请求的所有键值对 put 进去，可以 requestItem.putAll(原来的 request 对象)。

可以改下源码试试，如果可以麻烦提 PR 贡献下代码哦，开源要大家一起参与贡献才会更美好~
https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md

<img width="1531" alt="image" src="https://user-images.githubusercontent.com/5738175/231439447-9b192da3-2a1b-4c16-8920-c967b42f7ccc.png">

**Comment by wahowaho** [comment]
您好 我提交了一个修正  #545   
![image](https://user-images.githubusercontent.com/28621460/231677775-4eee54a7-532f-450b-bb60-34991ed0005f.png)
测试了一下双标插入，还有双标查询，还有crud的相关功能，没发现啥问题 。大佬有空看看。
![555555](https://user-images.githubusercontent.com/28621460/231677972-1a215c46-f562-4532-ada5-49516a6f5aae.png)
不能直接修正 requestItem.putAll(原来的 request 对象) ，他这个是循环校验每个，第二次进去会报错。

**Comment by wahowaho** [comment]
试了一下联合插入 
![6666](https://user-images.githubusercontent.com/28621460/231680946-199c5ce4-1454-43bf-b3fb-0edb662b3b16.png)
您那边看看这么改可以不。

**Comment by cloudAndMonkey** [comment]
@wahowaho 
你好, pr已经看到, 感谢贡献
vertify 方法需要兼容 crud全能接口和 post等method.
按照@TommyLemon  的意思, 别名不做提前 解析, 通过 Request structure 配置解决
https://github.com/Tencent/APIJSON/issues/468#issuecomment-1506346126
删除  tag 、JSONObject 别名判断的代码, 或者把crud 和其他 method区别处理, 我晚上测一下

**Comment by TommyLemon** [comment]
@cloudAndMonkey  @aldag @wahowaho 
6.1.0 已发布，解决了多表同时增删改的 bug 等问题；新增支持 Snowflake,Databricks,Cassandra；增强条件组合、参数校验等：
https://github.com/Tencent/APIJSON/releases/tag/6.1.0
https://github.com/APIJSON/apijson-framework/releases/tag/6.1.0
https://github.com/APIJSON/apijson-router/releases/tag/1.6.0
https://github.com/APIJSON/apijson-column/releases/tag/1.6.0
