### ISSUE TITLE
6.0.0版本APIJSONDemo带login功能吗

### ISSUE THREAD

**Issue by Chatles** [Tencent/APIJSON#521]
### Description

我看到6.0.0版本APIJSONDemo的Request表有条记录：
29,0,1,GETS,login,"{""Privacy"": {""MUST"": ""phone,_password"", ""REFUSE"": ""id""}}",,2017-10-15 18:04:52.000000
但没有找到任何的登录调用示例，我不知道登录的机制是什么。
想问6.0.0版本APIJSONDemo带login功能吗？还是说要自己实现？
另外也没看见有推出登录的功能。

各种查询的设计感觉很赞！
但是6.0.0版本APIJSONDemo和5.4.0版的todo demo差异很大，给初学者带来了很大的困惑。

**Comment by TommyLemon** [comment]
APIJSONBoot 系列带登录、注册、验证码等比较全的功能
https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server

**Comment by nanshuge** [comment]
> APIJSONBoot 系列 Demo 带登录、注册、验证码等比较全的功能 https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server <img alt="image" width="1262" src="https://user-images.githubusercontent.com/5738175/221733245-19d3aec0-56e9-4b00-9e4f-b9fc4d2ef1e3.png">

这个是一定要使用'http://apijson.cn:9090/login'这个登录吗?
1、我下载的最新代码（APIJSON-Demo/APIJSON-Java-Server/APIJSONDemo），程序启动成功之后，通过浏览器访问http://localhost:8080/get/%7B%7D 是成功的。
2、我在UnitAuto/UnitAuto-Java-Demo中将src/main/resources/static/js/main.js中的server由原来的的“'http://apijson.cn:9090'”，改成“'http://127.0.0.1:8080'”，
2.1、UnitAuto-Java-Demo可以正常启动，并且访问“http://localhost:8081/”可以打开页面。
2.2、不过我在进行登录的时候显示405错误。
<img width="816" alt="image" src="https://user-images.githubusercontent.com/40234211/233847776-fa713ad8-95fb-495b-980b-c1a04d93de7e.png">

**Comment by TommyLemon** [comment]
UnitAuto-Java-Demo 都没有  /login 接口，当然调不通，不过不影响单元测试，忽略掉即可。
也可以实现一个  /login 接口

**Comment by TommyLemon** [comment]
@nanshuge 6.1.0 已发布，解决了多表同时增删改的 bug 等问题；新增支持 Snowflake,Databricks,Cassandra；增强条件组合、参数校验等：
https://github.com/Tencent/APIJSON/releases/tag/6.1.0
https://github.com/APIJSON/apijson-framework/releases/tag/6.1.0
https://github.com/APIJSON/apijson-router/releases/tag/1.6.0
https://github.com/APIJSON/apijson-column/releases/tag/1.6.0
