### ISSUE TITLE
没有id字段的表进行删和改实现遇到的问题

### ISSUE THREAD

**Issue by aitedianaite** [Tencent/APIJSON#546]
### Description

我在进行主键不是id的数据进行删和改的时候发现会提示报错，没有id字段，经过排查和资料收集看到重写SimpleCallback的getIdKey方法，在重写它的时候发现当前手上很多表的主键是没有规律的，然后想到用配置来化解如下图
![image](https://user-images.githubusercontent.com/45868118/231715564-7a4506ce-10e6-4af9-a992-c9468350e583.png)
但是这样做的话我的access表中的alias字段最多只能有一个下划线，且在配置access的时候就得去考虑主键，不知道这样是不是太繁琐，大佬有没有实现思路呢，感谢~~

**Comment by TommyLemon** [comment]
不想写很多 if-else if-else 或 switch case 的话，可以加个 Map<String, String> tableIdKeyMap 配置下，
也可以在 Access 表里加上 idKey 字段，直接从 ACCESS_MAP 里根据 table 来取 idKey

**Comment by cloudAndMonkey** [comment]
@aitedianaite 
APIJSON支持非id条件删除、修改呀, 不需要改代码呀
![image](https://user-images.githubusercontent.com/12228225/231763786-26d48463-a5ae-4188-8dca-cc3bbdd10387.png)
https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractVerifier.java#L77

使用 可以参见: https://github.com/Tencent/APIJSON/issues/509

**Comment by TommyLemon** [comment]
如果有主键则建议改成实际主键名，如果没有主键要么加上，要么按以上 @cloudAndMonkey 的建议：增删改使用非主键作为条件
