### ISSUE TITLE
Sources not found for: com.github.Tencent:APIJSON

### ISSUE THREAD

**Issue by kit101** [Tencent/APIJSON#547]
### Description

无法通过maven下载源码jar（图1），访问[jitpack.io](https://jitpack.io/com/github/Tencent/apijson/6.0.0/)发现源码jar未发布到中央仓库（图2）

希望能发布源码到中央仓库，调试会更方便 🙏🙏🙏

图1:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/23008405/231959545-6e7a735b-4aae-4ff8-bff3-c283c816fd06.png">
图2:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/23008405/231961881-40259477-44ff-49b7-b42e-e74a5947e3f3.png">

**Comment by TommyLemon** [comment]
可以直接依赖源码来断点调试

**Comment by kit101** [comment]
下载源码并install到本地maven库调试
```bash
git clone -b 6.0.0 --depth=1 https://github.com/Tencent/APIJSON.git
cd APIJSON/APIJSONORM
mvn source:jar install
```
