### ISSUE TITLE
请问返回的code可以更改成 0 吗

### ISSUE THREAD

**Issue by jwcjf** [Tencent/APIJSON#548]
### Description

![image](https://user-images.githubusercontent.com/18321599/231980858-0560547c-a868-41da-a741-91d759ec7a19.png)

code:200  改成 code:0

**Comment by TommyLemon** [comment]
不管是前端还是后端，拿到返回 Response JSON 后想改成啥样都行，参考这个用户的文章：
使用APIJSON写低代码Crud接口
https://blog.csdn.net/weixin_42375862/article/details/121654264
<img width="889" alt="image" src="https://user-images.githubusercontent.com/5738175/232001096-6b1847c5-ad69-4c68-b873-687e7de7e3f2.png">

**Comment by TommyLemon** [comment]
增加一个 status/statusCode/errCode/errorCode 等命名的字段表示状态码/错误码更好，可以很好地兼容生态项目
https://github.com/Tencent/APIJSON/issues/611
