### ISSUE TITLE
关于APIJSONBoot部署的问题

### ISSUE THREAD

**Issue by X-777** [Tencent/APIJSON#549]
### Description

拉取[APIJSONBoot](https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server/APIJSONBoot)的代码在本地部署，项目正常启动，端口设置为8081，但是请求接口都是无法访问的，关于部署还有什么注意的吗？
![image](https://user-images.githubusercontent.com/3581889/232303792-3bab4c3e-64a1-4304-8974-6f36640a47bc.png)
![image](https://user-images.githubusercontent.com/3581889/232303990-b9b7ced9-1e12-4aff-8c28-283cb7f2e315.png)

**Comment by TommyLemon** [comment]
为啥要用 HTTP GET 调用只支持 HTTP POST 的接口？
