### ISSUE TITLE
Function 不允许 UNKNOWN 用户的 GET 请求！

### ISSUE THREAD

**Issue by moyuqinsi** [Tencent/APIJSON#550]
### Description

系统 win11 
数据库 mysql8.0

![image](https://user-images.githubusercontent.com/26790982/232306674-bbfd2483-6176-4dfc-8da8-a31e58a06b8e.png)

一添加上面得内容就报 Function 权限错误

下面是框架输出得错误信息

远程函数文档测试未通过！
请新增 demo 里的函数，或修改 Function 表里的 demo 为已有的函数示例！
保证前端看到的远程函数文档是正确的！！！

原因：

 !!!! 查询远程函数异常 !!!
Function 不允许 UNKNOWN 用户的 GET 请求！

**Comment by cloudAndMonkey** [comment]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/12228225/232368751-bab034c3-cb0a-42a0-a72d-d4712d4ce15d.png">
需要Access表配置远程函数 访问权限

```sql
INSERT INTO `access` (`id`, `debug`, `name`, `alias`, `get`, `head`, `gets`, `heads`, `post`, `put`, `delete`, `date`, `detail`, `appId`, `userId`, `deletedKey`, `deletedValue`) VALUES (5, 0, 'Function', NULL, '[\"UNKNOWN\", \"LOGIN\", \"CONTACT\", \"CIRCLE\", \"OWNER\", \"ADMIN\"]', '[\"UNKNOWN\", \"LOGIN\", \"CONTACT\", \"CIRCLE\", \"OWNER\", \"ADMIN\"]', '[\"LOGIN\", \"CONTACT\", \"CIRCLE\", \"OWNER\", \"ADMIN\"]', '[\"LOGIN\", \"CONTACT\", \"CIRCLE\", \"OWNER\", \"ADMIN\"]', '[]', '[]', '[]', '2018-11-29 00:38:15', '框架本身需要', NULL, NULL, NULL, NULL);
```
