### ISSUE TITLE
返回多条数据的传入参数key一定要用[] 吗

### ISSUE THREAD

**Issue by jwcjf** [Tencent/APIJSON#552]
### Description

![image](https://user-images.githubusercontent.com/18321599/232428107-ca5ac665-e467-4e3f-98b1-f743f26eef17.png)

![image](https://user-images.githubusercontent.com/18321599/232428158-7f7b9343-df74-4ae1-8f55-3f1993526af1.png)

我用其他的key 只返回一条数据。

**Comment by TommyLemon** [comment]
https://github.com/Tencent/APIJSON/issues/317
