### ISSUE TITLE
如何两张表进行关联查询，过滤第二张表的时候应该返回列表一条数据，结果列表返回了两条

### ISSUE THREAD

**Issue by AwenJackson** [Tencent/APIJSON#553]
### Description

查询参数

查询结果

**Comment by AwenJackson** [comment]
@TommyLemon 大佬，麻烦看一下；P73680_yonghulist_address_link表需要过滤出id等于1681809746458的数据，由于P73680_yonghulist表和P73680_yonghulist_address_link表存在关系，但是查出来的数据，本来应该是一条，结果显示了两条，该怎么处理？

**Comment by TommyLemon** [comment]
应该是因为本来就有两条数据，把 SQL 放数据库执行也是一样的结果。
如果要用副表 P73680_yonghulist_address_link 过滤主表 P73680_yonghulist，可以用 INNER JOIN：
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2

**Comment by AwenJackson** [comment]
![image](https://user-images.githubusercontent.com/95326431/232756842-60871c31-784b-45ca-90f7-86ce1f23b379.png)
SQL应该是这样的

**Comment by TommyLemon** [comment]
> ![image](https://user-images.githubusercontent.com/95326431/232756842-60871c31-784b-45ca-90f7-86ce1f23b379.png) SQL应该是这样的，那么APIJSON该怎么查？

这是子查询，在 APIJSON 通用文档搜索子查询：
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2

或者在 APIAuto 测试用例列表搜索子查询：
http://apijson.cn/api

**Comment by cloudAndMonkey** [comment]
> ![image](https://user-images.githubusercontent.com/95326431/232756842-60871c31-784b-45ca-90f7-86ce1f23b379.png) SQL应该是这样的，那么APIJSON该怎么查？

```json
{
  "sql@": {
        "with": true,
        "from": "User",
        "User": {
          "@column": "username",
          "username": "test2"
        }
    },
    "User": {
      "password": "123456",
        "username{}@": "sql"
    },
    "tag": "User",
    "format": true,
    "@explain": true
}

```
```sql
"sql": "SELECT * FROM `housekeeping`.`User` WHERE  (  (`password` = '123456') AND (`username` IN ( SELECT * FROM (SELECT `username` FROM `housekeeping`.`User` WHERE  (  (`username` = 'test2')  ) ) AS `sql`) )  )  LIMIT 1"
```

多看文档, 哈哈

**Comment by AwenJackson** [comment]
![image](https://user-images.githubusercontent.com/95326431/232945155-099a89bc-be34-4362-9b4c-300fff911798.png)
wo'zhe我这样查的，貌似也可以

**Comment by cloudAndMonkey** [comment]
> ```json
> "format": true,
>     "@explain": true
> ```

"format": true,
"@explain": true
可以看到sql语句

**Comment by AwenJackson** [comment]
> > ```json
> > "format": true,
> >     "@explain": true
> > ```
> 
> "format": true, "@Explain": true 可以看到sql语句

好的，谢谢 @cloudAndMonkey

**Comment by AwenJackson** [comment]
如果是这样的sql语句呢？
`SELECT * FROM p73680_yonghulist WHERE id IN (
	SELECT entity_id FROM p73680_yonghulist_address_link WHERE show_value = '四川北路'
)
AND
id IN (
	SELECT entity_id FROM p73680_yonghulist_shengfen_link WHERE show_value = '湖北省'
);`
![image](https://user-images.githubusercontent.com/95326431/233038911-883f2942-2348-4111-b0da-51f21113d175.png)

APIJSON的参数该怎么写？
![image](https://user-images.githubusercontent.com/95326431/233039114-f8991d3b-3676-44ee-b673-7a8184845f93.png)
在哪里加上这一段
![image](https://user-images.githubusercontent.com/95326431/233039279-24d7a5d9-94b5-437b-8913-6c0a41b27627.png)

@TommyLemon @cloudAndMonkey

**Comment by AwenJackson** [comment]
我找不到and符号在哪里加

**Comment by TommyLemon** [comment]
可以加个 "id|{}@": { ... }
不同键值对默认 AND 连接。

**Comment by AwenJackson** [comment]
那如果是OR呢？我看这里不是 | 对应OR，&对应 AND吗？ @TommyLemon

**Comment by TommyLemon** [comment]
"key|{}":"key>10,key<=100" // key>10 OR key<=100
"key&{}":"key>10,key<=100" // key>10 AND key<=100
"@combine":"key|{} | key&{}" // (key>10 OR key<=100) OR (key>10 AND key<=100)

多看看文档（与或非逻辑符）
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2

**Comment by AwenJackson** [comment]
`
SELECT * FROM p73680_yonghulist WHERE id IN (
	SELECT entity_id FROM p73680_yonghulist_address_link WHERE show_value = '四川北路'
)
AND
id IN (
	SELECT entity_id FROM p73680_yonghulist_shengfen_link WHERE show_value = '湖北省'
)
AND 
id IN (
  SELECT entity_id FROM p73680_yonghulist_zuojian_link WHERE show_value = '梵高'
);
`
如果是三张表呢？
![image](https://user-images.githubusercontent.com/95326431/233050769-afb63869-9d88-4e93-a4df-f9c89590854b.png)

@TommyLemon @cloudAndMonkey

**Comment by TommyLemon** [comment]
你这需求也太奇怪了，同一个 key IN 不同的子查询，把子查询换成 EXISTS 或 JOIN 吧

**Comment by TommyLemon** [comment]
p73680_yonghulist_address_link, p73680_yonghulist_shengfen_link, p73680_yonghulist_zuojian_link 
这三张表看起来结构一致，为啥数据不能放一张表，而是这么奇怪地拆分？

**Comment by AwenJackson** [comment]
![image](https://user-images.githubusercontent.com/95326431/233052351-8e26e184-6f51-4109-8ddc-123321a9c511.png)
这三张表其实是关系表

**Comment by TommyLemon** [comment]
上面两张关系表，加一个 type 之类的字段区分下就行了，表拆分太细不管是用 APIJSON、其它 ORM 库还是手写 SQL 都很麻烦

**Comment by TommyLemon** [comment]
要不然城、镇、乡、村都还得继续加 
p73680_yonghulist_cheng_link
p73680_yonghulist_zhen_link
p73680_yonghulist_xiang_link
p73680_yonghulist_cun_link
这些表吗？
没必要这么折腾

**Comment by AwenJackson** [comment]
> 要不然市、镇、乡、村都还得继续加 p73680_yonghulist_shi_link p73680_yonghulist_zhen_link p73680_yonghulist_xiang_link p73680_yonghulist_cun_link 这些表吗？ 没必要这么折腾，一张表通过一个字段标识 省、市、镇、乡、村 这样的类型就行了

目前只能做限制还是什么？马上要上线了，后期再改一下这个关系表的结构，谢谢大佬 @TommyLemon

**Comment by TommyLemon** [comment]
> 你这表名和需求都很奇怪，同一个 key IN 不同的子查询，把子查询换成 JOIN 或 EXISTS 吧

如果是直接暴露 APIJSON 格式的 HTTP API 给客户端 App（不像前端网页能随时更新），那上线后改动反而更麻烦，目前整合下表其实花不了多少时间。
如果使用了 apijson-router 或其它把 APIJSON 包装后再暴露 HTTP API，那也可以先上线，后面再调整。
https://github.com/APIJSON/apijson-router
