### ISSUE TITLE
请求400[xxx] 

### ISSUE THREAD

**Issue by linzhongniao** [Tencent/APIJSON#554]
### Description

请求url :     http://localhost:8081/get/{   "[]": {     "Moment": {       "id{}": [12, 15, 32],       "@column": "id,date,content"     }   } }
![image](https://user-images.githubusercontent.com/29010729/233592649-d113f975-a683-45b5-9927-d719ade2cae2.png)
请求url : http://localhost:8081/get/{   "Moment": {     "id": 12   } } 可以请求成功
![image](https://user-images.githubusercontent.com/29010729/233592846-decd87d1-a69a-480f-b047-e777812cf669.png)

**Comment by TommyLemon** [comment]
用 HTTP GET，URL 中的特殊字符要转义。
建议用 HTTP POST + JSON 传参。
另外接口工具推荐 APIAuto：
http://apijson.cn/api

**Comment by linzhongniao** [comment]
好的,感谢
