### ISSUE TITLE
Table 'sys.access' doesn't exist 

### ISSUE THREAD

**Issue by wenjinwei** [Tencent/APIJSON#556]
### APIJSON Version/APIJSON 版本号

6.0.0

### Database Type & Version/数据库类型及版本号

MYSQL 8.0.11 

### Environment/环境信息

```markdown
系统: Windows 10 10.0 
 JDK: 1.8.0_131 amd64
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

Table 'sys.access' doesn't exist 

### Current Behavior/问题描述

```markdown
Table 'sys.access' doesn't exist
```

**Comment by wenjinwei** [comment]
1

**Comment by TommyLemon** [comment]
没这张表，APIJSON 返回的报错信息里有 Google, 百度, GitHub 的关于这个问题的链接，都点进去看看

**Comment by luchao314** [comment]
我使用分别MySQL5.7.44和9.0.0，使用root用户也无法找到这张表

**Comment by luchao314** [comment]
兄弟，找到问题了，少了一个步骤
