### ISSUE TITLE
关于[APIJSON]和GraphQL的区别

### ISSUE THREAD

**Issue by yinziyan1206** [Tencent/APIJSON#557]
### Description

目前GraphQL的生态已经足够齐全，包括相应的低代码平台（比如hasura的graphql-engine）。APIJSON对比起来有哪些优势，或者说什么情况下用APIJSON会更好一些。

**Comment by TommyLemon** [comment]
APIJSON 在 功能、安全、性能、易用性、Java 版生态(继承 JSON 的海量生态) 等都大幅领先 GraphQL
https://github.com/Tencent/APIJSON/issues/2
![image](https://user-images.githubusercontent.com/5738175/104417275-103d7400-55b0-11eb-8ad8-737867d92456.png)

graphql-engine 做不到零代码实现复杂查询，例如 JOIN，子查询等，更别说 JOIN 和子查询相互嵌套了，
APIJSON 是各种 JOIN，各种子查询以及它们相互嵌套都支持后端零代码实现。

**Comment by entropy-cloud** [comment]
在低代码平台中使用GraphQL协议就可以实现类似APIJSON的功能。参见文章 [Nop平台与APIJSON的功能对比](https://mp.weixin.qq.com/s/vrQVGs-c0dVWcOJEsOz_nA)。
Nop平台内置了基于可逆计算原理从零开始设计的下一代GraphQL引擎NopGraphQL和下一代ORM引擎NopORM，它们结合在一起可以很容易的实现类似APIJSON的功能。https://github.com/entropy-cloud/nop-entropy
