### ISSUE TITLE
不允许调用远程函数 getCurrentUserId !

### ISSUE THREAD

**Issue by shyding** [Tencent/APIJSON#560]
### APIJSON Version/APIJSON 版本号

6.0.0

### Database Type & Version/数据库类型及版本号

MySQL 5.7

### Environment/环境信息

```markdown
JDK: 1.8.0_201 amd64 APIJSON: 6.0.0
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

正常调用getCurrentUserId 中的方法

### Current Behavior/问题描述

```markdown
{
  "id@-()": "getCurrentUserId()",  //  会得到 "id@": 1 这样
  "User": {
    "id@": "/id"  // 引用不到
  }
}
```

### Expected Behavior/期望结果

```markdown
getCurrentUserId 能够被正常调用
```

### Any additional comments?/其它补充说明？

```markdown
无
```

**Comment by TommyLemon** [comment]
"id@-()" 去掉多余的 @ 符号。
严格按通用文档来：
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2

**Comment by shyding** [comment]
一样的异常结果返回: 

req:

{
  "id()": "getCurrentUserId()",  //  会得到 "id@": 1 这样
  "User": {
    "id": 82005  
  }
}

rsp:
"id()": "getCurrentUserId()" ,
"User":  {
"id": 82005
},
"ok": false ,
"code": 403 ,
"msg": "不允许调用远程函数 getCurrentUserId !" ,

**Comment by shyding** [comment]
能否帮忙给个demo , 
apijsondemo-multidatasource-redis 模块中的apijson.demo.DemoFunctionParser.sayHello(JSONObject, String)方法

**Comment by TommyLemon** [comment]
麻烦完整截屏，否则不再回复

**Comment by shyding** [comment]
![1683509015219](https://user-images.githubusercontent.com/24986567/236714235-42e13f2a-36da-4021-ae7f-c1fbc48ffedb.png)

**Comment by shyding** [comment]
![1683509157919](https://user-images.githubusercontent.com/24986567/236714411-e2c00f9a-fae3-4249-81e8-b806a95c1e24.png)

**Comment by shyding** [comment]
> 麻烦完整截屏，否则不再回复

如上, 已经提供了完整截图了

**Comment by TommyLemon** [comment]
APIAuto 都已经通过静态检查明确告诉你了：必须在 Function 表有这个方法的配置
<img width="202" alt="image" src="https://user-images.githubusercontent.com/5738175/237034738-b0c2867c-a84b-4302-b601-0d6913a9ac5f.png">

**Comment by shyding** [comment]
好吧 谢谢
