### ISSUE TITLE
请教:后端如何进行正常的查询,一个普通的springboot bean 中如何调用框架api 进行类似前端的这种查询

### ISSUE THREAD

**Issue by shyding** [Tencent/APIJSON#561]
### APIJSON Version/APIJSON 版本号

6.0.0

### Database Type & Version/数据库类型及版本号

 MySQL 5.7

### Environment/环境信息

```markdown
JDK: 1.8.0_201 amd64 APIJSON: 6.0.0
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

后端springboot bean 中如何进行api调用,来完成 普通的crud

### Current Behavior/问题描述

```markdown
只能前端传字符串数据到后端,来完成数据的查询
```

### Expected Behavior/期望结果

```markdown
后端能够向前端一样调用api, 完成对应的查询. 理由: 存在很多场景,后端的数据是不需要跟前端交互的. 比如:定时任务; 守护进程中的报表统计等等
```

### Any additional comments?/其它补充说明？

```markdown
希望能够增加后端能够向前端一样调用的相关demo
```

**Comment by TommyLemon** [comment]
参考 APIJSONBoot 系列 DemoController 中的 /login, /register, /post/verify 等
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONBoot/src/main/java/apijson/boot/DemoController.java#L392-L1114

或者 @jerrylususu 写的关于自定义鉴权、执行完整原始 SQL 等代码片段
https://github.com/APIJSON/apijson_todo_demo/blob/master/FULLTEXT.md#%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6%E8%A7%92%E8%89%B2%E5%92%8C-access-%E8%A1%A8
