### ISSUE TITLE
使用APIJSON的模糊查询，报错如下，是什么问题

### ISSUE THREAD

**Issue by AwenJackson** [Tencent/APIJSON#563]
### Description

![image](https://github.com/Tencent/APIJSON/assets/95326431/91f3df7e-b79c-4fc0-8917-d2fe8ff0ff0f)
![image](https://github.com/Tencent/APIJSON/assets/95326431/1ab7549a-d12d-4cd5-bf1e-d020dd694ee7)

**Comment by AwenJackson** [comment]
@TommyLemon 大佬，麻烦看一下

**Comment by AwenJackson** [comment]
我将mysql 8.0数据库的数据导入到5.7版本的数据库中，发现使用这个参数查询没有问题；但是在8.0中就报错

**Comment by TommyLemon** [comment]
MySQL 8.0+ 不再支持 BINARY REGEXP 表达式，改为使用 regexp_like，APIJSON 5.2.0 + 兼容；
https://github.com/Tencent/APIJSON/releases

另外 DemoSQLConfig.getDBVersion 的 return 值必须和实际的数据库版本一致。
