### ISSUE TITLE
[Bug] DemoParser 重写 getMaxQueryPage 失效

### ISSUE THREAD

**Issue by transtone** [Tencent/APIJSON#569]
### APIJSON Version/APIJSON 版本号

6.1.0

### Database Type & Version/数据库类型及版本号

MySql 5.7.34

### Environment/环境信息

```markdown
- JDK/基础库: 1.8.0_17
- OS/系统: windows 11
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

![image](https://github.com/Tencent/APIJSON/assets/46688/602007a6-73b1-4a85-87b1-ec321a18db36)
![image](https://github.com/Tencent/APIJSON/assets/46688/cce9e9fa-a9e0-424c-88d6-8611ba28137a)

### Current Behavior/问题描述

```markdown
使用官方示例 https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server/APIJSONDemo-Druid 
修改 DemoParser 重写 getMaxQueryPage, 改写查询页码页数。

页面限制覆盖失效。依然提示："data[]/page:value 中 value 的值不合法！必须在 0-100 内 !"

原 APIJSONDemo-Druid 项目中不含 DemoParser.java 文件，新建了一个测试项目，只添加了这一个文件：
https://github.com/transtone/APIJSON-DEMO-Druid/blob/main/src/main/java/apijson/demo/DemoParser.java


请求参数
```json
{
    "format": true,
    "data[]": {
        "Comment": { },
        "page": 600,
        "query": 2,
        "count": 50
    },
    "total@": "/data[]/total",
    "info@": "/data[]/info"
}
```

复现项目地址：  https://github.com/transtone/APIJSON-DEMO-Druid/
```


### Expected Behavior/期望结果

_No response_

### Any additional comments?/其它补充说明？

_No response_

**Comment by transtone** [comment]
要想覆盖生效，必须加入 https://github.com/APIJSON/apijson-router/ 

而加入 router 有需要导入document 等数据表，启动验证不通过会自动结束。还没找到清爽的好办法。

**Comment by TommyLemon** [comment]
没有注册 DemoParser，所以没生效
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONBoot/src/main/java/apijson/boot/DemoApplication.java#L162-L189

**Comment by HePingLaoSan** [comment]
如果我想修改查询的最大数量，默认是单页100，100页面，都需要创建哪些才能实现呢？DemoParser、DemoSQLExecutor、DemoVerifier等等吗？

**Comment by TommyLemon** [comment]
@HePingLaoSan  
AbstractParser.MAX_QUERY_COUNT = 200;
AbstractParser.MAX_QUERY_PAGE = 200;
或者在 DemoParser 重写 getMaxQueryCount, getMaxQueryPage 等方法。
