### ISSUE TITLE
【事务】是否支持spring事务和apijson事务混搭使用？

### ISSUE THREAD

**Issue by nuizhaolei** [Tencent/APIJSON#572]
### Description

1、是否支持spring事务和apijson事务混搭使用？
2、关于表中时间返回值末尾有.0 或者 数字数据末尾返回.0，在不确定具体字段的情况下是否支持全局配置处理？

**Comment by TommyLemon** [comment]
1、APIJSON ORM 处理的增删改查 SQL 必须用 APIJSON 内置的事务，其它随意；用 SpringBoot 的 @Transactional 等方式实现事务不一定对 APIJSON 生成和执行的 SQL 生效。
2、DemoSQLExecutor 重写 onPutColumn，自己处理，例如加上 value instance of Date/DateTime/Timestamp 或者 "date".equals(columnName) 等判断

**Comment by nuizhaolei** [comment]
1、好吧，
2、这个处理方式多余了很多冗余代码，我搜索到有很多处理函数，是不是也处理不了？formdate、time等

**Comment by TommyLemon** [comment]
2、统一处理能有多少冗余代码？又不是每个接口都要写一份。
`formdate ` 打错了吧，是指 SQL 函数 `from_date` ? 
这些应该是传参，用来拼接成 SQL 的函数表达式，而不是拿到 ResultSet 后的处理。
例如
"@column": "from_date(date)" // 需要在 DemoSQLConfig 中注册 SQL_FUNCTION_MAP.put("from_date", "")
https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java#L291-L770

**Comment by nuizhaolei** [comment]
了解，多谢；
是否支持一个字段多模糊查询？

**Comment by TommyLemon** [comment]
麻烦先认真看了官方文档（首页介绍文档、通用文档、官网文档）再问，以后你提的这种问题不再回答
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2
<img width="1491" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/8902bae6-8109-4f52-a585-2b95b797cac1">

**Comment by TommyLemon** [comment]
请尊重别人的时间
https://github.com/Tencent/APIJSON/issues/36
<img width="1016" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/540bf82d-4b2e-4001-90cf-a9c465ceaf2c">
