### ISSUE TITLE
[低代码平台] 

### ISSUE THREAD

**Issue by Mengleijin** [Tencent/APIJSON#574]
### Description

想问一下目前有没有基于APIJSON的低代码平台啊？如果想把APIJSON应用到低代码平台里应该怎么实现呢？

**Comment by TommyLemon** [comment]
https://github.com/Tencent/APIJSON/pull/452
https://github.com/Tencent/APIJSON/issues/573
https://mp.weixin.qq.com/s/HfZDrrqDNUVpnU-aegKxcg
