### ISSUE TITLE
插入结果返回值少一个

### ISSUE THREAD

**Issue by wahowaho** [Tencent/APIJSON#575]
### APIJSON Version/APIJSON 版本号

6.1.0

### Database Type & Version/数据库类型及版本号

5.7.35

### Environment/环境信息

```markdown
- JDK/基础库: 1.8
- OS/系统: windows
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

1231231

### Current Behavior/问题描述

```markdown
参数：

{
	"@post": {
		"Stone": {"tag":"Stone"},
		"Stone[]": {"tag":"Stone[]"}
	},
	"Stone": {"name":"小石头","number":"1"},
	"Stone[]": [
		{"name":"石头1","number":"1"},
		{"name":"石头2","number":"2"},
		{"name":"石头3","number":"3"},
		{"name":"石头4","number":"4"}
	],
	"@explain": true
}

返回值：
{
    "Stone": {
        "ok": true,
        "code": 200,
        "msg": "success",
        "count": 4,
        "id[]": [
            1685243826399,
            1685243826401,
            1685243826402,
            1685243826403
        ]
    },
    "@explain": true,
    "ok": true,
    "code": 200,
    "msg": "success"
}
问题描述：
当前返回值中没有第一个单独插入的Stone对应的ID。
```

### Expected Behavior/期望结果

```markdown
单独插入的Stone，id同样被返回。
```

### Any additional comments?/其它补充说明？
两表插入没这个问题
{
	"@post": {
		"Rain": {"tag":"Rain"},
		"Stone[]": {"tag":"Stone[]"}
	},
	"Rain": {"name":"小雨","number":"1"},
	"Stone[]": [
		{"name":"石头1","number":"1"},
		{"name":"石头2","number":"2"},
		{"name":"石头3","number":"3"},
		{"name":"石头4","number":"4"}
	],
	"@explain": true
}

{
    "Rain": {
        "sql": "INSERT INTO `apijson`.`b_rain`(`id`,`name`,`number`) VALUES(1685254101633,'小雨','1')",
        "ok": true,
        "code": 200,
        "msg": "success",
        "count": 1,
        "id": 1685254101633
    },
    "Stone": {
        "ok": true,
        "code": 200,
        "msg": "success",
        "count": 4,
        "id[]": [
            1685254101663,
            1685254101665,
            1685254101667,
            1685254101668
        ]
    },
    "@explain": true,
    "ok": true,
    "code": 200,
    "msg": "success"
}

**Comment by TommyLemon** [comment]
是个 bug，同表增改会导致返回 id/id[] 被替换，因为目前 Table[]:[{}] 对应批量增删改也会返回为 Table:{ "id[]":[] }，简化前端解析。
之前是考虑到几乎没有这样的需求，因为同表的批量增改完全可以写到一个 Table[]:[{}]，没必要分拆成多个对象。

如果确实一定要这么做，可以合并下同表但不同对象返回的 id 和 id[]
https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLExecutor.java#L249-L258
<img width="1191" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/061248e4-551d-4351-a00a-eda39d721519">

或者更好地方式应该是，按原来的对象格式返回：
```js
{
	"Stone": {
            "id": 1,
            ...
        },
	"Stone[]": {
             "id[]": [2, 3, 4],
            ...
         }
}
```

**Comment by wahowaho** [comment]
嗯  我只是说了这个现象，基本没这么干的 ^_^，可以无视
