### ISSUE TITLE
双表插入问题，引用路径写错时，事务处理是不是有问题？

### ISSUE THREAD

**Issue by wahowaho** [Tencent/APIJSON#576]
### Description

![image](https://github.com/Tencent/APIJSON/assets/28621460/1a83b1bc-fc6c-4ad1-9f91-6c4d16883b00)
如上图，引用不到时，结果虽然成功了，第二张表Fly没有插入进去，这个不知道归类的那种情况，是bug还是别的情况^_^

**Comment by TommyLemon** [comment]
设计如此，不过可以提供一个类似 boolean THROW_WHEN_REFER_PATH_IS_NULL 选项，当引用路径对应的值不存在后为 null 时，把默认丢弃当前对象改为 throw NullPointerException

https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractObjectParser.java#L413-L419
<img width="1192" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/bb1a61b2-bafe-414f-a6ff-c02cb53fd588">

**Comment by TommyLemon** [comment]
当找不到引用赋值路径对应的非 null 值时在 DEBUG 下返回警告信息
https://github.com/Tencent/APIJSON/commit/74f4e73e92cf58064c882fd4505b13f74d5e974a
