### ISSUE TITLE
[Feature] 删除和修改时提示对象不存在，能否配置不存在也返回正常

### ISSUE THREAD

**Issue by lanmuc126** [Tencent/APIJSON#586]
### Description

您好，我也不知道我文档有没有看全，但是很多文档都找了，没有找到这么个功能。需求很简单，首先感谢大家提供的资料，让我可以知道如何实现多步同事务操作，有需要的可以看下下面的格式，但是当我在执行修改或者删除操作时，未查询到要修改或删除的数据时，会把前面的执行结果回滚掉并提醒我对象不存在，请问贡献者大大及作者大大，这个目前有解决方案吗，是可以屏蔽全局还是单独屏蔽某一个呢。
```json
{
  "Test": {
    "a":"1"
    "@explain":true
  },
  "Test:del": {
    "@method": "delete",
    "status{}": "=0",
    "@combine": "status{}",
    "@explain":true
  },
  "Test:put": {
    "@method": "put",
    "status": 0,
    "status{}": " =1",
    "@combine": "status{}",
    "@explain":true
  }
}
```

**Comment by TommyLemon** [comment]
DemoSQLExecutor 重写 begin，调用 setAutoCommit(true)
不过这样会导致多事务处理不能统一回滚，需要自己根据需要判断是否要这么操作
