### ISSUE TITLE
[咨询]请问支持跨库查询吗，有相关文档和查询demo吗 

### ISSUE THREAD

**Issue by jwcjf** [Tencent/APIJSON#587]
### Description

[咨询]请问支持跨库查询吗，有相关文档和查询demo吗

**Comment by TommyLemon** [comment]
@schema / @database / @datasource
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2
<img width="1440" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/1c2d85a1-bacb-4fb8-92b0-775fec26f50a">

https://github.com/Tencent/APIJSON/issues/272
https://github.com/Tencent/APIJSON/issues/364
