### ISSUE TITLE
[xxx] get请求返回的id精度丢失如何解决，在通用配置类配置了消息转换器处理，唯独apijson服务不起作用

### ISSUE THREAD

**Issue by lizwwww** [Tencent/APIJSON#589]
### Description

[xxx] get请求返回的id精度丢失如何解决，在通用配置类配置了消息转换器处理，唯独apijson服务不起作用

**Comment by TommyLemon** [comment]
类型改用 String
https://github.com/Tencent/APIJSON/issues/365
