### ISSUE TITLE
建议对springboot增加连接池组件

### ISSUE THREAD

**Issue by k4n5ha0** [Tencent/APIJSON#60]
我看了一下工程目录 似乎没有使用数据库连接池 
直接操作jdbc对性能影响很大 
希望作者 提供连接池相关的技术支持
谢谢
另外建议使用undertow以替换tomcat
undertow性能比tomcat好很多

**Comment by TommyLemon** [comment]
因为 Demo 只是用来简单上手的，尽可能少引入第三方库。
[Undertow](https://github.com/undertow-io/undertow) 暂不考虑，Web 容器还是 Tomcat 更主流上手简单；
连接池倒是比较刚需的，考虑用 [Druid](https://github.com/alibaba/druid) 在 Demo 工程内实现。

**Comment by yangjinju** [comment]
@TommyLemon 目前连接池管理是否已经完善了？

**Comment by TommyLemon** [comment]
@yangjinju 

在 DemoSQLExecutor 重写 getConnection

```java
public Connection getConnection(..) {
  Connection c = connectiomMap.get(config.getDatabase());
  if (c == null || c.isClosed()) {
    connectiomMap.put(config.getDatabase(), DruidConfig.DATA_SOURCE.getConnection());  // DruidConfig 初始化获取到 Datasource 后给静态变量 DATA_SOURCE 赋值，或者也可以试试 ApplicationContext.getBean(DruidConfig.class).getDataSource()
  }
  return super.getConnection(..)
}
```

**Comment by TommyLemon** [comment]
已适配连接池
https://github.com/APIJSON/APIJSON-Demo/releases/tag/4.4.5

**Comment by TommyLemon** [comment]
新增数据源关键词 @datasource，可由业务完全自定义
https://github.com/Tencent/APIJSON/releases/tag/4.7.0

新增 连接池及多数据源 Demo（Druid + HikariCP）
https://gitee.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server
