### ISSUE TITLE
apijson-framework  6.2.0 springboot3  未合并发布

### ISSUE THREAD

**Issue by csx-bill** [Tencent/APIJSON#600]
### Description

apijson-framework  6.2.0 springboot3  未合并发布

**Comment by TommyLemon** [comment]
包名不同，看起来可以整合下

**Comment by csx-bill** [comment]
不好整合，因为 引用包不一样&nbsp;jakarta.servlet



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Spencer ***@***.***&gt;; 
发送时间: 2023年8月14日(星期一) 晚上11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/APIJSON] apijson-framework  6.2.0 springboot3  未合并发布 (Issue #600)





 
包名不同，看起来可以整合下

**Comment by csx-bill** [comment]
好方案，增加泛型应该可以

**Comment by nnbh2020** [comment]
没明白

**Comment by liangxp** [comment]
`
APIJSONController<T extends Object> {
  public String get(String request, HttpSession session) {
     ...
  }
  public String get(String request, jakarta.servlet.http.HttpSession session) {
     ...
  }
}
`
我认为这种方案最可行，可以同时兼容，并且对于以往使用的开发者来说是无感的！

**Comment by csx-bill** [comment]
好像不行，突然想起如果我只安装了 jdk17，打包应该会找不到 servlet 的包



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ronny West ***@***.***&gt;
发送时间: 2023年10月21日 22:40
收件人: Tencent/APIJSON ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Tencent/APIJSON] apijson-framework  6.2.0 springboot3  未合并发布 (Issue #600)





 
APIJSONController<T extends Object&gt; { public String get(String request, HttpSession session) { ... } public String get(String request, jakarta.servlet.http.HttpSession session) { ... } }
 我认为这种方案最可行，可以同时兼容，并且对于以往使用的开发者来说是无感的！

**Comment by liangxp** [comment]
> 好像不行，突然想起如果我只安装了 jdk17，打包应该会找不到 servlet 的包 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Ronny West ***@***.***&gt; 发送时间: 2023年10月21日 22:40 收件人: Tencent/APIJSON ***@***.***&gt; 抄送: Bill ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [Tencent/APIJSON] apijson-framework 6.2.0 springboot3 未合并发布 (Issue #600) APIJSONController<T extends Object&gt; { public String get(String request, HttpSession session) { ... } public String get(String request, jakarta.servlet.http.HttpSession session) { ... } } 我认为这种方案最可行，可以同时兼容，并且对于以往使用的开发者来说是无感的！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

直接引用即可
<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>4.0.1</version>
		</dependency>

**Comment by liangxp** [comment]
不过你应该要用JDK8打包
