### ISSUE TITLE
数据权限咨询

### ISSUE THREAD

**Issue by csx-bill** [Tencent/APIJSON#608]
### Description

这是我设计的数据权限 规则表，通过关联前端的菜单 添加规则

CREATE TABLE `sys_data_rule`  (
  `id` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '主键id',
  `menu_id` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT '0' COMMENT '菜单id',
  `rule_name` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '规则名称',
  `rule_column` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '字段',
  `rule_conditions` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '条件',
  `rule_value` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL COMMENT '规则值',
  `description` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '描述',
  `create_by` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `del_flag` int NULL DEFAULT 0 COMMENT '删除状态',
  `status` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT '0' COMMENT '状态',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_sp_parent_id`(`menu_id` ASC) USING BTREE,
  INDEX `idx_sp_del_flag`(`del_flag` ASC) USING BTREE,
  INDEX `idx_sp_status`(`status` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci COMMENT = '数据权限' ROW_FORMAT = DYNAMIC;

APIJSON  如何拦截到sql 那一步，我想实现 获取到执行的sql  添加数据规则

**Comment by csx-bill** [comment]
这个并不是我想要的，我是想通过自定义sql  把这个断规则 拼接到sql上，实现数据权限

**Comment by TommyLemon** [comment]
> 这个并不是我想要的，我是想通过自定义sql 把这个断规则 拼接到sql上，实现数据权限

建议在 DemoVerifier 重写 verify / verifyAcess 提前处理，参考这个用户的博文
https://blog.csdn.net/qq_45593068/article/details/121751336

如果等已经拼接好了 SQL，再拼上去，很可能拼错位置导致结果不符合预期，甚至执行报错 syntax error

**Comment by csx-bill** [comment]
我只是想把sql 拼接上去，这个博文，我貌似没有理解怎么把sql 拼接到 （已经拼接好了 SQL) 追加 sql条件 实现自定义 数据规则




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/APIJSON"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月1日(星期五) 凌晨0:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/APIJSON] 数据权限咨询 (Issue #608)





  
这个并不是我想要的，我是想通过自定义sql 把这个断规则 拼接到sql上，实现数据权限
  
建议在 DemoVerifier 重写 verify / verifyAcess 提前处理，参考这个用户的博文
 https://blog.csdn.net/qq_45593068/article/details/121751336
 
如果等已经拼接好了 SQL，再拼上去，很可能拼错位置导致结果不符合预期，甚至执行报错 syntax error

**Comment by TommyLemon** [comment]
不要在已经生成好了 SQL 后再拼接，否则很难确定应该把 SQL 片段拼接到复杂 SQL 的具体哪个位置，例如这个包含 JOIN 和子查询的 SQL：
![image](https://github.com/Tencent/APIJSON/assets/5738175/84931d6b-813e-4e30-b83f-53e04ba79f1d)

如果要拼接自定义 SQL 片段，可以用 @raw
https://github.com/Tencent/APIJSON/issues/165

**Comment by liangxp** [comment]
我也有类似场景，比如多租户，用户在查询的时候根据租户ID 还有表对应有查询的租户注解自动追加主表的租户字段作为条件查询

**Comment by TommyLemon** [comment]
> 我也有类似场景，比如多租户，用户在查询的时候根据租户ID 还有表对应有查询的租户注解自动追加主表的租户字段作为条件查询

@liangxp 
15.如何自动插入 create_time, update_time, creator_id, is_deleted 之类的业务上全局通用字段？
https://github.com/Tencent/APIJSON/issues/36

注解可以自己 User.class.getAnnotation(DemoAnnotation.class) 这样获取，参考
https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractVerifier.java#L176-L196

**Comment by liangxp** [comment]
> > 我也有类似场景，比如多租户，用户在查询的时候根据租户ID 还有表对应有查询的租户注解自动追加主表的租户字段作为条件查询
> 
> @liangxp 15.如何自动插入 create_time, update_time, creator_id, is_deleted 之类的业务上全局通用字段？ #36
> 
> 注解可以自己 User.class.getAnnotation(DemoAnnotation.class) 这样获取，参考 https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractVerifier.java#L176-L196

问题是，我想在所有SQL执行上加上一个条件，比如：where   tenant_id='当前登录用户所在域'。这个条件不能被接口调用人控制，只能通过代码层面控制，防止数据访问越权

**Comment by TommyLemon** [comment]
@liangxp 按我上面说的方式就行
