### ISSUE TITLE
[Bug] ApiJson的多数据源配置后，Spring多数据源配置失效

### ISSUE THREAD

**Issue by Xuxin19960702** [Tencent/APIJSON#621]
### APIJSON Version/APIJSON 版本号

6.0.0 APIJSONBoot-MultiDataSource

### Database Type & Version/数据库类型及版本号

MYSQL 5.7

### Environment/环境信息

```markdown
- JDK/基础库: 1.8.0_17
- OS/系统: 本地windows
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

图片复制上传不了，评论里补充

### Current Behavior/问题描述

```markdown
ApiJson接已有项目，发现接入后，原项目的Spring多数据源配置失效，是因为所有数据库连接都走ApiJson了吗？导致Mybatis没法用了。

求教作者
```

### Expected Behavior/期望结果

```markdown
ApiJson的多数据源和Spring多数据源配置都有效
```

**Comment by Xuxin19960702** [comment]
![IMG_47671](https://github.com/Tencent/APIJSON/assets/55312037/90159741-a954-41da-a859-9ca79c9e4f32)
![IMG_47672](https://github.com/Tencent/APIJSON/assets/55312037/8e53c652-c6c3-4713-bb21-b80517891d9e)

**Comment by TommyLemon** [comment]
这个和 APIJSON 应该没啥关系，可能是同时配置多个 Druid/HikariCP 对应的 Config Bean 读取同一份配置导致的，具体得你把引入 APIJSON 后改动的代码及配置(涉及账号/密码的可脱敏)发出来才好分析

**Comment by TommyLemon** [comment]
如果你的项目本身配置了连接池，那就没必须继续按 APIJSONBoot-MultiDatasource 等 Demo 加上里面的 DemoDataSourceConfig 类了

**Comment by Xuxin19960702** [comment]
确实会DataSource两边没法兼得，所以我全改成ApiJson了。但在重构成ApiJson的途中遇到一个特殊sql，例：select sid from `service` where (sale_source & 8) > 0;

**Comment by TommyLemon** [comment]
RAW_MAP.put("&", ""); // 位运算
<img width="1531" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/897c8456-7141-48f0-9713-b06679671e56">

https://apijson.cn/api?type=JSON&url=http%3A%2F%2Flocalhost%3A8080%2Fget&json={%22[]%22:{%22User%22:{%22@having%22:%22(id%20%26%208)%3E0%22,%22@raw%22:%22%40having%22,%22@explain%22:true}}}

<img width="1495" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/2c5ad33e-2893-4d2c-8009-1f31440e7822">
