### ISSUE TITLE
[Feature] 期望支持兼容JDK17

### ISSUE THREAD

**Issue by liangxp** [Tencent/APIJSON#622]
### Description

JDK17日益流行，建议兼容下！

**Comment by TommyLemon** [comment]
早就兼容了，你用着有什么问题吗？

**Comment by liangxp** [comment]
> 早就兼容了，你用着有什么问题吗？

新版本不是都用jakarta.servlet么，我看怎么session这些依然是javax.servlet这个包

**Comment by TommyLemon** [comment]
这个和 JDK17 无关，和 SpringBoot 3.x 有关
https://github.com/Tencent/APIJSON/issues/600

**Comment by liangxp** [comment]
已解决
