### ISSUE TITLE
[问题] 如何在APIJSONVerifier的verifyAccess动态拼接SQL

### ISSUE THREAD

**Issue by hooli67** [Tencent/APIJSON#625]
### Description
发现重写APIJSONVerifier的verifyAccess，可以通过

```
sqlConfig.putWhere("xxx", LoginHelper.getTenantId(), true);
// 最终SQL为 xxx = '值'
```
来实现动态条件的添加，但是想实现动态条件为 ：
```
where field in('1','2')
```
如何实现呢？

APIJSON版本：
6.1.0

**Comment by TommyLemon** [comment]
用  IN 就行了，具体看通用文档 功能符 说明
sqlConfig.putWhere("field{}", LoginHelper.getTenantIdList(), true);

**Comment by hooli67** [comment]
非常棒，解决了
