### ISSUE TITLE
[官网] 官网卡的一笔，作为一个部署在国内的 cn 域名网站，怎么做到的...

### ISSUE THREAD

**Issue by dren-a** [Tencent/APIJSON#628]
### Description

这么牛逼的开源库，官网卡的一笔，难以理解。

最扯的是还是用的 cn 域名部署在阿里云的，我怀疑是花了 39 买了一年的 1M 小水管的促销机，而且还没有 HTTPS...

**Comment by TommyLemon** [comment]
首页放了几个几 2-5Mb 的 GIF  图，之前把好几兆的 PNG/JPG 图片压缩后好了很多，不过 GIF 图影响也比较大
<img width="1531" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/49c11b3c-b389-474e-9dcb-dda260d9a7c7">

不是 39，一开始是 9.9，后面每年续费基本都要 600+ 了，这项目开源免费不挣钱，官网只是演示 Demo，可以自己拿源码和数据来部署，要不你赞助下升级服务器的费用？
<img width="920" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/90c624c1-c7e2-45b9-85a8-8befd0d5dec7">
