### ISSUE TITLE
能否去除原有的httpSession

### ISSUE THREAD

**Issue by lxqaoliao** [Tencent/APIJSON#630]
### Description

能否去除原有的httpSession，使用自己的权限认证的时候，apijson原有的httpSession导致了无法创建会话。请问如何解决

**Comment by hooli67** [comment]
开发者很忙的，很少回复， extends APIJSONVerifier这个类，自己去实现相关的校验逻辑

**Comment by TommyLemon** [comment]
APIJSON ORM 没有用到 HttpSession，apijson-framework 用了，你的问题详细贴出来，不然我也不好分析，更没时间和你一问一答来回确认细节

**Comment by TommyLemon** [comment]
按模板重新提 issue，这个 issue 不再回复
https://github.com/Tencent/APIJSON/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml&title=%5BBug%5D+
