### ISSUE TITLE
查询 数据字典 问题

### ISSUE THREAD

**Issue by csx-bill** [Tencent/APIJSON#635]
### Description

咨询个问题，例如在微服务中 查询返回数据，有个字段是数据字典解析出来text  需要 Feign  远程调用的， 所以我就用了 远程函数，现在遇到一个问题

{
    "[]":{
        "SysUser":{
            "status()": "translateDict(sys_user_status,status)"  //  status 不能取到 status的值 传过去，现在传过去的是 status 字符
        },
        "page":0,
        "count":5,
        "query":2
    },
    "info@":"/[]/info",
    "format":true
}

**Comment by TommyLemon** [comment]
先确定远程函数的调用优先级
https://github.com/Tencent/APIJSON/blob/master/Document.md#32-%E5%8A%9F%E8%83%BD%E7%AC%A6

以及 SysUser 对应的表里是否有 sys_user_status,status 这两个字段

拿到的是字符串，那是因为本来传参的 key 就是字符串，需要根据 key 从 curObj 里 get 出来对应的 value，参考 Demo 中其它远程函数的写法
https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONBoot-MultiDataSource/src/main/java/apijson/demo/DemoFunctionParser.java#L75-L231

或这个贡献者写的文档
https://github.com/APIJSON/apijson_todo_demo/blob/master/FULLTEXT.md#%E8%BF%9C%E7%A8%8B%E5%87%BD%E6%95%B0%E5%92%8C-function-%E8%A1%A8

**Comment by csx-bill** [comment]
sys_user_status 是字典的的code  为 key,  status 是sys_user 表的字段，我写了远程函数

**Comment by csx-bill** [comment]
并且函数 能调用进去，只是 status  传过去的是  status  字符

**Comment by csx-bill** [comment]
我好像理解了，我可以从 request 中获取到
![image](https://github.com/Tencent/APIJSON/assets/31872268/060921a9-4878-4b5b-96b4-56cec96621c7)

**Comment by csx-bill** [comment]
可以了，理解了
