### ISSUE TITLE
apijson-framework 6.2.0  idea 编译不通过了

### ISSUE THREAD

**Issue by csx-bill** [Tencent/APIJSON#636]
### Description

![image](https://github.com/Tencent/APIJSON/assets/31872268/98a63cb6-fdfd-4e88-93c4-01cf61c831d1)

**Comment by csx-bill** [comment]
6.2.0 版本  javax.servlet-api 升级 jakarta.servlet-api  jdk 升级为 17
 这个版本升级后 打包不通过了
![image](https://github.com/Tencent/APIJSON/assets/31872268/f17ff125-1c54-4d4d-a594-a244b4f88d39)

**Comment by csx-bill** [comment]
我这边fork APIJSON  升级了jdk为17  apijson-framework  就可以正常打包了，也就是说 APIJSON 需要创建一个分支

**Comment by csx-bill** [comment]
APIJSON  jitci 打包 配置 方便发送一份给我吗？
![image](https://github.com/Tencent/APIJSON/assets/31872268/6253c9bc-34f7-445d-8295-2f7657548418)

**Comment by TommyLemon** [comment]
用了还没发版的 APIJSONORM 新源码？

**Comment by csx-bill** [comment]
APIJSONORM  也是 6.2.0 版本的

**Comment by csx-bill** [comment]
fork主分支的代码

**Comment by TommyLemon** [comment]
> APIJSONORM 也是 6.2.0 版本的

看样是不是 6.2.0，而是发布了 6.2.0 后提交了一些 commit 之后的版本，可以用这个
https://github.com/APIJSON/apijson-framework/tree/6.2.0
对应发版 commit 是
https://github.com/APIJSON/apijson-framework/commit/fbcf3a520b3e3637da23cbca6104972934b17b89

**Comment by csx-bill** [comment]
我等下一个版本吧，都需要 升级springboot3 分支
APIJSON  需要你这边 开个分支 jdk  升级成 17

**Comment by TommyLemon** [comment]
可以的，不过我优先尝试同一套源码同时支持两种 HttpSession
