### ISSUE TITLE
access,resquest 加载的问题

### ISSUE THREAD

**Issue by aitedianaite** [Tencent/APIJSON#640]
### Description

大神~请教一个问题....access,resquest必须都加载再服务内存中吗,服务默认查询最多100条,在什么都不重写的情况下内存中REQUEST_MAP,ACCESS_MAP是不是也只能有100条,若这俩表后期数据量大了怎么处理呢,重新查询最大条数,全部加载在内存中会不会有问题呢?尤其是我现在用的resquest表数据量有点大呢

**Comment by TommyLemon** [comment]
必须，最新的几个版本对 Access, Request 等在 AbstractSQLConfig.SYSTEM_ACCESS_MAP 中的表名不做查询数量限制
