### ISSUE TITLE
1. ACCESS_FAKE_DELETE_MAP" is null  2. java.rmi.ServerException: 查询权限配置异常 !

### ISSUE THREAD

**Issue by csx-bill** [Tencent/APIJSON#641]
### Description

问题1
   重写 这个方法后 
@Override
    public boolean isFakeDelete() {
        return true;
    }
启动异常 信息

java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "apijson.orm.AbstractVerifier.ACCESS_FAKE_DELETE_MAP" is null

问题2
java.rmi.ServerException: 查询权限配置异常 !

![image](https://github.com/Tencent/APIJSON/assets/31872268/0edeb0ad-48c4-4daa-976d-629cd5eb17ec)

**Comment by csx-bill** [comment]
Log.DEBUG = false;  启动就会出现这个bug

**Comment by TommyLemon** [comment]
需要对 ACCESS_FAKE_DELETE_MAP 判空，或者初始化赋非空值
