### ISSUE TITLE
行级数据权限的实现

### ISSUE THREAD

**Issue by csx-bill** [Tencent/APIJSON#643]
### Description

request.put(ruleColumn,ruleValue);  可以直接 以 AND 拼接进去

例如实现 in  like  自定义 sql 这种条件 
我尝试 request.put(ruleColumn+"{}",ruleValue);   但是失败了， "{}"  会被清除掉，sql 就会出现 and (ruleColumn  ruleValue )
期望结果
AND `rule_value` in ( '1111') 

实际结果
AND `rule_value`  '1111'

![image](https://github.com/Tencent/APIJSON/assets/31872268/81705fb8-c892-4436-a258-a339ec8d0369)

![image](https://github.com/Tencent/APIJSON/assets/31872268/dabbbbd6-6237-477a-8bff-1a1ed1a16db3)

**Comment by TommyLemon** [comment]
用法错误，key{}:"条件" 是条件范围表达式，如果要用选项范围，必须是 key{}:[选项值]
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2

**Comment by csx-bill** [comment]
意思是 [选项值]  这个是个数组才对是吧

**Comment by TommyLemon** [comment]
对

**Comment by csx-bill** [comment]
好的，我试试

**Comment by csx-bill** [comment]
自定义sql  这个 可以实现吗

**Comment by TommyLemon** [comment]
@raw 支持自定义 SQL 片段

**Comment by TommyLemon** [comment]
> 下一个版本 预计 什么时候发呀

@csx-bill 
https://github.com/Tencent/APIJSON/releases/tag/6.2.8

https://jitpack.io/#Tencent/APIJSON/6.2.8

**Comment by TommyLemon** [comment]
https://github.com/APIJSON/APIJSON-Demo/commit/db5810da2a0fc7ff69de4ee7f9e13e769398fcb3

https://github.com/Tencent/APIJSON/releases/tag/6.3.0
https://github.com/APIJSON/apijson-framework/releases/tag/6.3.0
https://github.com/APIJSON/apijson-column/releases/tag/1.8.0
https://github.com/APIJSON/apijson-router/releases/tag/1.8.0

**Comment by csx-bill** [comment]
我尝试升级  APIJSON 6.3.0  版本升级为jdk17 在 https://jitci.com/ 打包的时候 chu出现的一个问题，你这是怎么处理的，因为pom 在 APIJSONORM 下
![image](https://github.com/Tencent/APIJSON/assets/31872268/a9765c9d-fd9c-4855-ab09-59a86a6604ec)

**Comment by TommyLemon** [comment]
> 我尝试升级 APIJSON 6.3.0 版本升级为jdk17 在 https://jitci.com/ 打包的时候 出现的一个问题，你这是怎么处理的，因为pom 在 APIJSONORM 下 ![image](https://private-user-images.githubusercontent.com/31872268/290786086-a9765c9d-fd9c-4855-ab09-59a86a6604ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTg0MzAsIm5iZiI6MTcwMjY1ODEzMCwicGF0aCI6Ii8zMTg3MjI2OC8yOTA3ODYwODYtYTk3NjVjOWQtZmQ5Yy00ODU1LWFiMDktNTlhODZhNjYwNGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE2MzUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNDJlYmFhNGVhZjIyMTlhNDlmZDNiMDQ2MGVjMzhiY2QxNmZkNmFjMzljYTE2N2FhYjQ4NDM3NDMwZmM3MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.899h8u5ZwCsg3uWIsTAoXOP--fsgRmwWBsls0b1QdhM)

试试 JDK 17 只用来打包你的业务项目，依赖的 APIJSON ORM 仍然用 JDK 1.8 打包

**Comment by csx-bill** [comment]
> > 我尝试升级 APIJSON 6.3.0 版本升级为jdk17 在 https://jitci.com/ 预算的时候出现的一个问题，你这是怎么处理的，因为pom在APIJSONORM下![图像](https://private-user-images.githubusercontent.com/31872268/290786086-a9765c9d-fd9c-4855-ab09-59a86a6604ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTg0MzAsIm5iZiI6MTcwMjY1ODEzMCwicGF0aCI6Ii8zMTg3MjI2OC8yOTA3ODYwODYtYTk3NjVjOWQtZmQ5Yy00ODU1LWFiMDktNTlhODZhNjYwNGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE2MzUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNDJlYmFhNGVhZjIyMTlhNDlmZDNiMDQ2MGVjMzhiY2QxNmZkNmFjMzljYTE2N2FhYjQ4NDM3NDMwZmM3MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.899h8u5ZwCsg3uWIsTAoXOP--fsgRmwWBsls0b1QdhM)
> 
> 尝试 JDK 17 只用于备用你的业务项目，依赖的 APIJSON ORM 仍然使用 JDK 1.8 备用
![image](https://github.com/Tencent/APIJSON/assets/31872268/ba645a76-deae-4b5b-a3b1-dff279f518c6)
我尝试用1.8 编译，还是一样，这个是用的主分支编译的，我看到你的编译日志 是有 进入 APIJSONORM 这个目录的一个步骤

**Comment by TommyLemon** [comment]
是要进入 APIJSONORM，因为这个才是工程源码根目录

**Comment by csx-bill** [comment]
所以想问下这块的配置



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TommyLemon ***@***.***&gt;
发送时间: 2023年12月17日 13:09
收件人: Tencent/APIJSON ***@***.***&gt;
抄送: Bill ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [Tencent/APIJSON] 行级数据权限的实现 (Issue #643)





 
是要进入 APIJSONORM，因为这个才是工程源码根目录
