### ISSUE TITLE
[问题] jitpack 上的springboot3版本似乎没发布成功

### ISSUE THREAD

**Issue by komiblog** [Tencent/APIJSON#659]
### Description

APIJSON的springboot3版本似乎没发布成功 
![图片](https://github.com/Tencent/APIJSON/assets/102006886/6fbc0450-66fb-4e20-897c-dbf450c6b4e4)
apijson-framework 的springboot3版本 没有随着版本更新
![图片](https://github.com/Tencent/APIJSON/assets/102006886/dcf1e9fe-a557-47f2-b931-321ee58a17d5)

**Comment by TommyLemon** [comment]
目前需要单独发一个兼容 SpringBoot3 的版本
https://github.com/Tencent/APIJSON/issues/600

**Comment by komiblog** [comment]
请问该怎么做呢？我注意到springboot3单独分了分支，是分支上兼容的工作还没做完吗？还是说 等待你这边的发布即可？

**Comment by TommyLemon** [comment]
发了 6.4.0-springboot3 版本
https://github.com/Tencent/APIJSON/releases/tag/6.4.0-springboot3

但目前构建报错 "Fatal error compiling: invalid target release: 17"，需要再解决这个才能用 Maven 等远程依赖
https://jitpack.io/com/github/Tencent/APIJSON/6.4.0-springboot3/build.log

**Comment by komiblog** [comment]
感谢发布。
构建错误是不是由于使用了java8 编译？
另外，请问apijson-framework那边也能发布一个springboot3版本吗？ 
我还是新手，可能不能提供有效的帮助，但是如果告诉我怎么做，我可以帮忙

**Comment by TommyLemon** [comment]
执行了 java 17 编译无效，还是用了 java 8 编译
https://github.com/Tencent/APIJSON/blob/6.4.0-springboot3/APIJSONORM/pom.xml#L17-L19

apijson-framework 同样也是合并 master 分支到 springboot3 分支即可。
我看到 APIJSON 的 pom.xml 比 apijson-framework 的少了 3 个 encoding 配置，可能这是编译报错的原因
https://github.com/APIJSON/apijson-framework/blob/springboot_3/pom.xml#L15-L18

可以复制到 APIJSON 的 pom.xml，提个 PR：
https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%80%E5%AE%9A%E8%A6%81%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81

**Comment by komiblog** [comment]
似乎只缺了一个配置，已提交PR。
apijson-framework 那边等我有空去合并一下，再提交PR

**Comment by TommyLemon** [comment]
还是一样的问题：
https://github.com/Tencent/APIJSON/releases/tag/6.4.1-springboot3

https://jitpack.io/com/github/Tencent/APIJSON/6.4.1-springboot3/build.log

**Comment by TommyLemon** [comment]
本地 IDE 倒是可以打包成功，可能 jitpack 需要特殊配置，或者平台目前还不支持 JDK 17
<img width="1532" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/666a014c-01a0-466e-857e-bd6244f806ab">

**Comment by komiblog** [comment]
我注意到 build.log 里仍然在使用java8作为编译环境。
那应该是jitpack的问题，我去查一下解决方法

**Comment by TommyLemon** [comment]
解决了
https://jitpack.io/com/github/Tencent/APIJSON/6.4.2-springboot3/build.log

https://github.com/jitpack/jitpack.io/issues/5165

**Comment by komiblog** [comment]
好的，多谢！
等 apijson-framework  那边的springboot3版本发布，我就把这个 issue 关闭

**Comment by DenineLu** [comment]
apijson-framework现在有计划发布springboot3版本吗？

**Comment by TommyLemon** [comment]
@komiblog  理解

**Comment by komiblog** [comment]
为回馈开源，我在 [APIJSON/APIJSON-Demo](https://github.com/APIJSON/APIJSON-Demo) 中提交了一个Demo, 也算是我近期的工作成果，希望能帮助到入门的新手
希望作者有空能审阅一下那个PR，谢谢😊

**Comment by TommyLemon** [comment]
@komiblog 赞，感谢 ❤️
