### ISSUE TITLE
[Bug] APIJSON-DEMO中的Function.sql父类方法名错误

### ISSUE THREAD

**Issue by JupiterFeng** [Tencent/APIJSON#666]
### APIJSON Version/APIJSON 版本号

6.3.0

### Database Type & Version/数据库类型及版本号

mysql8.2.0

### Environment/环境信息

```markdown
JDK/基础库: 1.8.0_17
OS/系统: windows11
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

null

### Current Behavior/问题描述

```markdown
getMethodDefinition是父类APIJSONFunctionParser中存在的方法名

初始化sql  sys_Function.sql中 id=18 有一个方法名为getMethodDefination的错误配置
```

**Comment by TommyLemon** [comment]
在 Function 表删掉 name='getMethodDefination' 的配置即可。

apijson-framework 6.3.0 删掉了这个早就标记为 [@deprecated](https://gitee.com/jianhuaw) 的方法，用正确拼写 getMethodDefinition 替代。

https://gitee.com/Tencent/APIJSON/issues/I8PRLR

**Comment by JupiterFeng** [comment]
![image](https://github.com/Tencent/APIJSON/assets/134389159/c807e4e3-dc05-49b1-9cff-52c8c068cda0)
我看确实是有这段方法名和NullPointerException输出不太一致的代码 如果确认无误我可以关闭了

> 在 Function 表删掉 name='getMethodDefination' 的配置即可。
> 
> apijson-framework 6.3.0 删掉了这个早就标记为 [@deprecated](https://gitee.com/jianhuaw) 的方法，用正确拼写 getMethodDefinition 替代。
> 
> https://gitee.com/Tencent/APIJSON/issues/I8PRLR

**Comment by TommyLemon** [comment]
是这样

**Comment by TommyLemon** [comment]
是这样
