### ISSUE TITLE
文档醒目位置没有Getting started，没有说明如何运行这个项目

### ISSUE THREAD

**Issue by jsonhet** [Tencent/APIJSON#688]
### Description

花了2个小时才找到https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server 这个文档

**Comment by TommyLemon** [comment]
<img width="941" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/3d56da91-d6dc-45f2-afa1-79a54087705a">
<img width="866" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/8b44828a-0956-4511-8bc0-820ff459ce4c">

https://github.com/Tencent/APIJSON?tab=readme-ov-file#%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B
