### ISSUE TITLE
希望新增“导出查询结果到excel”的功能

### ISSUE THREAD

**Issue by CarsonYue** [Tencent/APIJSON#694]
### Description

针对查询结果 支持导出到excel并下载

**Comment by TommyLemon** [comment]
APIJSON 是专为后端对接数据库增删改查的 ORM 库，没有 UI，和 Excel 没有强相关关系，这个功能没有必要实现。
如果你希望在 APIAuto-机器学习零代码接口工具 上新增支持导出 Excel，可以去这个项目提 issue
https://github.com/TommyLemon/APIAuto
