### ISSUE TITLE
请求信息中日期/时间的处理方法

### ISSUE THREAD

**Issue by chendongcool** [Tencent/APIJSON#696]
### Description

1。 请求参数中时间段的参数如何实现，并且怎么兼容如mysql 和oracle 多种数据库，或者多种日期格式如：20240401160101,2024-04-01 16：01:01
{
  "[]": {
    "testTable1": {
      "update_time": "起始时间,结束时间",
    
    }
  }
}

**Comment by TommyLemon** [comment]
"update_time>=": "起始时间",
"update_time<=": "结束时间"

issues 里搜下 日期 可以找到多个类似问题：
