### ISSUE TITLE
[Bug] SQL注入风险

### ISSUE THREAD

**Issue by PittyXu** [Tencent/APIJSON#704]
### APIJSON Version/APIJSON 版本号

6.3.0

### Database Type & Version/数据库类型及版本号

MySQL 5.7.42

### Environment/环境信息

```markdown
- JDK/基础库:11
- OS/系统:MacOS
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

20240418175657.jpg

### Current Behavior/问题描述

```markdown
发现源码SQL生成是通过拼接完成，数据和代码没有分离，有SQL注入风险；

本地测试确实有SQL注入风险，不知道官方服务器是什么数据库，未在官方地址复现。
本地通过apiJSON_framwork集成, 采用MySQL数据库，请求如下：

{
    "[]": {
        "Request": {
            "method": "POST\\')) union select 1, 2,3,4,5,6,7, (select group_concat(table_name) from information_schema.tables ) #"
        }
    }
}
```

**Comment by PittyXu** [comment]
![20240418175657](https://github.com/Tencent/APIJSON/assets/4374151/e75e8086-dfca-4dbd-a9ce-6684690da4c2)

**Comment by TommyLemon** [comment]
基本只有两种可能：
1.关了预编译
   断点调试下 AbstractSQLConfig.isPrepared 返回值

2.实际用的不是 MySQL，而是 TDengine 等不支持预编译的数据库
   断点调试下 AbstractSQLConfig.getSQLDatabase 返回值

**Comment by TommyLemon** [comment]
官网用的 MySQL 是 5.7.34 社区版

**Comment by PittyXu** [comment]
@TommyLemon  `isPrepared` 调用的地方有很多，初始进入都是为true, 但如下代码会设置为 false.

![image](https://github.com/Tencent/APIJSON/assets/4374151/945ec192-1853-429d-96f2-c0eb36f5d119)

![image](https://github.com/Tencent/APIJSON/assets/4374151/1e05af23-f411-4c8f-9d52-637760875f19)

![image](https://github.com/Tencent/APIJSON/assets/4374151/ab3f3ef5-a6a8-4719-9dd7-ac0a0b1d4b88)

**Comment by TommyLemon** [comment]
一开始 prepared = false 只是为了打印 SQL，以及用 SQL 作为缓存 key。
实际执行时 prepared = true，SQL 都是 WHERE `column` = ? 然后 preparedStatement.setObject(value)
可以再断点调试 AbstractSQLExecutor.executeQuery 和 executeUpdate，看看是不是用 PreparedStatement

**Comment by PittyXu** [comment]
重启后不知道为啥，无法复现了
