### ISSUE TITLE
[提问] 请问支持自定义角色 、 RBAC 吗？

### ISSUE THREAD

**Issue by shengzhou1216** [Tencent/APIJSON#733]
### Description

场景：后台管理中可配置角色、角色权限等

**Comment by BA7IEE** [comment]
俺也需要

**Comment by TommyLemon** [comment]
常见问题
2.如何控制权限？
在 Access 表配置校验规则，默认不允许访问，需要对 每张表、每种角色、每种操作 做相应的配置，粒度细分到行级
https://github.com/Tencent/APIJSON/issues/12

<img width="1091" alt="image" src="https://github.com/user-attachments/assets/e5eab8ce-ead9-443c-9cbb-32f4ef4577e8" />
