### ISSUE TITLE
[Bug] 批量新增和修改报错417

### ISSUE THREAD

**Issue by ansyxpf** [Tencent/APIJSON#736]
### APIJSON Version/APIJSON 版本号

6.1.0

### Database Type & Version/数据库类型及版本号

5.6.25

### Environment/环境信息

```markdown
- JDK/基础库:1.8.0_342
- OS/系统:MasOS Sonoma 14.3.1(23D60) Intel
```

### APIAuto Screenshots/APIAuto 请求与结果完整截屏

https://smms.app/image/7AQaDr1upsFIwjJ

### Current Behavior/问题描述

```markdown
批量新增和修改都报错417，找不到解决方案
```

### Expected Behavior/期望结果

```markdown
单个修改可以正常使用，期望批量修改也可以正常使用
```

**Comment by TommyLemon** [comment]
看起来应该是重写了 getIdKey return null 导致，这个值不能为 null

**Comment by ansyxpf** [comment]
@Override
			public String getIdKey(String database, String schema, String datasource, String table) {
				String primaryKey = "id";
				switch (table) {
					case "Tbl_receiving_detail":
						primaryKey = "ReceivingDetailID";
						break;
				}
				return primaryKey;
			}
			这是我重写的getIdKey方法，有什么问题吗？主键为id的表批量修改的时候也会报同样的错误

> 看起来应该重写了 getIdKey 返回 null 导致 NPE 空指针异常，这个值不能为 null <img alt="图像" width="1529" src="https://private-user-images.githubusercontent.com/5738175/337848996-0d6c91de-e19e-42ab-ab7f-944aa8055cc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjg2MDIsIm5iZiI6MTcxODA2ODMwMiwicGF0aCI6Ii81NzM4MTc1LzMzNzg0ODk5Ni0wZDZjOTFkZS1lMTllLTQyYWItYWI3Zi05NDRhYTgwNTVjYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDExMTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU0ZjMwYzc3MDVjOGU1NWJmOWJiZjk3OThkNzZiZTgxZWY1ZDFkMzY4NmQ0ZTNmMDI1Y2JlOWQ3NWE2Njc1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7Dm7PotBxSq11WnT_O1dblsznXaseoPmjkXWTmBuFKc">
