### ISSUE TITLE
查询不到数据，出参应该有当前结构而不是什么都不返回怎么设置呢？数据库字段采用驼峰如何设置（除了用字段名映射）

### ISSUE THREAD

**Issue by gxmanito** [Tencent/APIJSON#738]
### Description

6.1.0版本
jdk8

1. 查询不到数据，出参应该有当前结构而不是什么都不返回怎么设置呢，且某个字段为空也要返回当前key;
2. 入参空字符串不作为where条件；
3. 如何添加默认的入参？

**Comment by TommyLemon** [comment]
注意事项：
https://github.com/Tencent/APIJSON?tab=readme-ov-file#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
