### ISSUE TITLE
分页查询拼接SQL时，总数对不上问题

### ISSUE THREAD

**Issue by gxmanito** [Tencent/APIJSON#762]
### Description

![image](https://github.com/user-attachments/assets/0741096f-7522-4373-a6bd-8f0ff78b6c20)
如图，分页查询添加数据权限，拼接where，但是count时未拼接条件
![image](https://github.com/user-attachments/assets/74e76c21-d2bc-4ace-aa0c-896ed3649df3)
![image](https://github.com/user-attachments/assets/fc785052-d101-431b-9094-2cdd4e09a941)

**Comment by TommyLemon** [comment]
看起来是自定义代码 isGetMethod 只盼断了 GET，没判断 HEAD，拦截掉了统计数量 count SQL 的自定义条件导致。
解决了的问题，麻烦回复下已解决，最好说明解决方式，帮助后面的人，谢谢

**Comment by gxmanito** [comment]
https://github.com/Tencent/APIJSON/issues/762#issuecomment-2358866027

是的，拦截掉了统计数量 count SQL 的自定义条件导致的，改成以下即可解决
![image](https://github.com/user-attachments/assets/43bb45c6-adbf-4aad-a6a0-19cc93f0ca3d)
