### ISSUE TITLE
如何去掉这些默认的debug信息

### ISSUE THREAD

**Issue by sonamkumary** [Tencent/APIJSON#780]
### Description

![图片](https://github.com/user-attachments/assets/00b4614b-2fea-4b5a-b7b5-c54791f5b410)
如何去掉  "debug:info|help": " \n提 bug 请发请求和响应的【完整截屏】，没图的自行解决！ \n开发者有限的时间和精力主要放在【维护项目源码和文档】上！ \n【描述不详细】 或 【文档/常见问题 已有答案】 的问题可能会被忽略！！ \n【态度 不文明/不友善】的可能会被踢出群，问题也可能不予解答！！！ \n\n **环境信息**  \n系统: Windows 10 10.0 \n数据库: DEFAULT_DATABASE = MYSQL \nJDK: 21.0.4 amd64 \nAPIJSON: 7.0.3 \n   \n【常见问题】：https://github.com/Tencent/APIJSON/issues/36 \n【通用文档】：https://github.com/Tencent/APIJSON/blob/master/Document.md \n【视频教程】：https://search.bilibili.com/all?keyword=APIJSON",

**Comment by shiliting** [comment]
![Image](https://github.com/user-attachments/assets/d3403c69-509c-4f7f-a871-2c315344e8f3)
